# Generated by Django 5.2.15 on 2026-06-23 08:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('public', 'Public — anyone can use it'), ('alliance', 'Corp & alliance members only'), ('corp', 'Corp members only'), ('disabled', 'Disabled')], default='alliance', max_length=10)),
                ('highsec_pct', models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=4)),
                ('lowsec_pct', models.DecimalField(decimal_places=3, default=Decimal('0.850'), max_digits=4)),
                ('nullsec_pct', models.DecimalField(decimal_places=3, default=Decimal('0.800'), max_digits=4)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BuybackOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_character_id', models.BigIntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('sec_band', models.CharField(choices=[('highsec', 'Highsec'), ('lowsec', 'Lowsec'), ('nullsec', 'Nullsec / wormhole')], default='highsec', max_length=10)),
                ('rate_pct', models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=4)),
                ('items', models.JSONField(blank=True, default=list)),
                ('item_count', models.IntegerField(default=0)),
                ('volume_m3', models.FloatField(default=0.0)),
                ('jita_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('offer_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('purchased', 'Purchased'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('buyer_character_id', models.BigIntegerField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyback_purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyback_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
