# Generated by Django 5.2.16 on 2026-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0003_guaranteed_buyback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guaranteedbuyout',
            new_name='buyback_gua_status_21a63e_idx',
            old_name='buyback_gua_status_idx',
        ),
        migrations.AlterField(
            model_name='guaranteedbuybackconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guaranteedbuyout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
