# Generated by Django 5.2.15 on 2026-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsiblexBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('from_system_id', models.IntegerField()),
                ('from_system_name', models.CharField(blank=True, max_length=100)),
                ('to_system_id', models.IntegerField()),
                ('to_system_name', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['from_system_name', 'to_system_name'],
                'unique_together': {('from_system_id', 'to_system_id')},
            },
        ),
    ]
