# Generated by Django 5.2.15 on 2026-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CynoBeacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_id', models.IntegerField(unique=True)),
                ('system_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('structure_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('esi', 'ESI sync')], default='manual', max_length=8)),
            ],
            options={
                'ordering': ['system_name'],
            },
        ),
        migrations.AddField(
            model_name='ansiblexbridge',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('esi', 'ESI sync')], default='manual', max_length=8),
        ),
        migrations.AddField(
            model_name='ansiblexbridge',
            name='structure_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
