# Generated by Django 5.2.15 on 2026-07-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('custom', 'Custom')], default='', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('default_channels', models.JSONField(blank=True, default=list)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=12)),
                ('required_vars', models.JSONField(blank=True, default=list)),
                ('is_official', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=12)),
                ('severity', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automation', 'Automation rule'), ('scheduled', 'Scheduled'), ('service', 'Service-emitted')], default='manual', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partial failure'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('confirmation', models.JSONField(blank=True, default=dict)),
                ('custom_message', models.BooleanField(default=False)),
                ('source_service', models.CharField(blank=True, default='', max_length=40)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('recipient_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pingboard.alerttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in_app', 'In-app'), ('eve_mail', 'EVE Mail'), ('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=16)),
                ('label', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('routing', models.JSONField(blank=True, default=dict)),
                ('_secret', models.TextField(blank=True, db_column='secret_enc', default='')),
                ('supports_direct', models.BooleanField(default=False)),
                ('supports_group', models.BooleanField(default=False)),
                ('supports_channel', models.BooleanField(default=False)),
                ('max_classification', models.CharField(blank=True, default='', max_length=24)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kind', 'label'],
                'indexes': [models.Index(fields=['kind', 'enabled'], name='pingboard_c_kind_d23f50_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in_app', 'In-app'), ('eve_mail', 'EVE Mail'), ('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rate_limited', 'Rate limited')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=4)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('recipients_ok', models.IntegerField(default=0)),
                ('recipients_failed', models.IntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pingboard.alert')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pingboard.channelprovider')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in_app', 'In-app'), ('eve_mail', 'EVE Mail'), ('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('recipient_type', models.CharField(max_length=24)),
                ('recipient_ref', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rate_limited', 'Rate limited')], default='pending', max_length=12)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='pingboard.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'indexes': [models.Index(fields=['alert', 'kind'], name='pingboard_a_alert_i_b0bd2b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'scheduled_at'], name='pingboard_a_status_1e3e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category', 'priority', 'created_at'], name='pingboard_a_categor_6d1b16_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source_service', 'source_object_id'], name='pingboard_a_source__05180a_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='pb_alert_idem'),
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'kind', 'provider'), name='pb_delivery_once'),
        ),
    ]
