# Generated by Django 5.2.15 on 2026-07-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0002_import_notification_channels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('slack', 'Slack'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord')], max_length=16)),
                ('handle', models.CharField(blank=True, default='', max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('verify_code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingboard_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'indexes': [models.Index(fields=['kind', 'handle'], name='pingboard_p_kind_a1f66e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='pb_contact_user_kind')],
            },
        ),
    ]
