# Generated by Django 5.2.15 on 2026-07-03 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0003_pilotcontactchannel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('scheduled_alert', 'Scheduled alert'), ('fleet_op', 'Fleet operation'), ('emergency_fleet', 'Emergency fleet'), ('mining', 'Mining operation'), ('moon_extraction', 'Moon extraction'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('logistics', 'Logistics event'), ('buyback', 'Buyback event'), ('mentorship', 'Mentorship event'), ('announcement', 'Corporation announcement'), ('custom', 'Custom timer')], db_index=True, max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('synced', 'Synced'), ('sync_conflict', 'Sync conflict')], db_index=True, default='scheduled', max_length=16)),
                ('source_system', models.CharField(blank=True, default='', max_length=40)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_manual', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('locked_fields', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(default='member', max_length=16)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('default_channels', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_minutes_before', models.IntegerField(default=0)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=12)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('cancelled', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pingboard.alert')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_schedules', to='pingboard.calendarevent')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pingboard.alerttemplate')),
            ],
            options={
                'ordering': ['-offset_minutes_before'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=40)),
                ('source_object_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(max_length=16)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_events', to='pingboard.calendarevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type', 'start_at'], name='pingboard_c_event_t_0668c1_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['status', 'start_at'], name='pingboard_c_status_da4d7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_system__gt', '')), fields=('source_system', 'source_object_id'), name='pb_calevent_source'),
        ),
        migrations.AddConstraint(
            model_name='calendareventalert',
            constraint=models.UniqueConstraint(fields=('event', 'offset_minutes_before', 'template'), name='pb_evt_alert_once'),
        ),
        migrations.AddIndex(
            model_name='calendarsyncevent',
            index=models.Index(fields=['source_system', 'source_object_id'], name='pingboard_c_source__ff9efb_idx'),
        ),
    ]
