# Generated by Django 5.2.15 on 2026-07-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0004_calendarevent_calendareventalert_calendarsyncevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pingboard.calendarevent'),
        ),
    ]
