# Generated by Django 5.2.15 on 2026-07-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0005_alert_calendar_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('trigger_source', models.CharField(db_index=True, max_length=60)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=12)),
                ('cooldown_minutes', models.IntegerField(default=0)),
                ('max_per_window', models.IntegerField(default=0)),
                ('window_minutes', models.IntegerField(default=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pingboard.alerttemplate')),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['trigger_source', 'enabled'], name='pingboard_a_trigger_f98c11_idx')],
            },
        ),
    ]
