# Generated by Django 5.2.15 on 2026-07-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0006_automationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='automation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pingboard.automationrule'),
        ),
    ]
