# Generated by Django 5.2.16 on 2026-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingboard', '0011_pilotchannelpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('campaign', 'Campaign'), ('custom', 'Custom')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('campaign', 'Campaign'), ('custom', 'Custom')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('campaign', 'Campaign'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pilotchannelpreference',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('home_defence', 'Home defence'), ('mining', 'Mining'), ('moon_extraction', 'Moon extraction'), ('pvp_fleet', 'PvP fleet'), ('roaming_gang', 'Roaming gang'), ('gatecamp', 'Gatecamp'), ('logistics', 'Logistics'), ('buyback', 'Buyback'), ('mentorship', 'Mentorship'), ('industry_job', 'Industry job'), ('structure_timer', 'Structure timer'), ('announcement', 'Corporation announcement'), ('system', 'System notification'), ('campaign', 'Campaign'), ('custom', 'Custom')], max_length=20),
        ),
    ]
