# Generated by Django 5.2.16 on 2026-07-10 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskevent_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['related_type', 'related_id'], name='tasks_task_related_456f28_idx'),
        ),
    ]
