# Generated by Django 5.2.15 on 2026-06-23 09:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('public', 'Public — anyone can shop'), ('alliance', 'Corp & alliance members only'), ('corp', 'Corp members only'), ('disabled', 'Disabled')], default='alliance', max_length=10)),
                ('doctrine_markup', models.DecimalField(decimal_places=3, default=Decimal('1.100'), max_digits=5)),
                ('hull_markup', models.DecimalField(decimal_places=3, default=Decimal('1.100'), max_digits=5)),
                ('deposit_pct', models.DecimalField(decimal_places=3, default=Decimal('0.250'), max_digits=4)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_character_id', models.BigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('doctrine_fit', 'Ready-to-fly doctrine ship'), ('hull', 'Made-to-order hull')], max_length=12)),
                ('fit_name', models.CharField(blank=True, max_length=200)),
                ('ship_type_id', models.IntegerField()),
                ('ship_name', models.CharField(blank=True, max_length=200)),
                ('hull_class', models.CharField(choices=[('subcap', 'Sub-capital'), ('capital', 'Capital'), ('supercapital', 'Supercapital')], default='subcap', max_length=12)),
                ('manifest', models.JSONField(blank=True, default=list)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_jita', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('markup_pct', models.DecimalField(decimal_places=3, default=Decimal('1.100'), max_digits=5)),
                ('deposit_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('requires_build', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('deposit_paid', 'Deposit paid'), ('in_production', 'In production'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='open', max_length=14)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('claimed_by_character_id', models.BigIntegerField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_fulfilments', to=settings.AUTH_USER_MODEL)),
                ('doctrine_fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='doctrines.doctrinefit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
