# Generated by Django 5.2.16 on 2026-07-16 10:12
#
# Per-hull-class store pricing: capital/supercapital hulls are priced off their
# estimated build cost × a leader-set profit multiplier instead of Jita sell.
# ``db_default`` on every new column is load-bearing for rollback safety: it keeps
# the DEFAULT in the database, so a code-only rollback to pre-0002 code (which
# INSERTs without these columns) still works — same pattern as capsuleer 0005.

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='capital_markup',
            field=models.DecimalField(db_default=Decimal('1.100'), decimal_places=3, default=Decimal('1.100'), max_digits=5),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='supercap_markup',
            field=models.DecimalField(db_default=Decimal('1.100'), decimal_places=3, default=Decimal('1.100'), max_digits=5),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='price_basis',
            field=models.CharField(choices=[('jita', 'Jita sell price'), ('build', 'Estimated build cost')], db_default='jita', default='jita', max_length=5),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='unit_cost',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=0, max_digits=20),
        ),
    ]
