# Generated by Django 5.2.16 on 2026-07-16 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0007_doctrinefit_ordering'),
        ('erp', '0007_buildjob_i18n_keys'),
        ('industry', '0005_consume_materials_on_delivery'),
        ('market', '0004_marketwatch'),
        ('store', '0002_storeconfig_capital_markup_and_more'),
        ('tasks', '0003_task_tasks_task_related_456f28_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_offered', models.BooleanField(db_default=True, default=True, help_text='Offer this fit for sale on the Shipyard.')),
                ('backorders_allowed', models.BooleanField(blank=True, help_text='Override the corp-wide backorder policy for this fit.', null=True)),
                ('lead_days', models.PositiveIntegerField(blank=True, help_text='Override the default backorder lead time (days).', null=True)),
                ('max_backorder_quantity', models.PositiveIntegerField(blank=True, help_text='Most units allowed on backorder per order for this fit.', null=True)),
                ('max_per_order', models.PositiveIntegerField(blank=True, help_text='Override the maximum quantity per order.', null=True)),
                ('safety_stock', models.PositiveIntegerField(db_default=0, default=0, help_text='Units held back from planning as a strategic reserve.')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Flag this fit for restocking when available stock falls to this level.', null=True)),
                ('target_stock', models.PositiveIntegerField(blank=True, help_text='How many complete ships the corp aims to keep stocked.', null=True)),
                ('preferred_fulfilment', models.CharField(choices=[('stock', 'Use stocked ships'), ('build', 'Build locally'), ('import', 'Import from Jita'), ('supplier', 'Buy from an approved supplier'), ('auto', 'Choose build or buy automatically')], db_default='auto', default='auto', max_length=10)),
                ('buyer_notes', models.CharField(blank=True, db_default='', default='', help_text='Shown to buyers on the Shipyard card.', max_length=300)),
                ('internal_notes', models.CharField(blank=True, db_default='', default='', help_text='Fulfilment notes visible to members and officers only.', max_length=300)),
                ('priority', models.IntegerField(db_default=0, default=0, help_text='Higher = restock sooner.')),
            ],
            options={
                'ordering': ['fit_id'],
            },
        ),
        migrations.CreateModel(
            name='FitReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.BigIntegerField(db_default=0, default=0)),
                ('manifest_hash', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Stock received'), ('adjustment', 'Manual adjustment'), ('consumed', 'Delivered to buyer'), ('reconciliation', 'Reconciliation'), ('revalidation', 'Fit revision revalidated')], max_length=14)),
                ('delta', models.BigIntegerField(default=0)),
                ('balance_after', models.BigIntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'fit stock entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FitSupplyNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12)),
                ('quantity_required', models.BigIntegerField(default=0)),
                ('required_by', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FitWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'fit waitlist entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipyardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backorders_enabled', models.BooleanField(db_default=True, default=True, help_text='Accept orders for doctrine ships that are not in stock.')),
                ('default_lead_days', models.PositiveIntegerField(db_default=7, default=7, help_text='Default estimated days to fulfil a backorder.')),
                ('allow_partial_fulfilment', models.BooleanField(db_default=True, default=True, help_text='Allow one order to combine reserved stock with a backordered remainder.')),
                ('reservation_expiry_days', models.PositiveIntegerField(db_default=0, default=0, help_text='Release reservations of orders nobody has claimed after this many days (0 = never).')),
                ('max_order_quantity', models.PositiveIntegerField(db_default=10, default=10, help_text='Most ships one order may request unless a fit overrides it.')),
                ('limited_stock_threshold', models.PositiveIntegerField(db_default=2, default=2, help_text="Show 'Limited stock' when this many or fewer ships remain.")),
                ('show_unavailable', models.BooleanField(db_default=True, default=True, help_text='Keep out-of-stock ships visible on the Shipyard (greyed out) instead of hiding them.')),
                ('available_only_default', models.BooleanField(db_default=False, default=False, help_text='Open the Shipyard filtered to immediately available ships.')),
                ('waitlist_enabled', models.BooleanField(db_default=False, default=False, help_text="Let pilots join a waitlist for ships that can't be ordered.")),
                ('auto_allocate_receipts', models.BooleanField(db_default=True, default=True, help_text='When stock arrives, reserve it for waiting backorders automatically (oldest first).')),
            ],
            options={
                'verbose_name': 'shipyard policy',
                'verbose_name_plural': 'shipyard policies',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='storeorder',
            name='actual_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='availability_state',
            field=models.CharField(blank=True, choices=[('ready', 'Reserved from stock'), ('partial', 'Partially reserved, remainder backordered'), ('backorder', 'Backordered')], db_default='', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='backorder_acknowledged',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='current_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='delay_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='market.marketlocation'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='eta_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='eta_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='lead_days_assumed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='manifest_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='promised_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quantity_backordered',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quantity_reserved',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status'], name='store_store_status_7dae12_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['current_eta'], name='store_store_current_6edd07_idx'),
        ),
        migrations.AddField(
            model_name='fitoffer',
            name='delivery_location',
            field=models.ForeignKey(blank=True, help_text='Override the default delivery location for this fit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation'),
        ),
        migrations.AddField(
            model_name='fitoffer',
            name='fit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='doctrines.doctrinefit'),
        ),
        migrations.AddField(
            model_name='fitoffer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_reservations', to='store.storeorder'),
        ),
        migrations.AddField(
            model_name='fitstock',
            name='doctrine_fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='doctrines.doctrinefit'),
        ),
        migrations.AddField(
            model_name='fitstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fit_stocks', to='market.marketlocation'),
        ),
        migrations.AddField(
            model_name='fitreservation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='store.fitstock'),
        ),
        migrations.AddField(
            model_name='fitstockentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitstockentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='store.storeorder'),
        ),
        migrations.AddField(
            model_name='fitstockentry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='store.fitstock'),
        ),
        migrations.AddField(
            model_name='fitsupplyneed',
            name='build_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erp.buildjob'),
        ),
        migrations.AddField(
            model_name='fitsupplyneed',
            name='doctrine_fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_needs', to='doctrines.doctrinefit'),
        ),
        migrations.AddField(
            model_name='fitsupplyneed',
            name='industry_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='industry.industryproject'),
        ),
        migrations.AddField(
            model_name='fitsupplyneed',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation'),
        ),
        migrations.AddField(
            model_name='fitsupplyneed',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='fitwaitlistentry',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='doctrines.doctrinefit'),
        ),
        migrations.AddField(
            model_name='fitwaitlistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipyardpolicy',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text='Where doctrine ships are stocked and delivered unless a fit overrides it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation'),
        ),
        migrations.AddConstraint(
            model_name='fitstock',
            constraint=models.UniqueConstraint(fields=('doctrine_fit', 'location', 'manifest_hash'), name='uniq_fitstock_fit_location_hash'),
        ),
        migrations.AddConstraint(
            model_name='fitstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='fitstock_on_hand_gte_0'),
        ),
        migrations.AddIndex(
            model_name='fitreservation',
            index=models.Index(fields=['stock', 'status'], name='store_fitre_stock_i_0afce5_idx'),
        ),
        migrations.AddIndex(
            model_name='fitreservation',
            index=models.Index(fields=['order', 'status'], name='store_fitre_order_i_4ab7dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='fitreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='fitreservation_qty_gte_1'),
        ),
        migrations.AddIndex(
            model_name='fitstockentry',
            index=models.Index(fields=['stock', '-created_at'], name='store_fitst_stock_i_9ae39c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fitsupplyneed',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'in_progress'))), fields=('doctrine_fit', 'location'), name='uniq_live_supplyneed_per_fit_location', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='fitwaitlistentry',
            constraint=models.UniqueConstraint(fields=('fit', 'user'), name='uniq_fit_waitlist_entry'),
        ),
    ]
