# Generated by Django 5.2.16 on 2026-07-16 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0008_remove_doctrine_is_public_preview_and_more'),
        ('store', '0003_fitoffer_fitreservation_fitstock_fitstockentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('history_weeks', models.PositiveIntegerField(db_default=12, default=12, help_text='Trailing weeks of loss history the demand rate is computed over.')),
                ('horizon_days', models.PositiveIntegerField(db_default=28, default=28, help_text='Days ahead that dated demand (fleet ops, manual lines) is planned for.')),
                ('service_level', models.CharField(choices=[('0.50', '50%'), ('0.80', '80%'), ('0.90', '90%'), ('0.95', '95%'), ('0.99', '99%')], db_default='0.90', default='0.90', help_text='Confidence level for demand bands and reorder suggestions.', max_length=4)),
                ('op_attrition_pct', models.PositiveIntegerField(db_default=10, default=10, help_text="Assumed percentage of a fleet op's pilots whose ship needs replacing.")),
                ('slow_mover_days', models.PositiveIntegerField(db_default=60, default=60, help_text='Days without demand or outbound stock before a stocked fit is flagged slow-moving.')),
                ('include_untagged_losses', models.BooleanField(db_default=True, default=True, help_text="Allocate hull losses without a doctrine-fit tag across that hull's offered fits.")),
                ('include_recurring_ops', models.BooleanField(db_default=False, default=False, help_text='Count recurring fleet ops as future demand. Off by default: their attrition is already inside the trailing loss history.')),
                ('use_suggested_reorder_alerts', models.BooleanField(db_default=False, default=False, help_text='Raise a console alert when available stock falls below the suggested reorder point (explicit reorder points always alert).')),
            ],
            options={
                'verbose_name': 'demand planning config',
                'verbose_name_plural': 'demand planning configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('needed_by', models.DateField(blank=True, help_text='Blank = undated; planned against the end of the demand horizon.', null=True)),
                ('note', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('campaign_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_default='open', db_index=True, default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_lines', to='doctrines.doctrinefit')),
            ],
            options={
                'ordering': ['needed_by', 'pk'],
                'indexes': [models.Index(fields=['fit', 'status'], name='store_deman_fit_id_402370_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('rate_week_mean', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rate_week_hi', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sigma_week', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sources', models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='doctrines.doctrinefit')),
            ],
            options={
                'ordering': ['week_start'],
                'constraints': [models.UniqueConstraint(fields=('fit', 'week_start'), name='uniq_demand_snapshot_week')],
            },
        ),
    ]
