# Generated by Django 5.2.16 on 2026-07-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('store', '0004_demandconfig_demandline_demandsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitsupplyneed',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='fitstockentry',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Stock received'), ('po_receipt', 'Received from supplier'), ('adjustment', 'Manual adjustment'), ('consumed', 'Delivered to buyer'), ('reconciliation', 'Reconciliation'), ('revalidation', 'Fit revision revalidated')], max_length=14),
        ),
    ]
