# Generated by Django 5.2.16 on 2026-07-17 17:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_fitsupplyneed_purchase_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('drift_threshold_pct', models.DecimalField(db_default=Decimal('0.100'), decimal_places=3, default=Decimal('0.100'), help_text='Flag an open order when its re-estimated basis moves this fraction or more from the frozen value (0.100 = 10 percent).', max_digits=5)),
                ('drift_min_isk', models.DecimalField(db_default=Decimal('5000000'), decimal_places=2, default=Decimal('5000000'), help_text='Also require this many ISK of absolute drift before flagging — stops penny noise on small hulls.', max_digits=20)),
                ('drift_check_enabled', models.BooleanField(db_default=False, default=False, help_text='Run the nightly quote-drift check. Off: no drift is ever flagged.')),
                ('settlement_reconcile_enabled', models.BooleanField(db_default=False, default=False, help_text='Match delivered orders to corp-wallet revenue by payment token. Off: margin shows quoted revenue only.')),
                ('margin_window_days', models.PositiveIntegerField(db_default=30, default=30, help_text='Trailing days of delivered orders the margin summary covers.')),
                ('margin_alert_floor_pct', models.DecimalField(db_default=Decimal('0.050'), decimal_places=3, default=Decimal('0.050'), help_text="Alert leadership when the window's evidenced-margin ratio drops below this fraction (0.050 = 5 percent).", max_digits=5)),
            ],
            options={
                'verbose_name': 'margin config',
                'verbose_name_plural': 'margin configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='storeorder',
            name='fulfilment_method',
            field=models.CharField(blank=True, choices=[('stock', 'Use stocked ships'), ('build', 'Build locally'), ('import', 'Import from Jita'), ('supplier', 'Buy from an approved supplier')], db_default='', default='', max_length=8),
        ),
        migrations.CreateModel(
            name='OrderBasisDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, choices=[('jita', 'Jita sell price'), ('build', 'Estimated build cost')], default='', max_length=5)),
                ('basis_source', models.CharField(blank=True, default='', max_length=8)),
                ('frozen_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('drift_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('flagged', models.BooleanField(db_default=False, default=False)),
                ('acknowledged_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basis_drift', to='store.storeorder')),
            ],
            options={
                'ordering': ['-flagged', '-checked_at'],
                'indexes': [models.Index(fields=['flagged', '-checked_at'], name='store_order_flagged_64b022_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('journal', 'Wallet journal'), ('contract', 'Corp contract')], max_length=8)),
                ('journal_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('contract_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=0, max_digits=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('matched_by', models.CharField(choices=[('token', 'Payment token'), ('officer', 'Officer-recorded')], max_length=8)),
                ('note', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='store.storeorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_id', 'occurred_at', 'id'],
                'indexes': [models.Index(fields=['order', 'occurred_at'], name='store_order_order_i_de9e21_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('journal_entry_id__isnull', False)), fields=('journal_entry_id',), name='uniq_settlement_journal_entry'), models.UniqueConstraint(condition=models.Q(('contract_id__isnull', False)), fields=('contract_id',), name='uniq_settlement_contract')],
            },
        ),
    ]
