# Generated by Django 5.2.15 on 2026-07-03 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0002_evecharacter_owner_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiMaterial',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('tier', models.CharField(choices=[('P0', 'P0 · Raw resource'), ('P1', 'P1 · Processed material'), ('P2', 'P2 · Refined commodity'), ('P3', 'P3 · Specialised commodity'), ('P4', 'P4 · Advanced commodity')], db_index=True, max_length=2)),
                ('volume', models.FloatField(default=0.0, help_text='m³ per unit — used for hauling sizing.')),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PiPlanetType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('best_for', models.CharField(blank=True, max_length=200)),
                ('blurb', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanetaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True, help_text='Master switch shown to pilots. Turning this off hides the planner even if the feature flag is on.')),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('default_market_region_id', models.IntegerField(default=10000002)),
                ('default_market_region_name', models.CharField(default='The Forge (Jita)', max_length=80)),
                ('default_customs_export_tax', models.DecimalField(decimal_places=2, default=5.0, help_text='Customs office (POCO) export tax %, applied to item base value.', max_digits=5)),
                ('default_customs_import_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('default_sales_tax', models.DecimalField(decimal_places=2, default=4.5, help_text='Market sales tax %.', max_digits=5)),
                ('default_broker_fee', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('default_hauling_cost_per_m3', models.DecimalField(decimal_places=2, default=0.0, help_text='ISK per m³ to move goods to the hub (0 = you self-haul).', max_digits=12)),
                ('corp_buyback_rate', models.DecimalField(decimal_places=2, default=90.0, help_text='% of Jita sell the corp buyback pays.', max_digits=5)),
                ('default_extraction_rate_per_hour', models.PositiveIntegerField(default=2000, help_text='Planning assumption: P0 units/hour on one extraction planet.')),
                ('recommended_products', models.JSONField(blank=True, default=list, help_text='Type ids the corp wants pilots to produce.')),
                ('priority_note', models.TextField(blank=True)),
                ('recommended_regions', models.CharField(blank=True, max_length=200)),
                ('default_visibility', models.CharField(default='private', max_length=12)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(blank=True, null=True)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('beginner', 'Beginner passive income'), ('low_effort', 'Low-effort extraction'), ('p0_p1', 'P0 → P1 processing'), ('p0_p2', 'P0 → P2 refined'), ('factory', 'Factory planet'), ('p3_p4', 'P3 / P4 advanced production'), ('corp_supply', 'Corporation supply chain'), ('max_profit', 'Maximum ISK profit')], default='beginner', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to build'), ('active', 'Active'), ('needs_review', 'Needs review'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private (only me)'), ('leadership', 'Shared with leadership'), ('corp', 'Shared with corporation')], default='private', max_length=12)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=120)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('planet_count', models.PositiveSmallIntegerField(default=1)),
                ('market_region_id', models.IntegerField(default=10000002)),
                ('market_region_name', models.CharField(default='The Forge (Jita)', max_length=80)),
                ('customs_export_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('customs_import_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=4.5, max_digits=5)),
                ('broker_fee', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('hauling_cost_per_m3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('corp_buyback_rate', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('extraction_rate_per_hour', models.PositiveIntegerField(default=2000)),
                ('effort', models.CharField(choices=[('low', 'Low effort'), ('daily', 'Daily reset'), ('few_days', 'Every 2–3 days'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('risk', models.CharField(choices=[('highsec', 'High-sec convenience'), ('low_null', 'Low-sec / null-sec yield'), ('wormhole', 'Wormhole production'), ('corp_space', 'Corp-controlled space')], default='highsec', max_length=12)),
                ('export_strategy', models.CharField(choices=[('sell_local', 'Sell locally'), ('haul_hub', 'Haul to market hub'), ('corp_buyback', 'Use corp buyback'), ('feed_chain', 'Feed another chain')], default='haul_hub', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('last_priced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PiPlanetResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_sources', to='planetary.pimaterial')),
                ('planet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='planetary.piplanettype')),
            ],
            options={
                'ordering': ['planet_type', 'material'],
            },
        ),
        migrations.CreateModel(
            name='PiPlanPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('extract', 'Extraction'), ('factory', 'Factory'), ('storage', 'Storage / staging')], default='extract', max_length=10)),
                ('output_override', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='planetary.piplan')),
                ('planet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planetary.piplanettype')),
                ('primary_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planetary.pimaterial')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PiSchematic',
            fields=[
                ('schematic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('output_quantity', models.IntegerField(default=1)),
                ('cycle_seconds', models.IntegerField(default=3600)),
                ('tier', models.CharField(choices=[('P0', 'P0 · Raw resource'), ('P1', 'P1 · Processed material'), ('P2', 'P2 · Refined commodity'), ('P3', 'P3 · Specialised commodity'), ('P4', 'P4 · Advanced commodity')], db_index=True, max_length=2)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_by', to='planetary.pimaterial')),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PiSchematicInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds_into', to='planetary.pimaterial')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planetary.pischematic')),
            ],
        ),
        migrations.CreateModel(
            name='PiColony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('planet_id', models.BigIntegerField()),
                ('planet_type_id', models.IntegerField(blank=True, null=True)),
                ('planet_type_name', models.CharField(blank=True, max_length=40)),
                ('solar_system_id', models.IntegerField(blank=True, null=True)),
                ('solar_system_name', models.CharField(blank=True, max_length=120)),
                ('upgrade_level', models.PositiveSmallIntegerField(default=0)),
                ('num_pins', models.PositiveSmallIntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_colonies', to='sso.evecharacter')),
            ],
            options={
                'ordering': ['character', 'planet_id'],
                'unique_together': {('character', 'planet_id')},
            },
        ),
        migrations.AddIndex(
            model_name='piplan',
            index=models.Index(fields=['owner', 'status'], name='planetary_p_owner_i_097732_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='piplanetresource',
            unique_together={('planet_type', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='pischematicinput',
            unique_together={('schematic', 'material')},
        ),
    ]
