# Generated by Django 5.2.16 on 2026-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetary', '0002_picolony_alerted_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetaryconfig',
            name='corp_buyback_rate',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Percent of Jita sell the corp buyback pays.', max_digits=5),
        ),
    ]
