# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(default=1)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contract_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('issued', 'Issued'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='expected', max_length=10)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='industry.industryproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HaulingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, default=list)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('volume_m3', models.FloatField(default=0.0)),
                ('route_jumps', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('in_progress', 'In progress'), ('done', 'Done')], default='open', max_length=12)),
                ('claimed_by_character_id', models.BigIntegerField(blank=True, null=True)),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haul_dests', to='market.marketlocation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haul_tasks', to='industry.industryproject')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haul_sources', to='market.marketlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('corp', 'Corp'), ('personal', 'Personal')], default='corp', max_length=10)),
                ('owner_character_id', models.BigIntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockpiles', to='market.marketlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockpileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField()),
                ('quantity_current', models.BigIntegerField(default=0)),
                ('quantity_target', models.BigIntegerField(blank=True, null=True)),
                ('provenance', models.CharField(choices=[('esi', 'ESI'), ('manual', 'Manual'), ('estimated', 'Estimated')], default='manual', max_length=10)),
                ('stockpile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stockpile.stockpile')),
            ],
            options={
                'unique_together': {('stockpile', 'type_id')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.BigIntegerField(default=0)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('released', 'Released')], default='active', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='industry.industryproject')),
                ('stockpile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stockpile.stockpileitem')),
            ],
            options={
                'ordering': ['reserved_at'],
            },
        ),
    ]
