# Generated by Django 5.2.15 on 2026-06-22 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('station', 'Station'), ('solar_system', 'Solar system'), ('structure', 'Structure'), ('other', 'Other')], default='other', max_length=16)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('owner_type', models.CharField(choices=[('corporation', 'Corporation'), ('character', 'Character')], db_index=True, max_length=12)),
                ('owner_id', models.BigIntegerField(db_index=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='stockpile.assetlocation')),
            ],
            options={
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='stockpile_a_owner_t_644cbb_idx')],
                'unique_together': {('owner_type', 'owner_id', 'location', 'type_id')},
            },
        ),
    ]
