# Generated by Django 5.2.16 on 2026-07-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_delete_blueprint'),
        ('stockpile', '0003_delete_contracttrackingitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockpileitem',
            index=models.Index(fields=['type_id'], name='stockpile_s_type_id_4a3198_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'stockpile_item'], name='stockpile_s_status_8859be_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['project', 'status'], name='stockpile_s_project_0faf1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockpileitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_current__gte', 0)), name='stockpileitem_current_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 1)), name='stockreservation_qty_gte_1'),
        ),
    ]
