# Generated by Django 5.2.15 on 2026-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=12)),
                ('is_public_preview', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Corp-need weight for skill planning.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctrineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'doctrine categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DoctrineFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('ship_type_id', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=40)),
                ('eft_text', models.TextField(blank=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('is_cheap_alt', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctrineRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('implant', 'Implant'), ('booster', 'Booster'), ('rig', 'Rig'), ('ammo', 'Ammo'), ('note', 'Note')], max_length=12)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type_id', models.IntegerField()),
                ('min_level', models.PositiveSmallIntegerField(default=1)),
                ('optimal_level', models.PositiveSmallIntegerField(default=1)),
                ('derived_from', models.CharField(choices=[('auto_dogma', 'Auto (dogma)'), ('manual', 'Manual override')], default='auto_dogma', max_length=12)),
            ],
        ),
    ]
