# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctrine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctrines', to='doctrines.doctrinecategory'),
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='doctrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='doctrines.doctrine'),
        ),
        migrations.AddField(
            model_name='doctrinerequirement',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='doctrines.doctrinefit'),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='doctrines.doctrinefit'),
        ),
        migrations.AlterUniqueTogether(
            name='skillrequirement',
            unique_together={('fit', 'skill_type_id')},
        ),
    ]
