# Generated by Django 5.2.15 on 2026-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0004_doctrineimportbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_fittings_per_import', models.PositiveIntegerField(default=1000, help_text='How many fittings one XML upload may contain (1–1000). 1000 is the hard safety maximum; set it there to effectively remove the limit.')),
            ],
            options={
                'verbose_name': 'doctrine import config',
                'verbose_name_plural': 'doctrine import config',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
