# Generated by Django 5.2.15 on 2026-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0005_doctrineimportconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineDisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('per_page', models.PositiveIntegerField(default=24, help_text='Doctrines/ships shown per page on the Doctrines and Shipyard pages (6–200).')),
            ],
            options={
                'verbose_name': 'doctrine display config',
                'verbose_name_plural': 'doctrine display config',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
