# Generated by Django 5.2.16 on 2026-07-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0007_doctrinefit_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctrine',
            name='is_public_preview',
        ),
        migrations.RemoveField(
            model_name='doctrinefit',
            name='estimated_cost',
        ),
    ]
