# Generated by Django 5.2.15 on 2026-06-24 22:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningObserver',
            fields=[
                ('observer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('observer_type', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiningTaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MiningPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pool_isk', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('method', models.CharField(choices=[('by_value', 'By ISK value mined'), ('by_volume', 'By quantity mined'), ('equal', 'Split equally')], default='by_value', max_length=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalised')], default='draft', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiningPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('value_mined', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('share_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('paid', models.BooleanField(default=False)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mining.miningpayout')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-value_mined'],
            },
        ),
        migrations.CreateModel(
            name='MiningLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('type_id', models.IntegerField()),
                ('quantity', models.BigIntegerField(default=0)),
                ('day', models.DateField(db_index=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mining.miningobserver')),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('observer', 'character_id', 'type_id', 'day')},
            },
        ),
    ]
