# Generated by Django 5.2.16 on 2026-07-10 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_seed_campaign_lead_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['owner', 'status'], name='campaigns_o_owner_i_dcb59b_idx'),
        ),
    ]
