# Generated by Django 5.2.16 on 2026-07-10 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_objective_campaigns_o_owner_i_dcb59b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['metric_source', 'measured_at'], name='campaigns_o_metric__44712f_idx'),
        ),
    ]
