# Generated by Django 5.2.16 on 2026-07-14 09:00
#
# Additive, metadata-only: one blank-by-default CharField per row type that gets blueprint prose
# copied into it, carrying the built-in item it came from (the i18n translate-until-edited seam).
# No data migration — existing rows keep the empty string and simply render verbatim, exactly as
# they do today.
#
# ``db_default=""`` is load-bearing: without it Django emits ``ADD COLUMN … DEFAULT '' NOT NULL``
# followed by ``ALTER COLUMN … DROP DEFAULT``, leaving a NOT NULL column with no database default —
# so any INSERT from older code (a rollback, a mid-deploy web pod) that does not name the column
# fails. With ``db_default`` the default survives in the database and the column is safe both ways.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_seed_builtin_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
        migrations.AddField(
            model_name='milestone',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
        migrations.AddField(
            model_name='objective',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
        migrations.AddField(
            model_name='risk',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
        migrations.AddField(
            model_name='workstream',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
    ]
