# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_corp_member', models.BooleanField(default=False)),
                ('security_status', models.FloatField(blank=True, null=True)),
                ('affiliation_updated_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='corporation.evecorporation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token')),
                ('_access_token', models.TextField(blank=True, db_column='access_token')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_ok_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_fail_count', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='sso.evecharacter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EveScopeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=128)),
                ('feature_key', models.CharField(blank=True, max_length=64)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_grants', to='sso.evecharacter')),
            ],
            options={
                'unique_together': {('character', 'scope')},
            },
        ),
    ]
