# Generated by Django 5.2.15 on 2026-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='owner_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
