# Generated by Django 5.2.16 on 2026-07-17 07:45

import apps.procurement.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0008_remove_doctrine_is_public_preview_and_more'),
        ('market', '0004_marketwatch'),
        ('stockpile', '0005_release_stranded_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('agreement_approval_threshold_isk', models.DecimalField(db_default=Decimal('5000000000'), decimal_places=2, default=Decimal('5000000000'), help_text="Estimated cycle value at or above which a supply agreement needs a second Director's approval.", max_digits=20)),
                ('po_director_threshold_isk', models.DecimalField(db_default=Decimal('2000000000'), decimal_places=2, default=Decimal('2000000000'), help_text='Total value at or above which a standalone purchase order (one not covered by an active agreement) needs Director approval.', max_digits=20)),
                ('overdue_grace_days', models.PositiveSmallIntegerField(db_default=2, default=2, help_text='Days past the promised date before a purchase order is flagged overdue.')),
                ('reliability_window_weeks', models.PositiveSmallIntegerField(db_default=8, default=8, help_text='Complete weeks of closed purchase orders the reliability rollup looks back over.')),
                ('match_enabled', models.BooleanField(db_default=False, default=False, help_text='Arm the contract matcher (runs after the corp-contracts sync). Off: officers confirm contract matches by hand.')),
                ('reconcile_enabled', models.BooleanField(db_default=False, default=False, help_text='Arm the wallet-journal payment reconcile. Off: officers confirm payments by hand.')),
                ('overdue_sweep_enabled', models.BooleanField(db_default=False, default=False, help_text='Arm the daily overdue sweep (also expires lapsed agreements).')),
                ('auto_receipt_enabled', models.BooleanField(db_default=False, default=False, help_text='Let a finished matched contract post its landed quantities as receipts automatically. Off: officers post receipts by hand.')),
                ('reliability_rollup_enabled', models.BooleanField(db_default=False, default=False, help_text='Arm the nightly supplier-reliability rollup.')),
                ('reconcile_ref_types', models.JSONField(db_default=models.Value(['contract_price_payment_corp'], models.JSONField()), default=apps.procurement.models._default_reconcile_ref_types, help_text='Wallet-journal ref_types the payment reconcile treats as supplier payments. Enumerate from the real corp journal before arming.')),
            ],
            options={
                'verbose_name': 'procurement config',
                'verbose_name_plural': 'procurement configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_mode', models.CharField(choices=[('supplier_delivers', 'Supplier delivers'), ('hub_pickup', 'Hub pickup (corp hauls)')], db_default='supplier_delivers', default='supplier_delivers', max_length=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('contract_expected', 'Contract expected'), ('contract_available', 'Contract available'), ('accepted', 'Accepted'), ('partial', 'Partially delivered'), ('delivered', 'Delivered'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('overdue', 'Overdue')], db_default='draft', db_index=True, default='draft', max_length=20)),
                ('promised_by', models.DateTimeField(blank=True, null=True)),
                ('overdue_since', models.DateTimeField(blank=True, null=True)),
                ('expected_total_isk', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('note_key', models.CharField(blank=True, db_default='', default='', max_length=60)),
                ('note_params', models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict)),
                ('system_note', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('contract_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('contract_status', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contract_date_issued', models.DateTimeField(blank=True, null=True)),
                ('contract_date_completed', models.DateTimeField(blank=True, null=True)),
                ('contract_matched_at', models.DateTimeField(blank=True, null=True)),
                ('contract_items', models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list)),
                ('paid_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity_ordered', models.BigIntegerField(db_default=0, default=0)),
                ('quantity_received', models.BigIntegerField(db_default=0, default=0)),
                ('unit_price_isk', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('unit_jita_at_order', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('doctrine_fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='doctrines.doctrinefit')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PoReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(db_default=0, default=0)),
                ('kind', models.CharField(choices=[('contract_auto', 'Auto (contract landed)'), ('manual', 'Manual (officer attested)')], db_default='manual', default='manual', max_length=14)),
                ('contract_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_jita_at_receipt', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('note', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stockpile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.stockpileitem')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorder')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorderline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pilot', 'Pilot'), ('corp', 'Corporation'), ('hub', 'Market hub')], max_length=5)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('contact', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('activities', models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list)),
                ('lead_time_days', models.PositiveSmallIntegerField(db_default=5, default=5)),
                ('weekly_capacity_units', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('suspended', 'Suspended'), ('retired', 'Retired')], db_default='active', db_index=True, default='active', max_length=10)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('on_time_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fill_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_variance_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reliability_sample', models.PositiveIntegerField(db_default=0, default=0)),
                ('reliability_computed_at', models.DateTimeField(blank=True, null=True)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation')),
                ('locations', models.ManyToManyField(blank=True, related_name='+', to='market.marketlocation')),
            ],
            options={
                'ordering': ['display_name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('moq', models.PositiveIntegerField(db_default=1, default=1)),
                ('price_model', models.CharField(choices=[('fixed', 'Fixed price'), ('jita_indexed', 'Jita-indexed + premium')], db_default='jita_indexed', default='jita_indexed', max_length=12)),
                ('fixed_price_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('premium_pct', models.DecimalField(db_default=Decimal('0'), decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_capacity_units', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(db_default=True, default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplier')),
            ],
            options={
                'ordering': ['supplier', 'type_id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_default='draft', db_index=True, default='draft', max_length=16)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('cadence', models.CharField(choices=[('one_off', 'One-off'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_default='one_off', default='one_off', max_length=8)),
                ('payment_terms', models.CharField(choices=[('prepaid', 'Prepaid'), ('on_delivery', 'On delivery'), ('net_7', 'Net 7 days'), ('net_30', 'Net 30 days')], db_default='on_delivery', default='on_delivery', max_length=12)),
                ('collateral_isk', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('estimated_cycle_value_isk', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='procurement.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.supplyagreement'),
        ),
        migrations.CreateModel(
            name='AgreementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_value_isk', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('reason', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_default='pending', db_index=True, default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_approvals_made', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.supplyagreement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyAgreementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity_per_cycle', models.BigIntegerField(db_default=0, default=0)),
                ('min_qty', models.BigIntegerField(blank=True, null=True)),
                ('max_qty', models.BigIntegerField(blank=True, null=True)),
                ('price_model', models.CharField(choices=[('fixed', 'Fixed price'), ('jita_indexed', 'Jita-indexed + premium')], db_default='jita_indexed', default='jita_indexed', max_length=12)),
                ('fixed_price_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('premium_pct', models.DecimalField(db_default=Decimal('0'), decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.supplyagreement')),
            ],
            options={
                'ordering': ['agreement', 'type_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gte', 1)), name='poline_ordered_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='poline_received_gte_0'),
        ),
        migrations.AddIndex(
            model_name='poreceipt',
            index=models.Index(fields=['po', '-created_at'], name='procurement_po_id_7ae3b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='poreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='poreceipt_qty_gte_1'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status', 'kind'], name='procurement_status_4fddec_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_id__isnull', False), models.Q(('status', 'retired'), _negated=True)), fields=('entity_id',), name='uniq_live_supplier_entity'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('supplier', 'type_id'), name='uniq_supplieritem_type'),
        ),
        migrations.AddIndex(
            model_name='supplyagreement',
            index=models.Index(fields=['status', 'supplier'], name='procurement_status_0dc747_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'promised_by'], name='procurement_status_8b172c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='procurement_supplie_b6d45e_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_id__isnull', False)), fields=('contract_id',), name='uniq_po_contract_id'),
        ),
        migrations.AddConstraint(
            model_name='agreementapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('agreement',), name='uniq_open_agreement_approval'),
        ),
        migrations.AddConstraint(
            model_name='supplyagreementline',
            constraint=models.UniqueConstraint(fields=('agreement', 'type_id'), name='uniq_agreementline_type'),
        ),
    ]
