# Generated by Django 5.2.15 on 2026-06-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('linked', 'ESI linked'), ('joined', 'Joined'), ('rejected', 'Rejected')], default='prospect', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('evidence_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scopes', models.JSONField(default=list)),
                ('state', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='recruitment.candidate')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('identity', 'Identity'), ('combat', 'Combat'), ('industry', 'Industry'), ('roles', 'Roles'), ('timezone', 'Timezone'), ('risk', 'Risk')], max_length=12)),
                ('claim', models.CharField(max_length=300)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('source', models.CharField(default='public', max_length=8)),
                ('is_flag', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['theme', '-confidence'],
            },
        ),
    ]
