# Generated by Django 5.2.15 on 2026-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateevidence',
            name='claim',
            field=models.TextField(),
        ),
    ]
