# Generated by Django 5.2.16 on 2026-07-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('em', models.FloatField(default=25.0)),
                ('thermal', models.FloatField(default=25.0)),
                ('kinetic', models.FloatField(default=25.0)),
                ('explosive', models.FloatField(default=25.0)),
                ('is_corp_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tochas_damage_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('ship_type_id', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('activity', models.CharField(blank=True, max_length=48)),
                ('environment', models.CharField(blank=True, max_length=48)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('corporation', 'Corporation'), ('alliance', 'Alliance'), ('public', 'Public link'), ('doctrine', 'Doctrine-managed')], default='private', max_length=12)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('share_revoked', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('forked_from_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=24)),
                ('promoted_doctrine_fit_id', models.IntegerField(blank=True, null=True)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='fitting.fit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tochas_fits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FitRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('ship_type_id', models.IntegerField()),
                ('items', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('change_summary', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_version', models.CharField(blank=True, max_length=16)),
                ('data_version', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='fitting.fit')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='fit',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fitting.fitrevision'),
        ),
        migrations.AddConstraint(
            model_name='fitrevision',
            constraint=models.UniqueConstraint(fields=('fit', 'revision_number'), name='uniq_fit_revision'),
        ),
        migrations.AddIndex(
            model_name='fit',
            index=models.Index(fields=['owner', 'is_archived'], name='fitting_fit_owner_i_531eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='fit',
            index=models.Index(fields=['visibility'], name='fitting_fit_visibil_b1236c_idx'),
        ),
    ]
