# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('station', 'Station'), ('structure', 'Structure'), ('system', 'System'), ('region', 'Region')], max_length=12)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('structure_id', models.BigIntegerField(blank=True, null=True)),
                ('is_price_reference', models.BooleanField(default=False)),
                ('is_staging', models.BooleanField(default=False)),
                ('requires_auth', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('is_buy', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_remain', models.BigIntegerField(default=0)),
                ('min_volume', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.marketlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('buy_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sell_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('weighted_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjusted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('profile', models.CharField(choices=[('jita_sell', 'Jita sell'), ('jita_buy', 'Jita buy'), ('adjusted', 'CCP adjusted')], default='jita_sell', max_length=12)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.marketlocation')),
            ],
            options={
                'unique_together': {('type_id', 'location', 'profile')},
            },
        ),
    ]
