# Generated by Django 5.2.15 on 2026-06-22 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('region_id', models.IntegerField(db_index=True)),
                ('date', models.DateField()),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('highest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('lowest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('order_count', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('type_id', 'region_id', 'date')},
            },
        ),
    ]
