# Generated by Django 5.2.15 on 2026-06-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slices', models.JSONField(blank=True, default=dict)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('config_version', models.IntegerField(default=0)),
                ('schema_version', models.IntegerField(default=1)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('outcome', 'Outcome measurement')], default='manual', max_length=16)),
                ('build_ms', models.IntegerField(default=0)),
                ('built_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(default='posture', max_length=64)),
                ('classification', models.CharField(choices=[('corp_internal', 'Corporation Internal'), ('high_command', 'High Command'), ('director_eyes_only', 'Director — Eyes Only'), ('alliance_command', 'Alliance Command')], default='high_command', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building_snapshot', 'Building snapshot'), ('computing_constraints', 'Computing constraints'), ('calling_llm', 'Calling LLM'), ('validating', 'Validating'), ('ready', 'Ready'), ('ready_degraded', 'Ready (degraded — no narrative)'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('outcome', 'Outcome measurement')], default='manual', max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.IntegerField(default=0)),
                ('config_version', models.IntegerField(default=0)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('repair_attempts_used', models.IntegerField(default=0)),
                ('grounding_violations_dropped', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_reports', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='command_intel.intelligencesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=160)),
                ('objective', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('expected_impact', models.JSONField(blank=True, default=dict)),
                ('readiness_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('priority', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('confidence_label', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('owner_tag', models.CharField(blank=True, max_length=48)),
                ('risk_if_ignored', models.TextField(blank=True)),
                ('severity_if_ignored', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('high', 'High'), ('critical', 'Critical')], default='watch', max_length=12)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], default='proposed', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_coa_decisions', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='command_intel.courseofaction')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_coas', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_of_action', to='command_intel.intelligencereport')),
                ('baseline_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_for_coas', to='command_intel.intelligencesnapshot')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=64)),
                ('predicted_delta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measured_delta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('error', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='command_intel.courseofaction')),
                ('baseline_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_baseline_for', to='command_intel.intelligencesnapshot')),
                ('outcome_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_result_for', to='command_intel.intelligencesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=24)),
                ('label', models.CharField(max_length=160)),
                ('binding_metric', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('limiting_factor', models.CharField(blank=True, max_length=80)),
                ('headroom', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=12)),
                ('status', models.CharField(choices=[('computed', 'Computed'), ('unknown', 'Unknown (insufficient data)'), ('unavailable', 'Unavailable')], default='computed', max_length=12)),
                ('affected_capabilities', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('detail', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='command_intel.intelligencesnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='courseofaction',
            name='constraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_of_action', to='command_intel.operationalconstraint'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['-created_at'], name='command_int_created_8344c6_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['-created_at'], name='command_int_created_039114_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['classification', '-created_at'], name='command_int_classif_2442bb_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['status'], name='command_int_status_f750f6_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalconstraint',
            index=models.Index(fields=['snapshot', '-severity'], name='command_int_snapsho_94a523_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalconstraint',
            index=models.Index(fields=['key', 'created_at'], name='command_int_key_20ef26_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalconstraint',
            constraint=models.UniqueConstraint(fields=('snapshot', 'key'), name='uniq_ci_constraint_key'),
        ),
        migrations.AddIndex(
            model_name='courseofaction',
            index=models.Index(fields=['state', '-priority'], name='command_int_state_f011b9_idx'),
        ),
        migrations.AddIndex(
            model_name='courseofaction',
            index=models.Index(fields=['slug'], name='command_int_slug_211c32_idx'),
        ),
    ]
