# Generated by Django 5.2.15 on 2026-06-30 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_intel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.TextField()),
                ('target_metric', models.CharField(max_length=80)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=12)),
                ('success_probability', models.FloatField(default=0.0)),
                ('expected_trajectory', models.JSONField(blank=True, default=list)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_from_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='command_intel.intelligencereport')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courseofaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_coas', to='command_intel.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('owner_tag', models.CharField(blank=True, max_length=48)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='command_intel.campaign')),
                ('coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='command_intel.courseofaction')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='command_intel.campaignmilestone')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campaign', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-created_at'], name='command_int_status_9d3b54_idx'),
        ),
    ]
