# Generated by Django 5.2.15 on 2026-06-30 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_intel', '0002_campaign_courseofaction_campaign_campaignmilestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=160)),
                ('constraint_key', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('skill', 'Training'), ('ship', 'Ship'), ('logistics', 'Logistics'), ('role', 'Role')], default='skill', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('leverage', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('posture_lift', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-leverage', '-points', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='delivered_channels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='intelligencereport',
            index=models.Index(fields=['trigger', '-created_at'], name='command_int_trigger_e42b3e_idx'),
        ),
        migrations.AddField(
            model_name='pilotdirective',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_intel_directives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pilotdirective',
            index=models.Index(fields=['user', 'state'], name='command_int_user_id_852281_idx'),
        ),
        migrations.AddConstraint(
            model_name='pilotdirective',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='uniq_ci_directive_user_slug'),
        ),
    ]
