# Generated by Django 5.2.15 on 2026-07-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_intel', '0003_pilot_directive_and_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelligencereport',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('outcome', 'Outcome measurement'), ('autonomous', 'Autonomous proposal')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='intelligencesnapshot',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('outcome', 'Outcome measurement'), ('autonomous', 'Autonomous proposal')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answering', 'Answering'), ('ready', 'Ready'), ('ready_degraded', 'Ready (degraded — retrieval only)'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('clearance', models.CharField(blank=True, max_length=24)),
                ('grounded', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_intel_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='command_int_user_id_a964d7_idx'), models.Index(fields=['status'], name='command_int_status_754750_idx')],
            },
        ),
    ]
