# Generated by Django 5.2.15 on 2026-07-01 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_intel', '0004_conversation_and_autonomous_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle_report_id', models.IntegerField(db_index=True)),
                ('classification', models.CharField(choices=[('corp_internal', 'Corporation Internal'), ('high_command', 'High Command'), ('director_eyes_only', 'Director — Eyes Only'), ('alliance_command', 'Alliance Command')], default='high_command', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building_facts', 'Building facts'), ('calling_llm', 'Calling LLM'), ('ready', 'Ready'), ('ready_degraded', 'Ready (degraded — facts only)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('grounding_violations_dropped', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_intel_battle_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['battle_report_id', '-created_at'], name='command_int_battle__fa742f_idx'), models.Index(fields=['status'], name='command_int_status_51bf18_idx')],
            },
        ),
    ]
