# Generated by Django 5.2.15 on 2026-06-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockpile', '0002_assetlocation_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('corporation', 'Corporation'), ('character', 'Character')], default='corporation', max_length=12)),
                ('owner_id', models.BigIntegerField(default=0)),
                ('type_id', models.IntegerField(db_index=True, help_text='Blueprint type id.')),
                ('product_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('me', models.PositiveSmallIntegerField(default=0)),
                ('te', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type_id', models.IntegerField(db_index=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('built', 'Built'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deliver_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.stockpile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='erp.buildjob')),
                ('stockpile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.stockpile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
