# Generated by Django 5.2.15 on 2026-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_buildjob_blocked_reason_alter_buildjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterIndustryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('job_id', models.BigIntegerField(unique=True)),
                ('activity_id', models.PositiveSmallIntegerField(default=1)),
                ('blueprint_type_id', models.IntegerField(db_index=True)),
                ('product_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('runs', models.IntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='active', max_length=12)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('facility_id', models.BigIntegerField(blank=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
