# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sso.evecharacter'),
        ),
        migrations.AddField(
            model_name='characterskillsnapshot',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='sso.evecharacter'),
        ),
        migrations.AddField(
            model_name='skillqueuesnapshot',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillqueue_snapshots', to='sso.evecharacter'),
        ),
        migrations.AddIndex(
            model_name='characterskillsnapshot',
            index=models.Index(fields=['character', 'is_latest'], name='characters__charact_2463b0_idx'),
        ),
    ]
