# Generated by Django 5.2.16 on 2026-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characterfittedship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterattributes',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='characterfittedship',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='characterskillsnapshot',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='skillqueuesnapshot',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
    ]
