# Generated by Django 5.2.15 on 2026-06-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_recognition', models.BooleanField(default=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('primary_character_id', models.BigIntegerField(blank=True, null=True)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('build', 'Built'), ('haul', 'Hauled'), ('seed', 'Seeded market'), ('train', 'Trained skill'), ('task', 'Completed task'), ('srp', 'Ship replacement'), ('mining', 'Mined'), ('delivery', 'Delivered')], db_index=True, max_length=12)),
                ('magnitude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit', models.CharField(default='count', max_length=16)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ref_type', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('gap_ref', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='pilots_cont_user_id_c45759_idx'), models.Index(fields=['kind', 'ref_type', 'ref_id'], name='pilots_cont_kind_beac41_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ref_id__gt', '')), fields=('kind', 'ref_type', 'ref_id'), name='uniq_contribution_per_source_action')],
            },
        ),
    ]
