# Generated by Django 5.2.15 on 2026-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionevent',
            name='kind',
            field=models.CharField(choices=[('build', 'Built'), ('haul', 'Hauled'), ('seed', 'Seeded market'), ('train', 'Trained skill'), ('task', 'Completed task'), ('srp', 'Ship replacement'), ('mining', 'Mined'), ('delivery', 'Delivered'), ('fleet', 'Flew in fleet')], db_index=True, max_length=12),
        ),
    ]
