# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdeCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SdeRegion',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SdeGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sde.sdecategory')),
            ],
        ),
        migrations.CreateModel(
            name='SdeSolarSystem',
            fields=[
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('security', models.FloatField(default=0.0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='sde.sderegion')),
            ],
        ),
        migrations.CreateModel(
            name='SdeType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('volume', models.FloatField(default=0.0)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('published', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.sdegroup')),
            ],
        ),
        migrations.CreateModel(
            name='SdeBlueprintMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_type_id', models.IntegerField(db_index=True)),
                ('quantity', models.BigIntegerField()),
                ('activity', models.CharField(default='manufacturing', max_length=32)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sde.sdetype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['product_type', 'activity'], name='sde_sdeblue_product_188bd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SdeTypeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sde.sdetype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='sde.sdetype')),
            ],
            options={
                'unique_together': {('type', 'skill_type')},
            },
        ),
    ]
