# Generated by Django 5.2.15 on 2026-06-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdeblueprintmaterial',
            name='output_quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
