# Generated by Django 5.2.15 on 2026-06-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0002_sdeblueprintmaterial_output_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdetype',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
