# Generated by Django 5.2.15 on 2026-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_sdetype_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeStation',
            fields=[
                ('station_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('system_id', models.IntegerField(db_index=True)),
                ('system_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
