# Generated by Django 5.2.15 on 2026-06-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0005_solarsystem_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sderegion',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='SdeConstellation',
            fields=[
                ('constellation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constellations', to='sde.sderegion')),
            ],
        ),
        migrations.AddField(
            model_name='sdesolarsystem',
            name='constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='sde.sdeconstellation'),
        ),
        migrations.CreateModel(
            name='SdeSystemJump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_system_id', models.IntegerField(db_index=True)),
                ('to_system_id', models.IntegerField(db_index=True)),
            ],
            options={
                'unique_together': {('from_system_id', 'to_system_id')},
            },
        ),
    ]
