# Generated by Django 5.2.15 on 2026-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0006_alter_sderegion_options_sdeconstellation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeCelestial',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('system_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('planet', 'Planet'), ('moon', 'Moon'), ('belt', 'Asteroid belt')], max_length=8)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('parent_planet_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('celestial_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['celestial_index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sdetype',
            name='packaged_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
