# Generated by Django 5.2.15 on 2026-07-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0008_sdeblueprintskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeDecryptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('probability_multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
                ('run_modifier', models.SmallIntegerField(default=0)),
                ('me_modifier', models.SmallIntegerField(default=0)),
                ('te_modifier', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SdeBlueprintActivityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_type_id', models.IntegerField(db_index=True)),
                ('activity', models.CharField(default='manufacturing', max_length=16)),
                ('time', models.IntegerField(default=0)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['product_type', 'activity'], name='sde_sdeblue_product_d0923b_idx')],
                'constraints': [models.UniqueConstraint(fields=('blueprint_type_id', 'activity'), name='uniq_bp_activity_time')],
            },
        ),
        migrations.CreateModel(
            name='SdeInventionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_blueprint_type_id', models.IntegerField(db_index=True)),
                ('t2_blueprint_type_id', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=1)),
                ('probability', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['product_type'], name='sde_sdeinve_product_22f297_idx')],
            },
        ),
    ]
