# Generated by Django 5.2.16 on 2026-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0012_type_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetypematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
