# Generated by Django 5.2.16 on 2026-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0013_alter_sdetypematerial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdetype',
            name='hi_slots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdetype',
            name='low_slots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdetype',
            name='med_slots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdetype',
            name='rig_slots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
