# Generated by Django 5.2.16 on 2026-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0014_sdetype_hi_slots_sdetype_low_slots_sdetype_med_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeDogmaAttribute',
            fields=[
                ('attribute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('stackable', models.BooleanField(default=True)),
                ('high_is_good', models.BooleanField(blank=True, null=True)),
                ('default_value', models.FloatField(default=0.0)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SdeDogmaEffect',
            fields=[
                ('effect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('effect_category', models.IntegerField(default=0)),
                ('is_offensive', models.BooleanField(default=False)),
                ('is_assistance', models.BooleanField(default=False)),
                ('discharge_attribute_id', models.IntegerField(blank=True, null=True)),
                ('duration_attribute_id', models.IntegerField(blank=True, null=True)),
                ('range_attribute_id', models.IntegerField(blank=True, null=True)),
                ('falloff_attribute_id', models.IntegerField(blank=True, null=True)),
                ('tracking_attribute_id', models.IntegerField(blank=True, null=True)),
                ('modifier_info', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SdeShipBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('target_attribute_id', models.IntegerField()),
                ('amount', models.FloatField(default=0.0)),
                ('per_level', models.BooleanField(default=False)),
                ('skill_type_id', models.IntegerField(blank=True, null=True)),
                ('target_domain', models.CharField(default='item', max_length=8)),
                ('match_group_ids', models.JSONField(blank=True, default=list)),
                ('match_category_ids', models.JSONField(blank=True, default=list)),
                ('match_attr_present', models.IntegerField(blank=True, null=True)),
                ('penalised', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_bonuses', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['ship_type'], name='sde_sdeship_ship_ty_be6528_idx')],
                'constraints': [models.UniqueConstraint(fields=('ship_type', 'key'), name='uniq_ship_bonus_key')],
            },
        ),
        migrations.CreateModel(
            name='SdeTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField()),
                ('value', models.FloatField(default=0.0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_attributes', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute_id'], name='sde_sdetype_attribu_283f0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'attribute_id'), name='uniq_type_attribute')],
            },
        ),
        migrations.CreateModel(
            name='SdeTypeEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_effects', to='sde.sdetype')),
            ],
            options={
                'indexes': [models.Index(fields=['effect_id'], name='sde_sdetype_effect__548a21_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'effect_id'), name='uniq_type_effect')],
            },
        ),
    ]
