# Generated by Django 5.2.16 on 2026-07-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0018_sdemodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeDbuff',
            fields=[
                ('buff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aggregate_mode', models.CharField(max_length=16)),
                ('operation', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SdeDbuffModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('modified_attribute_id', models.IntegerField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('skill_type_id', models.IntegerField(blank=True, null=True)),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='sde.sdedbuff')),
            ],
            options={
                'indexes': [models.Index(fields=['buff'], name='sde_sdedbuf_buff_id_2ca8d0_idx')],
            },
        ),
    ]
