# Generated by Django 5.2.15 on 2026-07-07 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('mumble', 'Mumble')], db_index=True, max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
                ('external_handle', models.CharField(blank=True, default='', max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('_secret', models.TextField(blank=True, db_column='secret_enc', default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessSyncLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('mumble', 'Mumble')], db_index=True, max_length=16)),
                ('target_ref', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke'), ('kick', 'Kick')], max_length=8)),
                ('result', models.CharField(choices=[('applied', 'Applied'), ('dry_run', 'Dry run (preview)'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=8)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('source_ref', models.CharField(blank=True, default='', max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='comms_access.commsaccount')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('mumble', 'Mumble')], db_index=True, max_length=16)),
                ('entitlement_key', models.CharField(max_length=48)),
                ('target_type', models.CharField(default='role', max_length=24)),
                ('target_ref', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=120)),
                ('mode', models.CharField(choices=[('additive', 'Additive (grant only)'), ('authoritative', 'Authoritative (grant + remove)')], default='additive', max_length=16)),
                ('dry_run', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform', 'entitlement_key', 'target_ref'],
                'indexes': [models.Index(fields=['platform', 'enabled'], name='comms_acces_platfor_074202_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'entitlement_key', 'target_ref'), name='uniq_comms_mapping')],
            },
        ),
        migrations.AddIndex(
            model_name='commsaccount',
            index=models.Index(fields=['platform', 'verified'], name='comms_acces_platfor_e78971_idx'),
        ),
        migrations.AddIndex(
            model_name='commsaccount',
            index=models.Index(fields=['platform', 'external_id'], name='comms_acces_platfor_f8f3c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='commsaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='uniq_comms_account_user_platform'),
        ),
        migrations.AddIndex(
            model_name='accesssyncledger',
            index=models.Index(fields=['platform', 'occurred_at'], name='comms_acces_platfor_b76907_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesssyncledger',
            constraint=models.UniqueConstraint(fields=('account', 'platform', 'target_ref', 'action', 'source_ref'), name='uniq_comms_sync_event'),
        ),
    ]
