# Generated by Django 5.2.16 on 2026-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('mumble', 'Mumble')], max_length=16, unique=True)),
                ('oauth_client_id', models.CharField(blank=True, default='', max_length=128)),
                ('oauth_callback_url', models.CharField(blank=True, default='', max_length=300)),
                ('_bot_token', models.TextField(blank=True, db_column='bot_token_enc', default='')),
                ('_oauth_client_secret', models.TextField(blank=True, db_column='oauth_client_secret_enc', default='')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform',), name='uniq_comms_credential_platform')],
            },
        ),
    ]
