# Generated by Django 5.2.15 on 2026-06-23 07:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=3, default=Decimal('0.800'), max_digits=4)),
                ('min_reward', models.BigIntegerField(default=4500000)),
                ('dst_rate_per_warp', models.BigIntegerField(default=1500000)),
                ('dst_lowsec_rate_per_warp', models.BigIntegerField(default=3750000)),
                ('dst_max_m3', models.BigIntegerField(default=62500)),
                ('dst_max_collateral', models.BigIntegerField(default=10000000000)),
                ('freighter_rate_per_warp', models.BigIntegerField(default=2250000)),
                ('freighter_rate_per_warp_long', models.BigIntegerField(default=2500000)),
                ('freighter_long_threshold', models.IntegerField(default=31)),
                ('freighter_max_m3', models.BigIntegerField(default=950000)),
                ('freighter_max_collateral', models.BigIntegerField(default=5000000000)),
                ('jf_base', models.BigIntegerField(default=200000000)),
                ('jf_per_lowsec_system', models.BigIntegerField(default=100000000)),
                ('jf_max_m3', models.BigIntegerField(default=360000)),
                ('jf_max_collateral', models.BigIntegerField(default=50000000000)),
                ('rush_fee_hs', models.BigIntegerField(default=50000000)),
                ('rush_fee_jf', models.BigIntegerField(default=200000000)),
                ('contract_days', models.IntegerField(default=7)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('origin_system_id', models.IntegerField(blank=True, null=True)),
                ('origin_name', models.CharField(max_length=200)),
                ('dest_system_id', models.IntegerField(blank=True, null=True)),
                ('dest_name', models.CharField(max_length=200)),
                ('jumps', models.IntegerField(default=0)),
                ('lowsec_jumps', models.IntegerField(default=0)),
                ('sec_band', models.CharField(default='highsec', max_length=10)),
                ('ship_class', models.CharField(choices=[('dst', 'Blockade Runner / DST'), ('freighter', 'Freighter'), ('jf', 'Jump Freighter')], default='freighter', max_length=12)),
                ('volume_m3', models.FloatField(default=0.0)),
                ('collateral', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rush', models.BooleanField(default=False)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('quote', 'Quote'), ('outstanding', 'Outstanding'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='quote', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_hauler_character_id', models.BigIntegerField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_contracts_hauled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_contracts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
