# Generated by Django 5.2.15 on 2026-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='audience',
            field=models.CharField(choices=[('public', 'Public — anyone can get quotes'), ('alliance', 'Corp & alliance members only'), ('corp', 'Corp members only'), ('disabled', 'Disabled')], default='alliance', max_length=10),
        ),
    ]
