# Generated by Django 5.2.15 on 2026-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_ratecard_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriercontract',
            name='dest_location_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='dest_location_kind',
            field=models.CharField(default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='origin_location_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='origin_location_kind',
            field=models.CharField(default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='posted_as_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='posted_as_kind',
            field=models.CharField(default='character', max_length=12),
        ),
        migrations.AddField(
            model_name='couriercontract',
            name='posted_as_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
