# Generated by Django 5.2.16 on 2026-07-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_courier_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpcontract',
            name='issuer_corporation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
