# Generated by Django 5.2.16 on 2026-07-17 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_corpcontract_issuer_corporation_id'),
        ('market', '0004_marketwatch'),
        ('stockpile', '0005_release_stranded_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('default_ship_class', models.CharField(choices=[('dst', 'Blockade Runner / DST'), ('freighter', 'Freighter'), ('jf', 'Jump Freighter')], db_default='jf', default='jf', help_text='Ship class assumed when an officer assigns a batch to the courier flow.', max_length=12)),
                ('default_dispatch_days', models.PositiveSmallIntegerField(db_default=2, default=2, help_text='Assumed days from opening a batch to it departing — the default ETD offset when none is typed.')),
                ('default_transit_days', models.PositiveSmallIntegerField(db_default=1, default=1, help_text='Assumed days in transit (depart → arrive) — the default ETA when no arrival date is typed.')),
                ('eta_sweep_enabled', models.BooleanField(db_default=False, default=False, help_text='Run the hourly batch sweep: flip batches to arrived from a verified courier contract or a completed haul, and flag late ones. Off: the beat is a no-op and officers click “arrived” by hand (the v1 workflow).')),
                ('late_grace_hours', models.PositiveSmallIntegerField(db_default=6, default=6, help_text="Hours past a batch's planned ETA before the sweep flags it late.")),
            ],
            options={
                'verbose_name': 'freight config',
                'verbose_name_plural': 'freight configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_default='open', db_index=True, default='open', max_length=12)),
                ('ship_class', models.CharField(choices=[('dst', 'Blockade Runner / DST'), ('freighter', 'Freighter'), ('jf', 'Jump Freighter')], db_default='jf', default='jf', max_length=12)),
                ('etd_planned', models.DateTimeField(blank=True, null=True)),
                ('eta_planned', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('freight_cost', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=20)),
                ('freight_breakdown', models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict)),
                ('late_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('courier_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.couriercontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='market.marketlocation')),
                ('hauling_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.haulingtask')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='market.marketlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity', models.BigIntegerField()),
                ('planned_quantity', models.BigIntegerField(db_default=0, default=0)),
                ('quantity_received', models.BigIntegerField(db_default=0, default=0)),
                ('unit_purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_source', models.CharField(blank=True, db_default='', default='', max_length=8)),
                ('freight_share', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=20)),
                ('purchase_ref', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.freightbatch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch_id', 'type_id'],
            },
        ),
        migrations.CreateModel(
            name='FreightReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('unit_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='logistics.freightbatchline')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stockpile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.stockpile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='freightbatch',
            index=models.Index(fields=['status'], name='logistics_f_status_1ef8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='freightbatch',
            index=models.Index(fields=['destination', 'status'], name='logistics_f_destina_abbc34_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('origin', 'destination'), name='uniq_open_freightbatch_per_lane'),
        ),
        migrations.AddConstraint(
            model_name='freightbatchline',
            constraint=models.UniqueConstraint(fields=('batch', 'type_id'), name='uniq_freightline_per_type'),
        ),
        migrations.AddConstraint(
            model_name='freightbatchline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='freightline_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='freightbatchline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0), ('quantity_received__lte', models.F('quantity'))), name='freightline_received_in_range'),
        ),
        migrations.AddConstraint(
            model_name='freightbatchline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gte', 0), ('planned_quantity__lte', models.F('quantity'))), name='freightline_planned_in_range'),
        ),
        migrations.AddIndex(
            model_name='freightreceipt',
            index=models.Index(fields=['line'], name='logistics_f_line_id_76f0de_idx'),
        ),
    ]
