# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('discord_webhook', 'Discord webhook'), ('in_app', 'In-app')], default='in_app', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('min_severity', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('doctrine_readiness', 'Doctrine readiness'), ('skill_training', 'Skill training'), ('stock_shortage', 'Stock shortage'), ('build_vs_buy', 'Build vs buy'), ('market_seeding', 'Market seeding'), ('hauling', 'Hauling'), ('newbro_next_step', 'Newbro next step'), ('combat_loss_pattern', 'Combat loss pattern'), ('officer_action', 'Officer action')], db_index=True, max_length=32)),
                ('subject_type', models.CharField(blank=True, max_length=32)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('logic_summary', models.CharField(blank=True, max_length=400)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('data_freshness', models.DateTimeField(blank=True, null=True)),
                ('required_permission', models.CharField(default='officer', max_length=32)),
                ('suggested_action', models.JSONField(blank=True, default=dict)),
                ('severity', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], db_index=True, default='new', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('severity', models.IntegerField(default=0)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('discord', 'Discord')], default='in_app', max_length=10)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='recommendations.recommendation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('linked_project_id', models.BigIntegerField(blank=True, null=True)),
                ('linked_hauling_task_id', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='recommendations.recommendation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['type', 'subject_type', 'subject_id', 'state'], name='recommendat_type_6a2f57_idx'),
        ),
    ]
