# Generated by Django 5.2.15 on 2026-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_type', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('text', models.TextField(blank=True)),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
