# Generated by Django 5.2.15 on 2026-07-05 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleticketledgerentry',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
