# Generated by Django 5.2.15 on 2026-07-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0003_occurred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflecontest',
            name='min_activity_metric',
            field=models.CharField(blank=True, help_text='Activity metric that gates a valid draw (blank = always valid).', max_length=32),
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='min_activity_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The contest is valid for an automatic draw only once this metric reaches this value.', max_digits=24),
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='prize_booster_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='prize_booster_metric',
            field=models.CharField(blank=True, help_text='Activity metric whose goal unlocks a prize-value boost (blank = off).', max_length=32),
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='prize_booster_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Boost ISK/PLEX prize values by this percent when the goal is reached (e.g. 10).', max_digits=6),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='forced_below_minimum',
            field=models.BooleanField(default=False, help_text='Drawn by leadership override despite unmet minimum activity.'),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='min_activity_met',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='prize_booster_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='prize_booster_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='awarded_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
