# Generated by Django 5.2.15 on 2026-07-07 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_activity_safeguard_booster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleOutreachOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(unique=True)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('opted_out_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaffleEnrolmentOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('would_be_tickets', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_outreach', to='raffle.rafflecontest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('contest', 'character_id')},
            },
        ),
    ]
