# Generated by Django 5.2.15 on 2026-07-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_raffleoutreachoptout_raffleenrolmentoutreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleconfig',
            name='budget_warn_pct',
            field=models.PositiveSmallIntegerField(default=80, help_text="Warn leadership once a month's committed prize value reaches this percent of the ceiling."),
        ),
        migrations.AddField(
            model_name='raffleconfig',
            name='monthly_prize_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly raffle prize ISK ceiling (0 = no limit). Warns near it and holds new contests once a month is committed past it.', max_digits=20),
        ),
    ]
