# Generated by Django 5.2.16 on 2026-07-29 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0007_ledger_reason_key_flag_detail_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleTicketPoolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('frozen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cutoff_at', models.DateTimeField(help_text='Ticket accrual cutoff this pool was taken against.')),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_pilots', models.IntegerField(default=0)),
                ('excluded_tickets', models.IntegerField(default=0)),
                ('excluded_pilots', models.IntegerField(default=0)),
                ('entries', models.JSONField(blank=True, default=list)),
                ('pilots', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('exclusion_summary', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='1', max_length=8)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('supersede_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-contest_id', '-version'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='raffledrawresult',
            name='uniq_raffle_result_per_prize',
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='next_ticket_number',
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='rafflecontest',
            name='ticket_numbers_backfilled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='redraw_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='redraw_reason',
            field=models.TextField(blank=True, db_default=''),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='snapshot_hash',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The earlier result this one replaces (forfeit / disqualification).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='raffle.raffledrawresult'),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='status_reason',
            field=models.CharField(blank=True, db_default='', help_text='Why this result was forfeited, voided or redrawn.', max_length=300),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='winning_ledger_entry',
            field=models.ForeignKey(blank=True, help_text='The award that owned the winning ticket — the evidence link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_results', to='raffle.raffleticketledgerentry'),
        ),
        migrations.AddField(
            model_name='raffledrawresult',
            name='winning_ticket_no',
            field=models.PositiveIntegerField(blank=True, help_text='The permanent ticket number that won. Null on pre-snapshot draws, where the winning ticket was never recorded.', null=True),
        ),
        migrations.AddField(
            model_name='raffleticketledgerentry',
            name='ticket_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='raffleticketledgerentry',
            index=models.Index(fields=['contest', 'ticket_start'], name='raffle_ledger_tno_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffledrawresult',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'won')), fields=('draw', 'prize'), name='uniq_raffle_result_per_prize'),
        ),
        migrations.AddConstraint(
            model_name='raffleticketledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_start__isnull', False)), fields=('contest', 'ticket_start'), name='uniq_raffle_ticket_start'),
        ),
        migrations.AddField(
            model_name='raffleticketpoolsnapshot',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_snapshots', to='raffle.rafflecontest'),
        ),
        migrations.AddField(
            model_name='raffleticketpoolsnapshot',
            name='frozen_by',
            field=models.ForeignKey(blank=True, help_text='Null = frozen automatically at contest close.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffleticketpoolsnapshot',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='raffle.raffleticketpoolsnapshot'),
        ),
        migrations.AddField(
            model_name='raffledraw',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='raffle.raffleticketpoolsnapshot'),
        ),
        migrations.AddIndex(
            model_name='raffleticketpoolsnapshot',
            index=models.Index(fields=['contest', '-version'], name='raffle_snap_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffleticketpoolsnapshot',
            constraint=models.UniqueConstraint(fields=('contest', 'version'), name='uniq_raffle_snapshot_version'),
        ),
    ]
