# Generated by Django 5.2.16 on 2026-07-29 14:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0009_backfill_ticket_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflecontest',
            name='prize_booster_applies_to',
            field=models.CharField(choices=[('both', 'Both ticket and rank prizes'), ('ticket', 'Ticket-draw prizes only'), ('rank', 'Rank prizes only')], db_default='both', default='both', help_text='Which kinds of prize the booster inflates when the goal is reached.', max_length=8),
        ),
        migrations.CreateModel(
            name='RaffleRankPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_key', models.CharField(max_length=24)),
                ('position', models.PositiveIntegerField(db_default=1, default=1, help_text='1 = top of that board.')),
                ('name', models.CharField(max_length=140)),
                ('prize_type', models.CharField(choices=[('isk', 'ISK'), ('plex', 'PLEX'), ('item', 'In-game item'), ('doctrine_ship', 'Doctrine ship'), ('capital', 'Capital ship'), ('supercapital', 'Supercapital ship'), ('custom', 'Custom reward')], db_default='isk', default='isk', max_length=14)),
                ('icon_type_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(db_default=1, default=1)),
                ('estimated_value', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=0, max_digits=20)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('delivery_instructions', models.TextField(blank=True, db_default='', default='', help_text='Public: how the winner receives the prize.')),
                ('internal_notes', models.TextField(blank=True, db_default='', default='', help_text='Internal — leaders only.')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_prizes', to='raffle.rafflecontest')),
            ],
            options={
                'ordering': ['contest', 'board_key', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RaffleRankAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winner_character_id', models.BigIntegerField(blank=True, null=True)),
                ('winner_character_name', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('metric_value', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=0, max_digits=24)),
                ('position', models.PositiveIntegerField(db_default=1, default=1)),
                ('standings', models.JSONField(blank=True, default=list)),
                ('awarded_value', models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=0, max_digits=20)),
                ('booster_applied', models.BooleanField(db_default=False, default=False)),
                ('status', models.CharField(choices=[('awarded', 'Awarded'), ('forfeited', 'Forfeited'), ('void', 'Void')], db_default='awarded', default='awarded', max_length=10)),
                ('status_reason', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('fulfil_status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_default='pending', db_index=True, default='pending', max_length=10)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilment_notes', models.TextField(blank=True, db_default='', default='')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_awards', to='raffle.rafflecontest')),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_awards', to='raffle.raffledraw')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('winner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle_rank_wins', to=settings.AUTH_USER_MODEL)),
                ('rank_prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='raffle.rafflerankprize')),
            ],
            options={
                'ordering': ['contest', 'rank_prize'],
            },
        ),
        migrations.AddIndex(
            model_name='rafflerankprize',
            index=models.Index(fields=['contest', 'board_key'], name='raffle_rankprize_idx'),
        ),
        migrations.AddConstraint(
            model_name='rafflerankprize',
            constraint=models.UniqueConstraint(fields=('contest', 'board_key', 'position'), name='uniq_raffle_rank_prize_slot'),
        ),
        migrations.AddConstraint(
            model_name='rafflerankprize',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 10)), name='ck_raffle_rank_prize_position'),
        ),
        migrations.AddIndex(
            model_name='rafflerankaward',
            index=models.Index(fields=['contest', 'status'], name='raffle_rankaward_idx'),
        ),
        migrations.AddConstraint(
            model_name='rafflerankaward',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'awarded')), fields=('rank_prize',), name='uniq_raffle_rank_award_live'),
        ),
    ]
