# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('links', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('account', 'Account'), ('skills', 'Skills'), ('doctrine', 'Doctrine'), ('activity', 'Activity')], default='account', max_length=12)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_detected', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='sso.evecharacter')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='onboarding.onboardingmilestone')),
            ],
            options={
                'unique_together': {('character', 'milestone')},
            },
        ),
    ]
