# Generated by Django 5.2.16 on 2026-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('sweep_enabled', models.BooleanField(db_default=False, default=False, help_text='Warm the board cache and fire the officer problem-set digest on its schedule. Off: the board is still viewable on demand, but nothing pings.')),
                ('at_risk_days', models.PositiveIntegerField(db_default=3, default=3, help_text='Flag an order as at-risk when its estimate is within this many days (also the stalled-haul age).')),
                ('commitments_due_days', models.PositiveIntegerField(db_default=7, default=7, help_text='Surface a restock commitment when it is due within this many days.')),
                ('stale_reconcile_days', models.PositiveIntegerField(db_default=14, default=14, help_text='Flag stocked fits not reconciled within this many days as a discrepancy.')),
            ],
            options={
                'verbose_name': 'board config',
                'verbose_name_plural': 'board configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
