"""Combat Signatures — deterministic procedural background generator (WS-2).

Draws the whole committed background library (``static/killboard/sigbg/<key>/*.png`` plus
``manifest.json``) from fixed integer seeds. Every design is wholly original abstract art —
no CCP artwork, logos, text or insignia — combining starfields, nebula banks, warp streaks,
tracer fire, drone swarms, tactical grids, wormhole rings, cyno flares and engine glows,
anchored on the app's Tailwind palette (see ``apps.killboard.signature_assets``).

Determinism is the contract that lets the test suite verify the committed bytes: every design
is drawn only from ``random.Random(seed)`` (never the global RNG, never the clock), rendered at
2× and LANCZOS-downscaled for clean edges, then quantized to a 256-colour adaptive palette. Run
inside the container (matching Pillow/zlib) so regenerated bytes are identical.

    manage.py generate_signature_backgrounds            # (re)build the whole library + manifest
    manage.py generate_signature_backgrounds --only KEY # rebuild one design in place
    manage.py generate_signature_backgrounds --check    # regenerate to a temp dir, diff checksums

``--check`` never touches the committed tree; it exits non-zero on any drift or contrast failure.
"""
from __future__ import annotations

import hashlib
import io
import math
import tempfile
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from PIL import Image, ImageChops, ImageDraw, ImageFilter

from apps.killboard.signature_assets import (
    AZURE,
    CYAN,
    EMBER,
    FAINT,
    FILE_KEYS,
    GOLD,
    GOLDB,
    GOLDDUST,
    INDIGO,
    KILL,
    LOSS,
    MUTED,
    PANEL2,
    PRESETS,
    ROSE,
    SMOKE,
    SPACE,
    TEAL,
    THUMB_KEY,
    VIOLET,
    apply_safe_scrim,
    canonical_rel,
    load_manifest,
    preset_size,
    sigbg_dir,
    text_zone_ok,
)

GENERATOR_VERSION = "1.0"
MODEL_VERSION = 1
GENERATED_DATE = "2026-07-22"
SUPERSAMPLE = 2

_REF_AREA = 1200.0 * 300.0  # the 2× standard preset — the density reference


def _area(w: int, h: int) -> float:
    """A density multiplier so element counts stay visually even across preset aspect ratios."""
    return (w * h) / _REF_AREA


def _mul(color, k: float):
    """A colour scaled by ``k`` and clamped to 0..255 (for brightness/alpha modulation)."""
    return tuple(max(0, min(255, int(round(c * k)))) for c in color)


def _scale_layer(layer, k: float):
    return layer.point(lambda v: max(0, min(255, int(v * k))))


def _stack(base, *layers):
    """Additively composite glowing ``layers`` (drawn on black) over ``base``."""
    out = base
    for layer in layers:
        out = ImageChops.add(out, layer)
    return out


# --------------------------------------------------------------------------- #
#  Procedural primitives (all deterministic given the passed RNG)
# --------------------------------------------------------------------------- #
def _vgrad(size, top, bottom):
    w, h = size
    col = Image.new("RGB", (1, h))
    px = col.load()
    for y in range(h):
        t = y / max(1, h - 1)
        px[0, y] = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))
    return col.resize((w, h))


def _black(size):
    return Image.new("RGB", size, (0, 0, 0))


def starfield(rng, size, *, count, tint=(255, 255, 255), max_r=1.6, bright=(50, 255), flares=0):
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    w, h = size
    strong = []
    for _ in range(count):
        x, y = rng.uniform(0, w), rng.uniform(0, h)
        b = rng.uniform(*bright)
        roll = rng.random()
        rad = 0.6 if roll < 0.7 else (1.1 if roll < 0.93 else max_r)
        col = _mul(tint, b / 255.0)
        if rad <= 0.7:
            d.point((x, y), fill=col)
        else:
            d.ellipse((x - rad, y - rad, x + rad, y + rad), fill=col)
        if b > 215 and rad >= 1.1:
            strong.append((x, y, col))
    for (x, y, col) in strong[:flares]:
        fl = _mul(col, 0.5)
        length = rng.uniform(3, 6)
        d.line((x - length, y, x + length, y), fill=fl)
        d.line((x, y - length, x, y + length), fill=fl)
    return layer


def nebula(rng, size, *, hues, blobs, blur, gain=1.0, spread=1.0, region=None):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    rx0, ry0, rx1, ry1 = region or (0, 0, w, h)
    for _ in range(blobs):
        cx, cy = rng.uniform(rx0, rx1), rng.uniform(ry0, ry1)
        rw = rng.uniform(0.12, 0.42) * (rx1 - rx0) * spread
        rh = rng.uniform(0.12, 0.42) * (ry1 - ry0) * spread
        b = rng.uniform(0.25, 1.0)
        d.ellipse((cx - rw, cy - rh, cx + rw, cy + rh), fill=_mul(rng.choice(hues), b))
    layer = layer.filter(ImageFilter.GaussianBlur(blur))
    return _scale_layer(layer, gain) if gain != 1.0 else layer


def glow(size, center, radius, color, *, gain=1.0, blur=None):
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    cx, cy = center
    d.ellipse((cx - radius, cy - radius, cx + radius, cy + radius), fill=_mul(color, gain))
    return layer.filter(ImageFilter.GaussianBlur(blur if blur is not None else radius * 0.6))


def warp_streaks(rng, size, *, vanish, count, color, gain=1.0, min_len=0.2, max_len=0.9,
                 blur=1.2, spread=1.0, r0_range=(0.05, 0.35)):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    vx, vy = vanish
    reach = max(w, h)
    for _ in range(count):
        ang = rng.uniform(0, 2 * math.pi)
        r0 = rng.uniform(*r0_range) * reach
        r1 = r0 + rng.uniform(min_len, max_len) * reach
        ca, sa = math.cos(ang), math.sin(ang) * spread
        x0, y0 = vx + ca * r0, vy + sa * r0
        x1, y1 = vx + ca * r1, vy + sa * r1
        b = rng.uniform(0.3, 1.0)
        width = rng.choice([1, 1, 1, 2])
        segs = 5
        for s in range(segs):
            t0, t1 = s / segs, (s + 1) / segs
            d.line((x0 + (x1 - x0) * t0, y0 + (y1 - y0) * t0,
                    x0 + (x1 - x0) * t1, y0 + (y1 - y0) * t1),
                   fill=_mul(color, gain * b * (1 - t0 * 0.8)), width=width)
    return layer.filter(ImageFilter.GaussianBlur(blur))


def tracer_dashes(rng, size, *, count, color, angle_deg, gain=1.0, region=None,
                  length=(0.04, 0.12), blur=0.8):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    rx0, ry0, rx1, ry1 = region or (0, 0, w, h)
    reach = max(w, h)
    for _ in range(count):
        x, y = rng.uniform(rx0, rx1), rng.uniform(ry0, ry1)
        length_px = rng.uniform(*length) * reach
        aa = math.radians(angle_deg + rng.uniform(-8, 8))
        ca, sa = math.cos(aa), math.sin(aa)
        b = rng.uniform(0.5, 1.0)
        width = rng.choice([1, 2, 2, 3])
        ex, ey = x + ca * length_px, y + sa * length_px
        d.line((x, y, ex, ey), fill=_mul(color, gain * b), width=width)
        d.ellipse((ex - 1.6, ey - 1.6, ex + 1.6, ey + 1.6), fill=_mul(color, min(1.0, gain * b * 1.3)))
    return layer.filter(ImageFilter.GaussianBlur(blur))


def smoke_trail(size, *, p0, p1, p2, color, gain=1.0, width0=6, blur=2.5):
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    steps = 60
    for i in range(steps + 1):
        t = i / steps
        x = (1 - t) ** 2 * p0[0] + 2 * (1 - t) * t * p1[0] + t ** 2 * p2[0]
        y = (1 - t) ** 2 * p0[1] + 2 * (1 - t) * t * p1[1] + t ** 2 * p2[1]
        r = width0 * (1 - t) * 0.9 + 1
        d.ellipse((x - r, y - r, x + r, y + r), fill=_mul(color, gain * (0.25 + 0.75 * (1 - t))))
    return layer.filter(ImageFilter.GaussianBlur(blur))


def drone_swarm(rng, size, *, count, color, region, gain=1.0):
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    rx0, ry0, rx1, ry1 = region
    for _ in range(count):
        x, y = rng.uniform(rx0, rx1), rng.uniform(ry0, ry1)
        s = rng.uniform(1.5, 4.0)
        ang = rng.uniform(0, 2 * math.pi)
        pts = [
            (x + math.cos(ang) * s, y + math.sin(ang) * s),
            (x + math.cos(ang + 2.5) * s * 0.7, y + math.sin(ang + 2.5) * s * 0.7),
            (x + math.cos(ang - 2.5) * s * 0.7, y + math.sin(ang - 2.5) * s * 0.7),
        ]
        b = rng.uniform(0.3, 0.8)
        d.polygon(pts, fill=_mul(color, gain * b * 0.5))
        d.point((x, y), fill=_mul(color, min(1.0, gain * b * 1.4)))
    return layer.filter(ImageFilter.GaussianBlur(0.6))


def hex_grid(size, *, color, radius=26, gain=1.0, blur=0.5):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    col = _mul(color, gain)
    dx = radius * math.sqrt(3)
    dy = radius * 1.5
    y = -radius
    row = 0
    while y < h + radius:
        xoff = 0 if row % 2 == 0 else dx / 2
        x = -radius
        while x < w + dx:
            cx, cy = x + xoff, y
            pts = [(cx + radius * math.cos(math.radians(60 * k + 30)),
                    cy + radius * math.sin(math.radians(60 * k + 30))) for k in range(6)]
            d.polygon(pts, outline=col)
            x += dx
        y += dy
        row += 1
    return layer.filter(ImageFilter.GaussianBlur(blur))


def perspective_grid(size, *, color, horizon=0.55, gain=1.0, cols=16, blur=0.6):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    col = _mul(color, gain)
    hy = h * horizon
    vpx = w * 0.5
    for i in range(cols + 1):
        d.line((w * i / cols, h, vpx, hy), fill=col)
    rows = 10
    for j in range(1, rows + 1):
        t = j / rows
        y = hy + (h - hy) * (t * t)
        d.line((0, y, w, y), fill=_mul(color, gain * (0.3 + 0.7 * t)))
    return layer.filter(ImageFilter.GaussianBlur(blur))


def rings(rng, size, *, center, color, count, gain=1.0, distort=0.0, blur=0.8, rmax=0.9):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    cx, cy = center
    base = rmax * max(w, h) * 0.5
    for i in range(1, count + 1):
        r = base * i / count
        rx = r * (1 + distort * rng.uniform(-1, 1)) if distort else r
        ry = r * (1 + distort * rng.uniform(-1, 1)) if distort else r
        b = gain * (0.35 + 0.65 * (1 - i / count))
        d.ellipse((cx - rx, cy - ry, cx + rx, cy + ry), outline=_mul(color, b))
    return layer.filter(ImageFilter.GaussianBlur(blur))


def scanlines(size, *, color, gap=6, gain=0.5):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    col = _mul(color, gain)
    y = 0
    while y < h:
        d.line((0, y, w, y), fill=col)
        y += gap
    return layer


def radar_sweep(size, *, center, color, angle_deg, width_deg=44, gain=0.5, radius=0.9, blur=6):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    cx, cy = center
    r = radius * max(w, h) * 0.5
    d.pieslice((cx - r, cy - r, cx + r, cy + r), angle_deg, angle_deg + width_deg, fill=_mul(color, gain))
    return layer.filter(ImageFilter.GaussianBlur(blur))


def corner_brackets(size, *, color, gain=0.7, inset=0.05, length=0.08, width=2):
    w, h = size
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    col = _mul(color, gain)
    ix, iy = w * inset, h * inset
    lx, ly = w * length, h * length
    for (x, y, sx, sy) in [(ix, iy, 1, 1), (w - ix, iy, -1, 1), (ix, h - iy, 1, -1), (w - ix, h - iy, -1, -1)]:
        d.line((x, y, x + lx * sx, y), fill=col, width=width)
        d.line((x, y, x, y + ly * sy), fill=col, width=width)
    return layer


def cyno_flare(size, *, center, color, gain=1.0, core=10, streak=0.8):
    w, h = size
    cx, cy = center
    layer = _black(size)
    d = ImageDraw.Draw(layer)
    d.ellipse((cx - core, cy - core, cx + core, cy + core), fill=_mul(color, gain))
    reach = streak * max(w, h) * 0.5
    for (dx, dy, wd) in [(1, 0, 2), (0, 1, 2), (0.7, 0.7, 1), (0.7, -0.7, 1)]:
        d.line((cx - dx * reach, cy - dy * reach, cx + dx * reach, cy + dy * reach),
               fill=_mul(color, gain * 0.5), width=wd)
    layer = layer.filter(ImageFilter.GaussianBlur(2.0))
    halo = _black(size)
    ImageDraw.Draw(halo).ellipse((cx - core * 3, cy - core * 3, cx + core * 3, cy + core * 3),
                                 fill=_mul(color, gain * 0.6))
    return ImageChops.add(layer, halo.filter(ImageFilter.GaussianBlur(core * 2)))


# --------------------------------------------------------------------------- #
#  Designs — each returns an RGB image at the given (already 2×) size.
#  The framework applies the safe-area scrim and downscales; designs never
#  darken the safe zones themselves.
# --------------------------------------------------------------------------- #
def d_nebula_emberfront(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(INDIGO, 0.25))
    clouds = nebula(rng, (w, h), hues=[EMBER, ROSE, GOLDDUST], blobs=int(9 * _area(w, h)) + 4,
                    blur=max(w, h) * 0.06, gain=0.85, region=(w * 0.30, 0, w, h))
    core = glow((w, h), (w * 0.78, h * 0.30), max(w, h) * 0.34, GOLD, gain=0.55)
    stars = starfield(rng, (w, h), count=int(150 * _area(w, h)), max_r=1.6, bright=(40, 230), flares=6)
    return _stack(base, clouds, core, stars)


def d_nebula_cyandrift(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(TEAL, 0.18))
    clouds = nebula(rng, (w, h), hues=[CYAN, TEAL, AZURE], blobs=int(10 * _area(w, h)) + 4,
                    blur=max(w, h) * 0.07, gain=0.8, region=(w * 0.28, 0, w, h))
    core = glow((w, h), (w * 0.82, h * 0.62), max(w, h) * 0.30, CYAN, gain=0.5)
    stars = starfield(rng, (w, h), count=int(260 * _area(w, h)), max_r=1.4, bright=(50, 240), flares=8)
    return _stack(base, clouds, core, stars)


def d_nebula_violet_veil(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(VIOLET, 0.16))
    clouds = nebula(rng, (w, h), hues=[VIOLET, ROSE, INDIGO], blobs=int(11 * _area(w, h)) + 5,
                    blur=max(w, h) * 0.08, gain=0.85, region=(w * 0.26, 0, w, h))
    rim = glow((w, h), (w * 0.9, h * 0.2), max(w, h) * 0.26, GOLDB, gain=0.32)
    stars = starfield(rng, (w, h), count=int(170 * _area(w, h)), max_r=1.5, bright=(45, 225), flares=5)
    return _stack(base, clouds, rim, stars)


def d_nebula_deepfield(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    smudges = nebula(rng, (w, h), hues=[TEAL, VIOLET, INDIGO], blobs=int(6 * _area(w, h)) + 3,
                     blur=max(w, h) * 0.05, gain=0.4, region=(w * 0.3, 0, w, h))
    stars = starfield(rng, (w, h), count=int(520 * _area(w, h)), max_r=1.5, bright=(30, 255), flares=10)
    return _stack(base, smudges, stars)


def d_fleet_swarm(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(AZURE, 0.10))
    haze = glow((w, h), (w * 0.78, h * 0.32), max(w, h) * 0.34, CYAN, gain=0.3)
    stars = starfield(rng, (w, h), count=int(130 * _area(w, h)), bright=(40, 200))
    swarm = drone_swarm(rng, (w, h), count=int(120 * _area(w, h)) + 40, color=CYAN,
                        region=(w * 0.34, h * 0.05, w * 0.98, h * 0.95), gain=0.9)
    swarm2 = drone_swarm(rng, (w, h), count=int(60 * _area(w, h)) + 20, color=GOLDB,
                         region=(w * 0.45, h * 0.1, w * 0.95, h * 0.9), gain=0.7)
    return _stack(base, haze, stars, swarm, swarm2)


def d_fleet_formation(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(GOLDDUST, 0.08))
    stars = starfield(rng, (w, h), count=int(120 * _area(w, h)), bright=(40, 200))
    out = _stack(base, stars)
    engines = _black((w, h))
    de = ImageDraw.Draw(engines)
    dsil = ImageDraw.Draw(out)
    vx, vy = w * 0.92, h * 0.28
    ranks = 5
    for r in range(ranks):
        t = r / (ranks - 1)
        scale = 0.35 + 0.65 * t
        count = r + 1
        for k in range(count):
            spread = (k - (count - 1) / 2)
            cx = vx - t * w * 0.55 + spread * 0.05 * w * t
            cy = vy + spread * 0.14 * h * (0.4 + t)
            sl = 0.045 * w * scale
            sh = sl * 0.5
            dsil.polygon([(cx, cy), (cx + sl, cy - sh), (cx + sl * 1.15, cy), (cx + sl, cy + sh)],
                         fill=_mul(SPACE, 0.6))
            de.ellipse((cx - 2.5, cy - 2, cx + 2.5, cy + 2), fill=_mul(GOLD, 0.9 * (0.4 + t)))
    out = ImageChops.add(out, engines.filter(ImageFilter.GaussianBlur(2.2)))
    return out


def d_fleet_armada(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(EMBER, 0.14))
    backlight = glow((w, h), (w * 0.64, h * 0.78), max(w, h) * 0.5, GOLDDUST, gain=0.5)
    stars = starfield(rng, (w, h), count=int(110 * _area(w, h)), bright=(35, 190))
    out = _stack(base, backlight, stars)
    dsil = ImageDraw.Draw(out)
    engines = _black((w, h))
    de = ImageDraw.Draw(engines)
    hy = h * 0.72
    for _ in range(7):
        sx = rng.uniform(w * 0.34, w * 0.98)
        sy = hy + rng.uniform(-h * 0.06, h * 0.05)
        sl = rng.uniform(0.05, 0.13) * w
        sh = sl * rng.uniform(0.16, 0.26)
        dsil.polygon([(sx, sy), (sx + sl, sy - sh * 0.5), (sx + sl, sy + sh * 0.5), (sx, sy + sh)],
                     fill=_mul(SPACE, 0.65))
        de.ellipse((sx - 3, sy + sh * 0.3 - 2, sx + 3, sy + sh * 0.3 + 3), fill=_mul(GOLD, 0.85))
    out = ImageChops.add(out, engines.filter(ImageFilter.GaussianBlur(2.0)))
    return out


def d_fleet_scramble(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(INDIGO, 0.12))
    stars = starfield(rng, (w, h), count=int(120 * _area(w, h)), bright=(40, 210))
    dots = drone_swarm(rng, (w, h), count=int(70 * _area(w, h)) + 25, color=GOLDB,
                       region=(w * 0.34, h * 0.06, w * 0.97, h * 0.94), gain=0.85)
    tracers = tracer_dashes(rng, (w, h), count=int(26 * _area(w, h)) + 10, color=GOLD,
                            angle_deg=-24, region=(w * 0.36, h * 0.1, w * 0.95, h * 0.9),
                            length=(0.03, 0.08), gain=0.8)
    tracers2 = tracer_dashes(rng, (w, h), count=int(14 * _area(w, h)) + 6, color=CYAN,
                             angle_deg=200, region=(w * 0.4, h * 0.15, w * 0.95, h * 0.85),
                             length=(0.03, 0.07), gain=0.7)
    return _stack(base, stars, dots, tracers, tracers2)


def d_tactical_hexgrid(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    mesh = hex_grid((w, h), color=CYAN, radius=max(12, int(w * 0.028)), gain=0.16)
    scans = scanlines((w, h), color=CYAN, gap=max(4, int(h * 0.03)), gain=0.06)
    glowc = glow((w, h), (w * 0.8, h * 0.3), max(w, h) * 0.34, CYAN, gain=0.28)
    brackets = corner_brackets((w, h), color=CYAN, gain=0.55)
    stars = starfield(rng, (w, h), count=int(60 * _area(w, h)), bright=(30, 150))
    return _stack(base, glowc, mesh, scans, brackets, stars)


def d_tactical_gridfade(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(TEAL, 0.10))
    horizon = glow((w, h), (w * 0.6, h * 0.56), max(w, h) * 0.42, CYAN, gain=0.3)
    grid = perspective_grid((w, h), color=CYAN, horizon=0.56, gain=0.22, cols=int(14 + w * 0.006))
    stars = starfield(rng, (w, h), count=int(140 * _area(w, h)), bright=(40, 200))
    return _stack(base, horizon, grid, stars)


def d_tactical_radar(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    cx, cy = w * 0.78, h * 0.5
    ring = rings(rng, (w, h), center=(cx, cy), color=CYAN, count=6, gain=0.4, rmax=1.0)
    sweep = radar_sweep((w, h), center=(cx, cy), color=CYAN, angle_deg=-30, gain=0.32)
    d = ImageDraw.Draw(base)
    d.line((cx - w * 0.4, cy, cx + w * 0.4, cy), fill=_mul(CYAN, 0.18))
    d.line((cx, cy - h * 0.45, cx, cy + h * 0.45), fill=_mul(CYAN, 0.18))
    blips = drone_swarm(rng, (w, h), count=int(30 * _area(w, h)) + 8, color=GOLDB,
                        region=(w * 0.5, h * 0.12, w * 0.96, h * 0.88), gain=1.0)
    return _stack(base, sweep, ring, blips)


def d_tactical_wormhole(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(VIOLET, 0.12))
    cx, cy = w * 0.8, h * 0.42
    core = glow((w, h), (cx, cy), max(w, h) * 0.14, CYAN, gain=0.5)
    ring1 = rings(rng, (w, h), center=(cx, cy), color=CYAN, count=9, gain=0.42, distort=0.05, rmax=0.7)
    ring2 = rings(rng, (w, h), center=(cx, cy), color=VIOLET, count=7, gain=0.3, distort=0.09, rmax=1.0)
    stars = starfield(rng, (w, h), count=int(120 * _area(w, h)), bright=(40, 210))
    return _stack(base, stars, ring2, ring1, core)


def d_tactical_hud(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    mesh = hex_grid((w, h), color=CYAN, radius=max(16, int(w * 0.04)), gain=0.08)
    scans = scanlines((w, h), color=CYAN, gap=max(4, int(h * 0.028)), gain=0.05)
    brackets = corner_brackets((w, h), color=GOLDB, gain=0.5, length=0.1)
    reticle = rings(rng, (w, h), center=(w * 0.8, h * 0.5), color=CYAN, count=3, gain=0.4, rmax=0.4)
    d = ImageDraw.Draw(base)
    for i in range(1, 20):
        x = w * 0.34 + i * (w * 0.033)
        if x > w * 0.98:
            break
        d.line((x, h * 0.08, x, h * 0.12), fill=_mul(CYAN, 0.22))
    return _stack(base, mesh, scans, reticle, brackets)


def d_warp_tunnel(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(AZURE, 0.10))
    vanish = (w * 0.82, h * 0.34)
    core = glow((w, h), vanish, max(w, h) * 0.18, CYAN, gain=0.5)
    streaks = warp_streaks(rng, (w, h), vanish=vanish, count=int(150 * _area(w, h)) + 60,
                           color=CYAN, gain=0.8, min_len=0.15, max_len=0.75)
    hot = warp_streaks(rng, (w, h), vanish=vanish, count=int(40 * _area(w, h)) + 15,
                       color=GOLDB, gain=0.6, min_len=0.1, max_len=0.5)
    return _stack(base, core, streaks, hot)


def d_warp_streaks(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(GOLDDUST, 0.10))
    vanish = (w * 1.15, h * 0.5)
    streaks = warp_streaks(rng, (w, h), vanish=vanish, count=int(120 * _area(w, h)) + 50,
                           color=GOLD, gain=0.7, min_len=0.2, max_len=0.9, spread=0.25, blur=1.6)
    glowc = glow((w, h), (w * 0.9, h * 0.4), max(w, h) * 0.3, GOLDB, gain=0.35)
    stars = starfield(rng, (w, h), count=int(80 * _area(w, h)), bright=(30, 170))
    return _stack(base, glowc, streaks, stars)


def d_warp_jump(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    center = (w * 0.8, h * 0.45)
    burst = warp_streaks(rng, (w, h), vanish=center, count=int(130 * _area(w, h)) + 60,
                         color=(210, 235, 255), gain=0.75, min_len=0.12, max_len=0.7,
                         r0_range=(0.02, 0.12))
    flare = cyno_flare((w, h), center=center, color=(210, 235, 255), gain=0.9,
                       core=max(8, int(w * 0.016)), streak=0.7)
    stars = starfield(rng, (w, h), count=int(90 * _area(w, h)), bright=(30, 180))
    return _stack(base, stars, burst, flare)


def d_warp_driftlines(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(VIOLET, 0.12))
    vanish = (w * 1.2, h * 0.1)
    streaks = warp_streaks(rng, (w, h), vanish=vanish, count=int(90 * _area(w, h)) + 40,
                           color=VIOLET, gain=0.6, min_len=0.25, max_len=1.0, spread=0.5, blur=2.2)
    glowc = glow((w, h), (w * 0.85, h * 0.3), max(w, h) * 0.32, ROSE, gain=0.28)
    stars = starfield(rng, (w, h), count=int(120 * _area(w, h)), bright=(40, 200))
    return _stack(base, glowc, streaks, stars)


def d_weapons_tracers(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(EMBER, 0.10))
    stars = starfield(rng, (w, h), count=int(90 * _area(w, h)), bright=(30, 180))
    region = (w * 0.34, h * 0.05, w * 0.98, h * 0.95)
    gold = tracer_dashes(rng, (w, h), count=int(34 * _area(w, h)) + 14, color=GOLD,
                         angle_deg=-22, region=region, length=(0.04, 0.11), gain=0.85)
    green = tracer_dashes(rng, (w, h), count=int(16 * _area(w, h)) + 6, color=KILL,
                          angle_deg=-18, region=region, length=(0.04, 0.1), gain=0.75)
    muzzle = glow((w, h), (w * 0.36, h * 0.75), max(w, h) * 0.16, GOLD, gain=0.3)
    return _stack(base, stars, muzzle, gold, green)


def d_weapons_missilesmoke(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(SMOKE, 0.06))
    stars = starfield(rng, (w, h), count=int(90 * _area(w, h)), bright=(30, 170))
    out = _stack(base, stars)
    trails = int(4 * _area(w, h)) + 3
    for _ in range(trails):
        sx = rng.uniform(w * 0.36, w * 0.5)
        sy = rng.uniform(h * 0.6, h * 0.95)
        ex = rng.uniform(w * 0.7, w * 0.98)
        ey = rng.uniform(h * 0.05, h * 0.4)
        mx = rng.uniform(w * 0.5, w * 0.75)
        my = rng.uniform(h * 0.1, h * 0.6)
        trail = smoke_trail((w, h), p0=(sx, sy), p1=(mx, my), p2=(ex, ey),
                            color=SMOKE, gain=0.5, width0=max(4, w * 0.007))
        head = glow((w, h), (ex, ey), max(w, h) * 0.05, EMBER, gain=0.8)
        out = ImageChops.add(ImageChops.add(out, trail), head)
    return out


def d_weapons_detonation(rng, w, h):
    base = Image.new("RGB", (w, h), SPACE)
    center = (w * 0.8, h * 0.46)
    fire = glow((w, h), center, max(w, h) * 0.24, EMBER, gain=0.75)
    coreg = glow((w, h), center, max(w, h) * 0.1, GOLDB, gain=0.9)
    shock = rings(rng, (w, h), center=center, color=GOLD, count=2, gain=0.4, rmax=0.8, blur=1.4)
    sparks = tracer_dashes(rng, (w, h), count=int(40 * _area(w, h)) + 18, color=GOLDB,
                           angle_deg=0, region=(w * 0.55, h * 0.15, w * 0.98, h * 0.85),
                           length=(0.02, 0.06), gain=0.8, blur=0.6)
    stars = starfield(rng, (w, h), count=int(70 * _area(w, h)), bright=(25, 150))
    return _stack(base, stars, fire, shock, coreg, sparks)


def d_weapons_crossfire(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(LOSS, 0.08))
    stars = starfield(rng, (w, h), count=int(80 * _area(w, h)), bright=(30, 170))
    region = (w * 0.34, h * 0.05, w * 0.98, h * 0.95)
    a = tracer_dashes(rng, (w, h), count=int(26 * _area(w, h)) + 10, color=GOLD,
                      angle_deg=-26, region=region, length=(0.04, 0.1), gain=0.8)
    b = tracer_dashes(rng, (w, h), count=int(22 * _area(w, h)) + 9, color=LOSS,
                      angle_deg=200, region=region, length=(0.04, 0.1), gain=0.75)
    c = tracer_dashes(rng, (w, h), count=int(12 * _area(w, h)) + 5, color=GOLDB,
                      angle_deg=-8, region=region, length=(0.03, 0.08), gain=0.7)
    return _stack(base, stars, a, b, c)


def d_industrial_cynofield(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(GOLDDUST, 0.10))
    haze = glow((w, h), (w * 0.78, h * 0.5), max(w, h) * 0.4, GOLDDUST, gain=0.32)
    flare = cyno_flare((w, h), center=(w * 0.8, h * 0.44), color=GOLD, gain=0.95,
                       core=max(9, int(w * 0.018)), streak=0.85)
    flare2 = cyno_flare((w, h), center=(w * 0.55, h * 0.8), color=GOLDB, gain=0.5,
                        core=max(5, int(w * 0.01)), streak=0.4)
    stars = starfield(rng, (w, h), count=int(80 * _area(w, h)), bright=(30, 170))
    return _stack(base, stars, haze, flare, flare2)


def d_industrial_refinery(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(PANEL2, 0.9))
    haze = glow((w, h), (w * 0.75, h * 0.4), max(w, h) * 0.34, CYAN, gain=0.22)
    stars = starfield(rng, (w, h), count=int(70 * _area(w, h)), bright=(25, 150))
    out = _stack(base, haze, stars)
    dsil = ImageDraw.Draw(out)
    lights = _black((w, h))
    dl = ImageDraw.Draw(lights)
    for _ in range(5):
        bx = rng.uniform(w * 0.4, w * 0.92)
        bw = rng.uniform(0.03, 0.08) * w
        bh = rng.uniform(0.3, 0.75) * h
        by = h - bh
        dsil.rectangle((bx, by, bx + bw, h), fill=_mul(SPACE, 0.5))
        for _ in range(int(bh / (h * 0.12)) + 1):
            ly = rng.uniform(by + 4, h - 4)
            col = rng.choice([CYAN, GOLD, GOLDB])
            dl.ellipse((bx + bw * 0.3, ly, bx + bw * 0.3 + 1.6, ly + 1.6), fill=_mul(col, 0.9))
    out = ImageChops.add(out, lights.filter(ImageFilter.GaussianBlur(0.8)))
    return out


def d_industrial_oreveins(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(PANEL2, 0.7))
    stars = starfield(rng, (w, h), count=int(60 * _area(w, h)), bright=(20, 140))
    out = _stack(base, stars)
    veins = _black((w, h))
    dv = ImageDraw.Draw(veins)
    for _ in range(int(10 * _area(w, h)) + 6):
        x = rng.uniform(w * 0.36, w * 0.96)
        y = rng.uniform(h * 0.06, h * 0.94)
        r = rng.uniform(0.02, 0.09) * min(w, h)
        col = rng.choice([MUTED, FAINT, TEAL])
        pts = []
        n = rng.randint(6, 9)
        for k in range(n):
            ang = 2 * math.pi * k / n
            rr = r * rng.uniform(0.6, 1.2)
            pts.append((x + math.cos(ang) * rr, y + math.sin(ang) * rr))
        dv.polygon(pts, outline=_mul(col, 0.5))
        if rng.random() < 0.5:
            dv.point((x, y), fill=_mul(CYAN, 0.9))
    shimmer = glow((w, h), (w * 0.82, h * 0.35), max(w, h) * 0.3, CYAN, gain=0.18)
    return ImageChops.add(_stack(out, shimmer), veins.filter(ImageFilter.GaussianBlur(0.6)))


def d_industrial_enginewake(rng, w, h):
    base = _vgrad((w, h), SPACE, _mul(AZURE, 0.10))
    stars = starfield(rng, (w, h), count=int(90 * _area(w, h)), bright=(30, 180))
    out = _stack(base, stars)
    for _ in range(int(3 * _area(w, h)) + 2):
        ey = rng.uniform(h * 0.12, h * 0.88)
        ex = rng.uniform(w * 0.55, w * 0.8)
        col = rng.choice([GOLD, CYAN, GOLDB])
        core = glow((w, h), (ex, ey), max(w, h) * 0.05, col, gain=0.8)
        end = (w * 1.0, ey + rng.uniform(-h * 0.05, h * 0.05))
        wake = smoke_trail((w, h), p0=(ex, ey), p1=(ex + w * 0.12, ey), p2=end,
                           color=col, gain=0.4, width0=max(3, w * 0.006), blur=3.0)
        out = ImageChops.add(ImageChops.add(out, wake), core)
    return out


# --------------------------------------------------------------------------- #
#  Registry — (key, name, category, seed, display_order, notes, fn)
# --------------------------------------------------------------------------- #
DESIGNS: list[dict] = [
    dict(key="nebula-emberfront", name="Ember Front", category="nebula", seed=10001, display_order=10,
         notes="Warm ember and rose nebula banks under a gold core glow over a sparse starfield.",
         fn=d_nebula_emberfront),
    dict(key="nebula-cyandrift", name="Cyan Drift", category="nebula", seed=10002, display_order=20,
         notes="Cool cyan and teal nebula wisps behind a dense fine starfield.", fn=d_nebula_cyandrift),
    dict(key="nebula-violet-veil", name="Violet Veil", category="nebula", seed=10003, display_order=30,
         notes="Layered violet and rose clouds with a faint gold rim light.", fn=d_nebula_violet_veil),
    dict(key="nebula-deepfield", name="Deep Field", category="nebula", seed=10004, display_order=40,
         notes="A very dark deep-field: distant colour smudges and a dense scatter of tiny stars.",
         fn=d_nebula_deepfield),
    dict(key="fleet-swarm", name="Drone Swarm", category="fleet", seed=10101, display_order=50,
         notes="A loose flock of drone silhouettes drifting through cyan haze.", fn=d_fleet_swarm),
    dict(key="fleet-formation", name="Attack Formation", category="fleet", seed=10102, display_order=60,
         notes="A receding V-formation of gunships with gold engine glows.", fn=d_fleet_formation),
    dict(key="fleet-armada", name="Armada", category="fleet", seed=10103, display_order=70,
         notes="Backlit capital silhouettes on a burning horizon.", fn=d_fleet_armada),
    dict(key="fleet-scramble", name="Scramble", category="fleet", seed=10104, display_order=80,
         notes="A chaotic dogfight of light craft and crossing tracer hints.", fn=d_fleet_scramble),
    dict(key="tactical-hexgrid", name="Hex Grid", category="tactical", seed=10201, display_order=90,
         notes="A faint cyan hex mesh with scanlines and corner brackets.", fn=d_tactical_hexgrid),
    dict(key="tactical-gridfade", name="Grid Fade", category="tactical", seed=10202, display_order=100,
         notes="A perspective floor grid receding into a cyan horizon glow.", fn=d_tactical_gridfade),
    dict(key="tactical-radar", name="Radar", category="tactical", seed=10203, display_order=110,
         notes="Concentric radar rings, a sweep wedge and gold contact blips.", fn=d_tactical_radar),
    dict(key="tactical-wormhole", name="Wormhole", category="tactical", seed=10204, display_order=120,
         notes="Concentric distorted rings around a cyan wormhole core.", fn=d_tactical_wormhole),
    dict(key="tactical-hud", name="Tactical HUD", category="tactical", seed=10205, display_order=130,
         notes="An interface overlay of reticles, brackets, tick marks and scanlines.", fn=d_tactical_hud),
    dict(key="warp-tunnel", name="Warp Tunnel", category="warp", seed=10301, display_order=140,
         notes="Cyan warp streaks converging on a bright vanishing point.", fn=d_warp_tunnel),
    dict(key="warp-streaks", name="Warp Streaks", category="warp", seed=10302, display_order=150,
         notes="Long horizontal gold warp motion lines.", fn=d_warp_streaks),
    dict(key="warp-jump", name="Jump Flash", category="warp", seed=10303, display_order=160,
         notes="A radial jump-flash burst around a bright white core.", fn=d_warp_jump),
    dict(key="warp-driftlines", name="Drift Lines", category="warp", seed=10304, display_order=170,
         notes="Soft diagonal violet warp streaks over a rose glow.", fn=d_warp_driftlines),
    dict(key="weapons-tracers", name="Tracer Fire", category="weapons", seed=10401, display_order=180,
         notes="Angled gold and green tracer-fire dashes from a muzzle glow.", fn=d_weapons_tracers),
    dict(key="weapons-missilesmoke", name="Missile Smoke", category="weapons", seed=10402, display_order=190,
         notes="Curved tapered missile smoke trails tipped with ember heads.", fn=d_weapons_missilesmoke),
    dict(key="weapons-detonation", name="Detonation", category="weapons", seed=10403, display_order=200,
         notes="A radial detonation glow, shockwave ring and debris sparks.", fn=d_weapons_detonation),
    dict(key="weapons-crossfire", name="Crossfire", category="weapons", seed=10404, display_order=210,
         notes="Dense multi-directional gold and red tracer crossfire.", fn=d_weapons_crossfire),
    dict(key="industrial-cynofield", name="Cyno Field", category="industrial", seed=10501, display_order=220,
         notes="A bright cyno flare with lens streaks over golden haze.", fn=d_industrial_cynofield),
    dict(key="industrial-refinery", name="Refinery", category="industrial", seed=10502, display_order=230,
         notes="Abstract structural silhouettes speckled with status lights.", fn=d_industrial_refinery),
    dict(key="industrial-oreveins", name="Ore Veins", category="industrial", seed=10503, display_order=240,
         notes="Asteroid ore-vein facets shimmering with cyan flecks.", fn=d_industrial_oreveins),
    dict(key="industrial-enginewake", name="Engine Wake", category="industrial", seed=10504, display_order=250,
         notes="Engine cores trailing long directional exhaust wakes.", fn=d_industrial_enginewake),
]


def _design_by_key(key: str) -> dict:
    for design in DESIGNS:
        if design["key"] == key:
            return design
    raise CommandError(f"unknown design key: {key}")


# --------------------------------------------------------------------------- #
#  Rendering & encoding
# --------------------------------------------------------------------------- #
def _render_preset(design: dict, size: tuple[int, int]):
    """Render one design at ``size`` (2× internally), scrimmed, downscaled — RGB, pre-quantize."""
    import random

    w, h = size
    rng = random.Random(design["seed"])  # noqa: S311 — procedural art, not cryptography
    art = design["fn"](rng, w * SUPERSAMPLE, h * SUPERSAMPLE)
    scrimmed = apply_safe_scrim(art)
    return scrimmed.resize((w, h), Image.LANCZOS)


def _encode_png(img) -> bytes:
    quant = img.convert("RGB").quantize(colors=256, method=Image.Quantize.MEDIANCUT,
                                        dither=Image.Dither.FLOYDSTEINBERG)
    buf = io.BytesIO()
    quant.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _build_design_pngs(design: dict) -> dict[str, bytes]:
    """All committed PNG bytes for a design, keyed by file name (presets + thumb)."""
    out: dict[str, bytes] = {}
    std_master = None
    for preset, size in PRESETS.items():
        master = _render_preset(design, size)
        if preset == "standard":
            std_master = master
        out[preset] = _encode_png(master)
    out[THUMB_KEY] = _encode_png(std_master.resize(preset_size(THUMB_KEY), Image.LANCZOS))
    return out


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _combined_checksum(files: dict[str, str]) -> str:
    """A single per-design checksum folding in every file's digest (order-stable)."""
    joined = "".join(f"{k}:{files[k]}" for k in sorted(files))
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def _manifest_entry(design: dict, pngs: dict[str, bytes]) -> dict:
    files = {}
    per_sha = {}
    for name in FILE_KEYS:
        sha = _sha256(pngs[name])
        files[name] = {"path": canonical_rel(design["key"], name), "sha256": sha}
        per_sha[name] = sha
    return {
        "key": design["key"],
        "name": design["name"],
        "category": design["category"],
        "seed": design["seed"],
        "display_order": design["display_order"],
        "version": MODEL_VERSION,
        "checksum": _combined_checksum(per_sha),
        "files": files,
        "provenance": {
            "origin": "procedural-original",
            "source": "generate_signature_backgrounds",
            "license": "MIT (project)",
            "notes": design["notes"],
        },
    }


class Command(BaseCommand):
    help = "Generate the Combat Signatures background library (deterministic procedural art)."

    def add_arguments(self, parser) -> None:
        parser.add_argument("--only", metavar="KEY", default=None,
                            help="Regenerate only this design key (in place).")
        parser.add_argument("--check", action="store_true",
                            help="Regenerate into a temp dir and diff checksums; exit 1 on drift.")
        parser.add_argument("--out", metavar="DIR", default=None,
                            help="Write into DIR instead of the committed static tree (testing).")

    def handle(self, *args, **options) -> None:
        only = options["only"]
        designs = [_design_by_key(only)] if only else DESIGNS
        if options["check"]:
            self._run_check(designs)
            return
        out_root = Path(options["out"]) if options["out"] else sigbg_dir()
        self._write(designs, out_root, only=only)

    # -- write mode ---------------------------------------------------------- #
    def _write(self, designs, out_root: Path, *, only) -> None:
        out_root.mkdir(parents=True, exist_ok=True)
        # Preserve untouched entries when regenerating a single design.
        existing = {}
        mpath = out_root / "manifest.json"
        if mpath.exists():
            existing = {bg["key"]: bg for bg in load_manifest(mpath).get("backgrounds", [])}
        entries = dict(existing) if only else {}
        for design in designs:
            dir_path = out_root / design["key"]
            dir_path.mkdir(parents=True, exist_ok=True)
            pngs = _build_design_pngs(design)
            for name, data in pngs.items():
                (dir_path / f"{name}.png").write_bytes(data)
                img = Image.open(io.BytesIO(data)).convert("RGB")
                if not text_zone_ok(img):
                    raise CommandError(f"{design['key']} {name}: fails text_zone_ok (safe area too bright)")
            entries[design["key"]] = _manifest_entry(design, pngs)
            self.stdout.write(f"  {design['key']}: {len(pngs)} files")
        manifest = {
            "generator_version": GENERATOR_VERSION,
            "generated": GENERATED_DATE,
            "backgrounds": sorted(entries.values(), key=lambda e: (e["display_order"], e["key"])),
        }
        mpath.write_text(_dump_manifest(manifest), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(
            f"Wrote {len(designs)} design(s); manifest lists {len(manifest['backgrounds'])}."
        ))

    # -- check mode ---------------------------------------------------------- #
    def _run_check(self, designs) -> None:
        committed = {bg["key"]: bg for bg in load_manifest().get("backgrounds", [])}
        drift = []
        with tempfile.TemporaryDirectory() as tmp:
            tmp_root = Path(tmp)
            for design in designs:
                key = design["key"]
                want = committed.get(key)
                pngs = _build_design_pngs(design)
                dir_path = tmp_root / key
                dir_path.mkdir(parents=True, exist_ok=True)
                for name in FILE_KEYS:
                    fpath = dir_path / f"{name}.png"
                    fpath.write_bytes(pngs[name])
                    got = _sha256(fpath.read_bytes())
                    expect = (want or {}).get("files", {}).get(name, {}).get("sha256")
                    if want is None:
                        drift.append(f"{key}: not in committed manifest")
                        break
                    if got != expect:
                        drift.append(f"{key}/{name}.png: checksum drift")
                    if not text_zone_ok(Image.open(fpath).convert("RGB")):
                        drift.append(f"{key}/{name}.png: fails text_zone_ok")
        if drift:
            for line in drift:
                self.stderr.write(self.style.ERROR(line))
            raise CommandError(f"{len(drift)} background(s) drifted from the committed library.")
        self.stdout.write(self.style.SUCCESS(f"OK — {len(designs)} design(s) match the committed library."))


def _dump_manifest(manifest: dict) -> str:
    import json

    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
