# Generated by Django 5.2.15 on 2026-06-22 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0002_initial'),
        ('killboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SrpBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='e.g. 2026-06', max_length=20, unique=True)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(choices=[('hull', 'Hull only'), ('fit', 'Full fit'), ('fixed', 'Fixed cap')], default='fit', max_length=8)),
                ('max_payout', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('doctrine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srp_rules', to='doctrines.doctrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrpClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied'), ('paid', 'Paid')], db_index=True, default='submitted', max_length=10)),
                ('basis', models.CharField(choices=[('hull', 'Hull only'), ('fit', 'Full fit'), ('fixed', 'Fixed cap')], default='fit', max_length=8)),
                ('computed_payout', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('explanation', models.CharField(blank=True, max_length=300)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srp_claims', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctrine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srp_claims', to='doctrines.doctrine')),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srp_claims', to='killboard.killmail')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('killmail',), name='uniq_srp_claim_per_killmail')],
            },
        ),
    ]
