# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveAlliance',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('alliance_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EveCorporation',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('corporation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=10)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('ceo_id', models.BigIntegerField(blank=True, null=True)),
                ('is_home_corp', models.BooleanField(default=False)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='corporation.evealliance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
