# Generated by Django 5.2.15 on 2026-06-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveName',
            fields=[
                ('entity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
