# Generated by Django 5.2.15 on 2026-06-22 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0002_evename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpMember',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('corporation_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('ship_type_id', models.IntegerField(blank=True, null=True)),
                ('base_id', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('logon_date', models.DateTimeField(blank=True, null=True)),
                ('logoff_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
