# Generated by Django 5.2.15 on 2026-06-24 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0004_partneralliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpWalletDivision',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('division', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['division'],
            },
        ),
        migrations.CreateModel(
            name='CorpWalletJournalEntry',
            fields=[
                ('entry_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('division', models.IntegerField(db_index=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('ref_type', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('first_party_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('second_party_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
