# Generated by Django 5.2.15 on 2026-06-24 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0005_corpwalletdivision_corpwalletjournalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('contact_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance'), ('faction', 'Faction')], max_length=12)),
                ('standing', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-standing', 'name'],
            },
        ),
    ]
