# Generated by Django 5.2.15 on 2026-06-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.BigIntegerField(db_index=True)),
                ('moon_id', models.BigIntegerField(blank=True, null=True)),
                ('moon_name', models.CharField(blank=True, max_length=200)),
                ('structure_name', models.CharField(blank=True, max_length=200)),
                ('extraction_start', models.DateTimeField(blank=True, null=True)),
                ('chunk_arrival', models.DateTimeField(db_index=True)),
                ('natural_decay', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['chunk_arrival'],
                'unique_together': {('structure_id', 'chunk_arrival')},
            },
        ),
    ]
