# Generated by Django 5.2.16 on 2026-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0011_moonextraction_reminders_sent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='corpwalletjournalentry',
            index=models.Index(fields=['second_party_id', 'date'], name='cwje_secondparty_date_idx'),
        ),
    ]
