# Generated by Django 5.2.16 on 2026-07-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0012_corpwalletjournalentry_cwje_secondparty_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpwalletjournalentry',
            name='context_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpwalletjournalentry',
            name='context_id_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
