# Generated by Django 5.2.15 on 2026-06-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('deployment', 'Deployment'), ('war_prep', 'War preparation'), ('home_defence', 'Home defence'), ('structure_timer', 'Structure timer'), ('doctrine_rollout', 'Doctrine rollout'), ('industrial', 'Industrial campaign')], default='deployment', max_length=20)),
                ('target_at', models.DateTimeField(blank=True, null=True)),
                ('staging_location_id', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationDoctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.IntegerField(default=0, help_text='Pilots wanted on this doctrine (0 = any).')),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doctrines.doctrine')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctrines', to='operations.operation')),
            ],
            options={
                'unique_together': {('operation', 'doctrine')},
            },
        ),
    ]
