# Generated by Django 5.2.15 on 2026-06-24 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.BigIntegerField(blank=True, null=True)),
                ('character_name', models.CharField(blank=True, max_length=200)),
                ('confirmed', models.BooleanField(default=False, help_text='Verified by an FC / officer.')),
                ('added_by_officer', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='operations.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed', 'character_name'],
                'unique_together': {('operation', 'user')},
            },
        ),
    ]
