# Generated by Django 5.2.15 on 2026-06-24 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operationattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Structure name or label.', max_length=200)),
                ('system_name', models.CharField(blank=True, max_length=120)),
                ('system_id', models.BigIntegerField(blank=True, null=True)),
                ('structure_type', models.CharField(blank=True, help_text='Astrahus, Fortizar…', max_length=80)),
                ('timer_type', models.CharField(choices=[('armor', 'Armor'), ('hull', 'Hull / Final'), ('anchoring', 'Anchoring'), ('unanchoring', 'Unanchoring'), ('ihub', 'Sov · IHub'), ('tcu', 'Sov · TCU'), ('other', 'Other')], default='armor', max_length=12)),
                ('side', models.CharField(choices=[('friendly', 'Friendly (defend)'), ('hostile', 'Hostile (attack)'), ('neutral', 'Neutral')], default='hostile', max_length=10)),
                ('exits_at', models.DateTimeField(db_index=True, help_text='When the timer comes out (EVE/UTC).')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exits_at'],
            },
        ),
    ]
