# Generated by Django 5.2.16 on 2026-07-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrines', '0008_remove_doctrine_is_public_preview_and_more'),
        ('operations', '0012_op_template_target_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtemplateslot',
            name='doctrine_fit',
            field=models.ForeignKey(blank=True, help_text="The doctrine fit this slot is for, if it's an official doctrine ship.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='doctrines.doctrinefit'),
        ),
    ]
