from __future__ import annotations

from django.urls import path

from apps.killboard import console_signatures

from . import (
    console,
    console_access,
    console_capsuleer,
    console_combat,
    console_command_intel,
    console_comms_access,
    console_corporation,
    console_doctrine_xml,
    console_i18n,
    console_industry,
    console_mentorship,
    console_navigation,
    console_notifications,
    console_pingboard,
    console_planetary,
    console_raffle,
    console_readiness,
    console_recommendations,
    console_recovery,
    views,
)

app_name = "admin_audit"

urlpatterns = [
    path("audit/", views.audit_log_view, name="audit"),
    path("health/", views.health_view, name="health"),
    path("admin/capsuleer/", console_capsuleer.capsuleer_console, name="capsuleer_console"),
    path("admin/capsuleer/save/", console_capsuleer.capsuleer_save, name="capsuleer_save"),
    # Native admin console (no Django /admin needed).
    path("admin/", console.console_hub, name="console"),
    path("admin/features/", console.features, name="features"),
    path("admin/compliance/", console.compliance, name="compliance"),
    path("admin/retention/settings/", console.retention_settings, name="retention_settings"),
    # Localisation policy — which locales the language selector offers (Director).
    path("admin/i18n/", console_i18n.i18n_settings, name="i18n_settings"),
    # Access governance — partner alliances + friendly corporations (Director).
    path("admin/access/", console_access.access_governance, name="access_governance"),
    path("admin/access/partner-alliances/save/", console_access.partner_alliance_save,
         name="access_partner_alliance_create"),
    path("admin/access/partner-alliances/<int:alliance_id>/save/", console_access.partner_alliance_save,
         name="access_partner_alliance_update"),
    path("admin/access/partner-alliances/<int:alliance_id>/delete/", console_access.partner_alliance_delete,
         name="access_partner_alliance_delete"),
    path("admin/access/friendly-corps/save/", console_access.friendly_corp_save,
         name="access_friendly_corp_create"),
    path("admin/access/friendly-corps/<int:corporation_id>/save/", console_access.friendly_corp_save,
         name="access_friendly_corp_update"),
    path("admin/access/recovery/", console_recovery.character_recovery, name="character_recovery"),
    path("admin/access/recovery/detach/", console_recovery.character_detach, name="character_detach"),
    path("admin/access/friendly-corps/<int:corporation_id>/delete/", console_access.friendly_corp_delete,
         name="access_friendly_corp_delete"),
    path("admin/members/", console.members, name="members"),
    path("admin/members/<int:user_id>/", console.member_audit, name="member_audit"),
    path("admin/members/<int:user_id>/role/", console.set_role, name="set_role"),
    path("admin/role-requests/<int:pk>/decide/", console.role_request_decide, name="role_request_decide"),
    path("admin/doctrines/", console.doctrines_admin, name="doctrines"),
    path("admin/doctrines/settings/", console.doctrine_settings, name="doctrine_settings"),
    path("admin/industry/settings/", console_industry.industry_settings, name="industry_settings"),
    path("admin/corporation/structure-alerts/", console_corporation.structure_alert_settings,
         name="structure_alert_settings"),
    path("admin/recommendations/relay/", console_recommendations.relay_settings,
         name="relay_settings"),
    path("admin/recommendations/tuning/", console_recommendations.recommendations_tuning,
         name="recommendations_tuning"),
    path("admin/notifications/", console_notifications.notifications_console, name="notifications"),
    path("admin/pingboard/settings/", console_pingboard.pingboard_settings, name="pingboard_settings"),
    path("admin/pingboard/channels/", console_pingboard.pingboard_channels, name="pingboard_channels"),
    path("admin/pingboard/channels/new/", console_pingboard.pingboard_channel_new,
         name="pingboard_channel_new"),
    path("admin/pingboard/channels/save/", console_pingboard.pingboard_channel_save,
         name="pingboard_channel_save"),
    path("admin/pingboard/channels/<int:pk>/edit/", console_pingboard.pingboard_channel_edit,
         name="pingboard_channel_edit"),
    path("admin/pingboard/channels/<int:pk>/save/", console_pingboard.pingboard_channel_save,
         name="pingboard_channel_update"),
    path("admin/pingboard/automation/", console_pingboard.pingboard_automation, name="pingboard_automation"),
    path("admin/pingboard/templates/", console_pingboard.pingboard_templates, name="pingboard_templates"),
    path("admin/jump-planner/settings/", console_navigation.jump_planner_settings, name="jump_planner_settings"),
    # External comms access sync — Discord/Slack/Mumble roles from membership+RBAC (Director).
    path("admin/comms-access/", console_comms_access.comms_access_settings, name="comms_access_settings"),
    path("admin/comms-access/mappings/", console_comms_access.comms_access_mappings,
         name="comms_access_mappings"),
    path("admin/comms-access/mappings/save/", console_comms_access.comms_access_mapping_save,
         name="comms_access_mapping_create"),
    path("admin/comms-access/mappings/<int:pk>/save/", console_comms_access.comms_access_mapping_save,
         name="comms_access_mapping_update"),
    path("admin/comms-access/mappings/<int:pk>/delete/", console_comms_access.comms_access_mapping_delete,
         name="comms_access_mapping_delete"),
    path("admin/comms-access/status/", console_comms_access.comms_access_status,
         name="comms_access_status"),
    path("admin/doctrines/create/", console.doctrine_create, name="doctrine_create"),
    path("admin/doctrines/categories/create/", console.category_create, name="category_create"),
    path("admin/doctrines/<int:pk>/", console.doctrine_edit, name="doctrine_edit"),
    path("admin/doctrines/<int:pk>/update/", console.doctrine_update, name="doctrine_update"),
    path("admin/doctrines/<int:pk>/delete/", console.doctrine_delete, name="doctrine_delete"),
    path("admin/doctrines/<int:pk>/fit/add/", console.fit_add, name="fit_add"),
    path("admin/fits/<int:fit_id>/delete/", console.fit_delete, name="fit_delete"),
    path("admin/fits/<int:fit_id>/requirements/add/", console.requirement_add, name="requirement_add"),
    path("admin/requirements/<int:req_id>/delete/", console.requirement_delete, name="requirement_delete"),
    # Import fits into doctrines (Director).
    path("admin/doctrines/import-fits/", console.import_fits, name="import_fits"),
    path("admin/doctrines/import-fits/apply/", console.import_fits_apply, name="import_fits_apply"),
    # Import doctrines from an EVE-client XML export (Director).
    path("admin/doctrines/import-xml/", console_doctrine_xml.xml_import_start, name="doctrine_xml_import"),
    path("admin/doctrines/import-xml/settings/", console_doctrine_xml.xml_import_settings,
         name="doctrine_xml_settings"),
    path("admin/doctrines/import-xml/upload/", console_doctrine_xml.xml_import_upload,
         name="doctrine_xml_upload"),
    path("admin/doctrines/import-xml/<int:pk>/", console_doctrine_xml.xml_import_preview,
         name="doctrine_xml_preview"),
    path("admin/doctrines/import-xml/<int:pk>/commit/", console_doctrine_xml.xml_import_commit,
         name="doctrine_xml_commit"),
    path("admin/doctrines/import-xml/<int:pk>/result/", console_doctrine_xml.xml_import_result,
         name="doctrine_xml_result"),
    path("admin/doctrines/from-killmail/<int:killmail_id>/", console.doctrine_from_killmail,
         name="doctrine_from_killmail"),
    path("admin/content/", console.content, name="content"),
    path("admin/content/glossary/create/", console.glossary_create, name="glossary_create"),
    path("admin/content/glossary/<int:term_id>/delete/", console.glossary_delete, name="glossary_delete"),
    path("admin/content/milestones/create/", console.milestone_save, name="milestone_create"),
    path("admin/content/milestones/<int:pk>/update/", console.milestone_save, name="milestone_update"),
    path("admin/content/milestones/<int:pk>/delete/", console.milestone_delete, name="milestone_delete"),
    path("admin/settings/", console.settings_view, name="settings"),
    path("admin/contributions/", console.contribution_weights, name="contribution_weights"),
    # Readiness Platform configuration (Director-gated; doc 07). Phase 1: dimensions.
    path("admin/readiness/dimensions/", console_readiness.readiness_dimensions,
         name="readiness_dimensions"),
    path("admin/readiness/wizard/", console_readiness.readiness_wizard, name="readiness_wizard"),
    path("admin/readiness/mandatory-ships/", console_readiness.readiness_mandatory_ships,
         name="readiness_mandatory_ships"),
    path("admin/readiness/mandatory-ships/create/", console_readiness.readiness_mandatory_ship_save,
         name="readiness_mandatory_ship_create"),
    path("admin/readiness/mandatory-ships/<int:pk>/update/", console_readiness.readiness_mandatory_ship_save,
         name="readiness_mandatory_ship_update"),
    path("admin/readiness/mandatory-ships/<int:pk>/delete/", console_readiness.readiness_mandatory_ship_delete,
         name="readiness_mandatory_ship_delete"),
    path("admin/readiness/strategic-roles/", console_readiness.readiness_strategic_roles,
         name="readiness_strategic_roles"),
    path("admin/readiness/strategic-roles/create/", console_readiness.readiness_strategic_role_save,
         name="readiness_strategic_role_create"),
    path("admin/readiness/strategic-roles/<int:pk>/update/", console_readiness.readiness_strategic_role_save,
         name="readiness_strategic_role_update"),
    path("admin/readiness/strategic-roles/<int:pk>/delete/", console_readiness.readiness_strategic_role_delete,
         name="readiness_strategic_role_delete"),
    path("admin/readiness/finance/", console_readiness.readiness_finance,
         name="readiness_finance"),
    path("admin/readiness/srp/", console_readiness.readiness_srp,
         name="readiness_srp"),
    path("admin/readiness/responsibilities/", console_readiness.readiness_responsibilities,
         name="readiness_responsibilities"),
    path("admin/readiness/alerts/", console_readiness.readiness_alerts,
         name="readiness_alerts"),
    path("admin/readiness/alerts/save/", console_readiness.readiness_alert_save,
         name="readiness_alert_save"),
    path("admin/readiness/alerts/<str:key>/delete/", console_readiness.readiness_alert_delete,
         name="readiness_alert_delete"),
    path("admin/readiness/alerts/sender/", console_readiness.readiness_mail_sender,
         name="readiness_mail_sender"),
    path("admin/readiness/doctrines/", console_readiness.readiness_doctrines,
         name="readiness_doctrines"),
    path("admin/readiness/kpis/", console_readiness.readiness_kpis,
         name="readiness_kpis"),
    path("admin/readiness/support/", console_readiness.readiness_support,
         name="readiness_support"),
    path("admin/readiness/support/search/", console_readiness.readiness_support_skill_search,
         name="readiness_support_skill_search"),
    path("admin/readiness/support/create/", console_readiness.readiness_support_skill_save,
         name="readiness_support_skill_create"),
    path("admin/readiness/support/<int:pk>/update/", console_readiness.readiness_support_skill_save,
         name="readiness_support_skill_update"),
    path("admin/readiness/support/<int:pk>/delete/", console_readiness.readiness_support_skill_delete,
         name="readiness_support_skill_delete"),
    path("admin/readiness/staging/", console_readiness.readiness_staging,
         name="readiness_staging"),
    path("admin/readiness/staging/clear/", console_readiness.readiness_staging_clear,
         name="readiness_staging_clear"),
    path("admin/readiness/<str:domain>/reset/", console_readiness.readiness_reset,
         name="readiness_reset"),
    # Command Intelligence configuration (Director-gated; doc 13).
    path("admin/command-intel/provider/", console_command_intel.command_intel_provider,
         name="command_intel_provider"),
    path("admin/command-intel/constraints/", console_command_intel.command_intel_constraints,
         name="command_intel_constraints"),
    path("admin/command-intel/classification/", console_command_intel.command_intel_classification,
         name="command_intel_classification"),
    path("admin/command-intel/auto-aar/", console_command_intel.command_intel_auto_aar,
         name="command_intel_auto_aar"),
    path("admin/command-intel/notifications/", console_command_intel.command_intel_notifications,
         name="command_intel_notifications"),
    path("admin/command-intel/autonomous/", console_command_intel.command_intel_autonomous,
         name="command_intel_autonomous"),
    path("admin/command-intel/<str:domain>/reset/", console_command_intel.command_intel_reset,
         name="command_intel_reset"),
    # Planetary Industry (officer overview; director for config).
    path("admin/planetary/", console_planetary.planetary_hub, name="planetary_hub"),
    path("admin/planetary/config/", console_planetary.planetary_config, name="planetary_config"),
    # Mentorship Program (officer day-to-day; director for config & rewards).
    path("admin/mentorship/", console_mentorship.mentorship_hub, name="mentorship_hub"),
    path("admin/mentorship/config/", console_mentorship.mentorship_config, name="mentorship_config"),
    path("admin/mentorship/cohorts/", console_mentorship.mentorship_cohorts, name="mentorship_cohorts"),
    path("admin/mentorship/cohorts/create/", console_mentorship.mentorship_cohort_save,
         name="mentorship_cohort_create"),
    path("admin/mentorship/cohorts/<int:pk>/update/", console_mentorship.mentorship_cohort_save,
         name="mentorship_cohort_update"),
    path("admin/mentorship/cohorts/<int:pk>/delete/", console_mentorship.mentorship_cohort_delete,
         name="mentorship_cohort_delete"),
    path("admin/mentorship/tracks/", console_mentorship.mentorship_tracks, name="mentorship_tracks"),
    path("admin/mentorship/tracks/create/", console_mentorship.mentorship_track_save,
         name="mentorship_track_create"),
    path("admin/mentorship/tracks/<int:pk>/update/", console_mentorship.mentorship_track_save,
         name="mentorship_track_update"),
    path("admin/mentorship/tracks/<int:pk>/delete/", console_mentorship.mentorship_track_delete,
         name="mentorship_track_delete"),
    path("admin/mentorship/tracks/<int:pk>/clone/", console_mentorship.mentorship_track_clone,
         name="mentorship_track_clone"),
    path("admin/mentorship/tracks/<int:pk>/build/", console_mentorship.mentorship_track_builder,
         name="mentorship_track_builder"),
    path("admin/mentorship/tasks/create/", console_mentorship.mentorship_task_save,
         name="mentorship_task_create"),
    path("admin/mentorship/tasks/<int:pk>/update/", console_mentorship.mentorship_task_save,
         name="mentorship_task_update"),
    path("admin/mentorship/tasks/<int:pk>/delete/", console_mentorship.mentorship_task_delete,
         name="mentorship_task_delete"),
    path("admin/mentorship/rewards-config/", console_mentorship.mentorship_reward_rules,
         name="mentorship_reward_rules"),
    path("admin/mentorship/rewards-config/create/", console_mentorship.mentorship_reward_rule_save,
         name="mentorship_reward_rule_create"),
    path("admin/mentorship/rewards-config/<int:pk>/update/", console_mentorship.mentorship_reward_rule_save,
         name="mentorship_reward_rule_update"),
    path("admin/mentorship/rewards-config/<int:pk>/delete/", console_mentorship.mentorship_reward_rule_delete,
         name="mentorship_reward_rule_delete"),
    path("admin/mentorship/badges/create/", console_mentorship.mentorship_badge_save,
         name="mentorship_badge_create"),
    path("admin/mentorship/badges/<int:pk>/update/", console_mentorship.mentorship_badge_save,
         name="mentorship_badge_update"),
    path("admin/mentorship/badges/<int:pk>/delete/", console_mentorship.mentorship_badge_delete,
         name="mentorship_badge_delete"),
    path("admin/mentorship/approvals/", console_mentorship.mentorship_approvals,
         name="mentorship_approvals"),
    path("admin/mentorship/approvals/mentor/<int:pk>/", console_mentorship.mentorship_mentor_decide,
         name="mentorship_mentor_decide"),
    path("admin/mentorship/approvals/mentee/<int:pk>/", console_mentorship.mentorship_mentee_decide,
         name="mentorship_mentee_decide"),
    path("admin/mentorship/approvals/pairing/<int:pk>/", console_mentorship.mentorship_pairing_decide,
         name="mentorship_pairing_decide"),
    path("admin/mentorship/matching/", console_mentorship.mentorship_matching, name="mentorship_matching"),
    path("admin/mentorship/matching/pair/", console_mentorship.mentorship_pair_create,
         name="mentorship_pair_create"),
    path("admin/mentorship/matching/auto-suggest/", console_mentorship.mentorship_auto_suggest,
         name="mentorship_auto_suggest"),
    path("admin/mentorship/rewards/", console_mentorship.mentorship_rewards, name="mentorship_rewards"),
    path("admin/mentorship/rewards/<int:pk>/decide/", console_mentorship.mentorship_reward_decide,
         name="mentorship_reward_decide"),
    path("admin/mentorship/rewards/<int:pk>/pay/", console_mentorship.mentorship_reward_pay,
         name="mentorship_reward_pay"),
    path("admin/mentorship/report/", console_mentorship.mentorship_report, name="mentorship_report"),
    path("admin/mentorship/flags/<int:pk>/resolve/", console_mentorship.mentorship_flag_resolve,
         name="mentorship_flag_resolve"),
    # Raffle Contests (officer day-to-day; director for draw execution + override).
    path("admin/raffle/", console_raffle.raffle_hub, name="raffle_hub"),
    path("admin/raffle/create/", console_raffle.raffle_create, name="raffle_create"),
    path("admin/raffle/config/", console_raffle.raffle_config, name="raffle_config"),
    path("admin/raffle/<int:pk>/", console_raffle.raffle_detail, name="raffle_detail"),
    path("admin/raffle/<int:pk>/edit/", console_raffle.raffle_edit, name="raffle_edit"),
    path("admin/raffle/<int:pk>/status/", console_raffle.raffle_status, name="raffle_status"),
    path("admin/raffle/<int:pk>/apply-template/", console_raffle.raffle_apply_template,
         name="raffle_apply_template"),
    path("admin/raffle/<int:pk>/prizes/", console_raffle.raffle_prizes, name="raffle_prizes"),
    path("admin/raffle/<int:pk>/prizes/save/", console_raffle.raffle_prize_save, name="raffle_prize_create"),
    path("admin/raffle/<int:pk>/prizes/<int:prize_id>/save/", console_raffle.raffle_prize_save,
         name="raffle_prize_update"),
    path("admin/raffle/<int:pk>/prizes/<int:prize_id>/delete/", console_raffle.raffle_prize_delete,
         name="raffle_prize_delete"),
    path("admin/raffle/<int:pk>/sources/", console_raffle.raffle_sources, name="raffle_sources"),
    path("admin/raffle/<int:pk>/sources/<int:source_pk>/save/", console_raffle.raffle_source_save,
         name="raffle_source_save"),
    path("admin/raffle/<int:pk>/grant/", console_raffle.raffle_grant, name="raffle_grant"),
    path("admin/raffle/<int:pk>/ledger/", console_raffle.raffle_ledger, name="raffle_ledger"),
    path("admin/raffle/<int:pk>/ledger/<int:entry_id>/action/", console_raffle.raffle_ledger_action,
         name="raffle_ledger_action"),
    path("admin/raffle/<int:pk>/ineligible/", console_raffle.raffle_ineligible, name="raffle_ineligible"),
    path("admin/raffle/<int:pk>/ineligible/outreach/",
         console_raffle.raffle_send_outreach, name="raffle_send_outreach"),
    path("admin/raffle/<int:pk>/draw/", console_raffle.raffle_draw, name="raffle_draw"),
    path("admin/raffle/<int:pk>/draw/action/", console_raffle.raffle_draw_action, name="raffle_draw_action"),
    path("admin/raffle/<int:pk>/draw/<int:result_id>/fulfil/", console_raffle.raffle_fulfil,
         name="raffle_fulfil"),
    path("admin/raffle/<int:pk>/stats/", console_raffle.raffle_stats, name="raffle_stats"),
    path("admin/raffle/<int:pk>/exclude/", console_raffle.raffle_exclude, name="raffle_exclude"),
    path("admin/raffle/<int:pk>/exclude/<int:exclusion_id>/remove/", console_raffle.raffle_exclude_remove,
         name="raffle_exclude_remove"),
    path("admin/raffle/<int:pk>/flags/", console_raffle.raffle_flags, name="raffle_flags"),
    path("admin/raffle/<int:pk>/flags/<int:flag_id>/resolve/", console_raffle.raffle_flag_resolve,
         name="raffle_flag_resolve"),
    path("admin/raffle/<int:pk>/preview/", console_raffle.raffle_preview, name="raffle_preview"),
    # Combat Rank ladder config (Director) + reward-event triage (Officer).
    path("admin/combat-ranks/", console_combat.combat_ranks, name="combat_ranks"),
    path("admin/combat-ranks/new/", console_combat.combat_rank_edit, name="combat_rank_new"),
    path("admin/combat-ranks/save/", console_combat.combat_rank_save, name="combat_rank_create"),
    path("admin/combat-ranks/settings/", console_combat.combat_reward_settings,
         name="combat_reward_settings"),
    path("admin/combat-ranks/newbro/", console_combat.newbro_settings, name="newbro_settings"),
    path("admin/combat-ranks/rewards/enable/", console_combat.combat_reward_enable,
         name="combat_reward_enable"),
    path("admin/combat-ranks/rewards/disable/", console_combat.combat_reward_disable,
         name="combat_reward_disable"),
    path("admin/combat-ranks/rewards/rebaseline/", console_combat.combat_reward_rebaseline,
         name="combat_reward_rebaseline"),
    path("admin/combat-ranks/<int:pk>/edit/", console_combat.combat_rank_edit, name="combat_rank_edit"),
    path("admin/combat-ranks/<int:pk>/save/", console_combat.combat_rank_save, name="combat_rank_update"),
    path("admin/combat-ranks/<int:pk>/delete/", console_combat.combat_rank_delete,
         name="combat_rank_delete"),
    path("admin/combat-rewards/", console_combat.combat_rewards, name="combat_rewards"),
    path("admin/combat-rewards/scan/", console_combat.combat_reward_scan, name="combat_reward_scan"),
    path("admin/combat-rewards/<int:pk>/action/", console_combat.combat_reward_action,
         name="combat_reward_action"),
    # Combat Signatures admin (Officer dashboard/search + moderation; Director settings/curation).
    path("admin/signatures/", console_signatures.signatures_dashboard, name="signatures_dashboard"),
    path("admin/signatures/settings/", console_signatures.signature_settings,
         name="signature_settings"),
    path("admin/signatures/backgrounds/", console_signatures.signature_backgrounds,
         name="signature_backgrounds"),
    path("admin/signatures/search/", console_signatures.signature_search, name="signature_search"),
    path("admin/signatures/<int:pk>/<str:action>/", console_signatures.signature_admin_action,
         name="signature_admin_action"),
    path("admin/maintenance/<str:action>/", console.run_maintenance, name="run_maintenance"),
]
