# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0002_initial'),
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('doctrine', 'Doctrine'), ('newbro', 'Newbro'), ('custom', 'Custom')], default='custom', max_length=12)),
                ('corp_priority_weighted', models.BooleanField(default=False)),
                ('estimated_total_seconds', models.BigIntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_plans', to='sso.evecharacter')),
                ('target_doctrine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_plans', to='doctrines.doctrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('skill_type_id', models.IntegerField()),
                ('target_level', models.PositiveSmallIntegerField()),
                ('estimated_seconds', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('done', 'Done')], default='pending', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skills.skillplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
