# Generated by Django 5.2.16 on 2026-07-11 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0004_evecharacter_director_checked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('motivation', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('template', 'Template'), ('doctrine', 'Doctrine'), ('ship', 'Ship'), ('activity', 'Activity'), ('custom', 'Custom')], max_length=12)),
                ('template_key', models.SlugField(blank=True, default='', max_length=64)),
                ('doctrine_id', models.BigIntegerField(blank=True, null=True)),
                ('ship_type_id', models.BigIntegerField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('considering', 'Considering'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('archived', 'Archived')], default='considering', max_length=12)),
                ('priority', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('someday', 'Someday')], default='secondary', max_length=10)),
                ('pace', models.CharField(choices=[('inherit', 'Inherit from profile'), ('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('accelerated', 'Accelerated')], default='inherit', max_length=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('budget_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('mentor', 'Mentor'), ('officers', 'Officers'), ('aggregate_only', 'Aggregate only')], default='private', max_length=16)),
                ('corp_alignment_optin', models.BooleanField(default=False)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('skill_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_reason', models.CharField(blank=True, default='', max_length=200)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_goals', to='sso.evecharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CareerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('skill_target', 'Skill target'), ('doctrine_ready', 'Doctrine ready'), ('ship_owned', 'Ship owned'), ('contribution', 'Contribution'), ('combat_first', 'Combat first'), ('practical', 'Practical'), ('manual', 'Manual')], max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=8)),
                ('verification', models.CharField(choices=[('auto', 'Automatic'), ('self', 'Self'), ('mentor', 'Mentor'), ('officer', 'Officer')], default='auto', max_length=8)),
                ('evidence_note', models.TextField(blank=True)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('check_state', models.CharField(choices=[('ok', 'OK'), ('unknown', 'Unknown'), ('stale', 'Stale')], default='unknown', max_length=8)),
                ('data_source', models.CharField(blank=True, default='', max_length=120)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='capsuleer.careergoal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CareerActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('source', models.CharField(choices=[('pilot', 'Pilot'), ('template', 'Template'), ('suggestion', 'Suggestion')], default='pilot', max_length=12)),
                ('est_cost_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('task_id', models.BigIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='capsuleer.careergoal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_steps', to='capsuleer.careermilestone')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_activities', models.JSONField(blank=True, default=list)),
                ('curious_activities', models.JSONField(blank=True, default=list)),
                ('avoided_activities', models.JSONField(blank=True, default=list)),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('play_windows', models.CharField(blank=True, default='', max_length=200)),
                ('pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('accelerated', 'Accelerated')], default='balanced', max_length=12)),
                ('monthly_budget_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('corp_alignment', models.CharField(choices=[('personal_only', 'Personal only'), ('mostly_personal', 'Mostly personal'), ('balanced', 'Balanced'), ('corp_forward', 'Corp forward'), ('show_all', 'Show all')], default='balanced', max_length=16)),
                ('mentor_interest', models.BooleanField(default=False)),
                ('default_visibility', models.CharField(choices=[('private', 'Private'), ('mentor', 'Mentor'), ('officers', 'Officers'), ('aggregate_only', 'Aggregate only')], default='private', max_length=16)),
                ('suggestion_muted_kinds', models.JSONField(blank=True, default=list)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('combat_line', 'Combat line (DPS)'), ('combat_support', 'Combat support (logi/ewar)'), ('tackle_scout', 'Tackle & scouting'), ('fleet_command', 'Fleet command'), ('black_ops', 'Black ops'), ('capitals', 'Capitals'), ('mining', 'Mining'), ('industry', 'Industry'), ('planetary', 'Planetary industry'), ('hauling', 'Hauling'), ('exploration', 'Exploration'), ('wormholes', 'Wormholes'), ('trade', 'Trade'), ('mentoring', 'Mentoring'), ('corp_service', 'Corp service')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('est_hours_note', models.CharField(blank=True, default='', max_length=120)),
                ('cost_note', models.CharField(blank=True, default='', max_length=120)),
                ('solo_group', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('mixed', 'Mixed')], default='mixed', max_length=8)),
                ('risk_note', models.CharField(blank=True, default='', max_length=200)),
                ('income_note', models.CharField(blank=True, default='', max_length=200)),
                ('newbro_friendly', models.BooleanField(default=False)),
                ('structure', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('corp', 'Corp')], default='corp', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('doctrine_id', models.BigIntegerField(blank=True, null=True)),
                ('advanced_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_paths', to='capsuleer.careertemplate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='careergoal',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='capsuleer.careertemplate'),
        ),
        migrations.CreateModel(
            name='GoalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='capsuleer.careergoal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PathSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('near_qualification', 'Near qualification'), ('event_match', 'Event match'), ('mentor_available', 'Mentor available'), ('stalled_goal', 'Stalled goal'), ('blocked_prereq', 'Blocked prerequisite'), ('ship_available', 'Ship available'), ('campaign_opportunity', 'Campaign opportunity'), ('review_due', 'Review due')], max_length=24)),
                ('title', models.CharField(max_length=140)),
                ('reason', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('corp_driven', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('deferred', 'Deferred'), ('not_interested', 'Not interested'), ('incorrect', 'Incorrect')], default='open', max_length=16)),
                ('dedupe_key', models.CharField(max_length=180)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='capsuleer.careergoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('percent', models.PositiveSmallIntegerField()),
                ('milestones_done', models.PositiveSmallIntegerField()),
                ('milestones_total', models.PositiveSmallIntegerField()),
                ('sp_remaining', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='capsuleer.careergoal')),
            ],
            options={
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='careermilestone',
            index=models.Index(fields=['status', 'verification'], name='capsuleer_c_status_6d15a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='careermilestone',
            constraint=models.UniqueConstraint(fields=('goal', 'order'), name='uniq_cp_milestone_order'),
        ),
        migrations.AddIndex(
            model_name='careeractionstep',
            index=models.Index(fields=['goal', 'status'], name='capsuleer_c_goal_id_f4a5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='careertemplate',
            index=models.Index(fields=['category', 'is_active'], name='capsuleer_c_categor_04fdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='careertemplate',
            index=models.Index(fields=['source', 'is_active'], name='capsuleer_c_source_f49990_idx'),
        ),
        migrations.AddConstraint(
            model_name='careertemplate',
            constraint=models.UniqueConstraint(fields=('key',), name='uniq_cp_template_key'),
        ),
        migrations.AddConstraint(
            model_name='careertemplate',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 3)), name='ck_cp_template_difficulty'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['user', 'status'], name='capsuleer_c_user_id_08ec27_idx'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['status', 'visibility'], name='capsuleer_c_status_e0d657_idx'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['status', 'review_due_at'], name='capsuleer_c_status_3c7fb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='careergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False), ('status__in', ['considering', 'active', 'paused'])), fields=('user', 'template_key'), name='uniq_cp_goal_user_template_active'),
        ),
        migrations.AddConstraint(
            model_name='careergoal',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__lte', 100)), name='ck_cp_goal_progress'),
        ),
        migrations.AddIndex(
            model_name='goalactivity',
            index=models.Index(fields=['goal', 'created_at'], name='capsuleer_g_goal_id_97f242_idx'),
        ),
        migrations.AddIndex(
            model_name='pathsuggestion',
            index=models.Index(fields=['user', 'status'], name='capsuleer_p_user_id_989467_idx'),
        ),
        migrations.AddIndex(
            model_name='pathsuggestion',
            index=models.Index(fields=['status', 'expires_at'], name='capsuleer_p_status_3b6c7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathsuggestion',
            constraint=models.UniqueConstraint(fields=('dedupe_key',), name='uniq_cp_suggestion_dedupe'),
        ),
        migrations.AddIndex(
            model_name='progresssnapshot',
            index=models.Index(fields=['goal', 'taken_at'], name='capsuleer_p_goal_id_69a158_idx'),
        ),
        migrations.AddConstraint(
            model_name='progresssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('percent__lte', 100)), name='ck_cp_snapshot_percent'),
        ),
    ]
