# Generated by Django 5.2.16 on 2026-07-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleer', '0002_seed_builtin_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeractionstep',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
