# Generated by Django 5.2.16 on 2026-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleer', '0003_careeractionstep_snoozed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermilestone',
            name='structural_block',
            field=models.BooleanField(default=False),
        ),
    ]
