# Generated by Django 5.2.16 on 2026-07-14 09:00
#
# Additive, metadata-only: one nullable-by-default CharField carrying the built-in template
# milestone a title was copied from (the i18n translate-until-edited seam). No rows are touched.
#
# ``db_default=""`` is load-bearing: without it Django emits ``ADD COLUMN … DEFAULT '' NOT NULL``
# followed by ``ALTER COLUMN … DROP DEFAULT``, leaving a NOT NULL column with no database default —
# so any INSERT from older code (a rollback, a mid-deploy web pod) that does not name the column
# fails. With ``db_default`` the default survives in the database and the column is safe both ways.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleer', '0004_careermilestone_structural_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermilestone',
            name='source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=160),
        ),
    ]
