# Generated by Django 5.2.16 on 2026-07-14 12:00
#
# The persisted-prose i18n seam ("Seam B", apps/capsuleer/messages.py). Additive, metadata-only:
# six new columns, no row is read or written, no data migration.
#
# ``CareerMilestone.data_source`` and ``PathSuggestion.title`` / ``.reason`` are prose assembled by
# a Celery worker (the verification sweep and the daily suggestion beat), which has no reader and no
# locale — so every row is frozen in the writer's English and a ``gettext_lazy`` at the write site
# would be coerced to ``str`` on ``.save()`` and translate nothing. The new ``*_key`` / ``*_params``
# columns record the message scaffold and its raw params alongside the prose, so the READER's locale
# decides the language at render time. The prose columns stay: they are the English fallback and the
# audit record, and they are what legacy rows (no key) keep rendering. Nothing is backfilled.
#
# ``db_default`` is load-bearing on every one of them. Without it Django emits
#   ADD COLUMN … DEFAULT x NOT NULL
#   ALTER COLUMN … DROP DEFAULT
# leaving a NOT NULL column with NO database default, so any INSERT from older code during a
# rollback (or a mid-deploy web pod) that does not name the column fails with a not-null violation —
# reads keep working, so it looks fine and breaks silently. This exact trap bit the production i18n
# deploy. Verified with ``manage.py sqlmigrate capsuleer 0006``: the DDL is six plain
# ``ADD COLUMN … DEFAULT … NOT NULL`` statements and there is NO ``DROP DEFAULT``.
#
# ``db_default=dict`` is not a thing for a JSONField (Django needs a database expression, not a
# Python callable), hence ``Value({}, JSONField())`` — the literal empty JSON object.
# (``Value("{}", …)`` would store the JSON *string* "{}", which reads back as a str, not a dict.)

from django.db import migrations, models
from django.db.models import Value


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleer', '0005_careermilestone_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermilestone',
            name='data_source_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='careermilestone',
            name='data_source_params',
            field=models.JSONField(
                blank=True, db_default=Value({}, models.JSONField()), default=dict
            ),
        ),
        migrations.AddField(
            model_name='pathsuggestion',
            name='title_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pathsuggestion',
            name='title_params',
            field=models.JSONField(
                blank=True, db_default=Value({}, models.JSONField()), default=dict
            ),
        ),
        migrations.AddField(
            model_name='pathsuggestion',
            name='reason_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pathsuggestion',
            name='reason_params',
            field=models.JSONField(
                blank=True, db_default=Value({}, models.JSONField()), default=dict
            ),
        ),
    ]
