# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('owner_character_id', models.BigIntegerField(blank=True, null=True)),
                ('is_corp', models.BooleanField(default=False)),
                ('me', models.PositiveSmallIntegerField(default=0)),
                ('te', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetaryIndustryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('character_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('planet_id', models.BigIntegerField(blank=True, null=True)),
                ('target_product_type_id', models.IntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=4)),
                ('chain', models.JSONField(blank=True, default=dict)),
                ('buy_vs_extract', models.JSONField(blank=True, default=dict)),
                ('manual_mode', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective_type', models.CharField(choices=[('build', 'Build'), ('stock', 'Stock'), ('ammo', 'Ammo'), ('contracts', 'Contracts'), ('custom', 'Custom')], default='build', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_doctrine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='doctrines.doctrine')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='market.marketlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('quantity', models.BigIntegerField(default=1)),
                ('build_or_buy', models.CharField(choices=[('build', 'Build'), ('buy', 'Buy'), ('undecided', 'Undecided')], default='undecided', max_length=10)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('me', models.PositiveSmallIntegerField(default=0)),
                ('te', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='industry.industryproject')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('quantity_required', models.BigIntegerField(default=0)),
                ('quantity_available', models.BigIntegerField(default=0)),
                ('quantity_to_acquire', models.BigIntegerField(default=0)),
                ('acquire_method', models.CharField(choices=[('build', 'Build'), ('buy', 'Buy'), ('react', 'React'), ('invent', 'Invent'), ('pi', 'PI'), ('haul', 'Haul'), ('contract', 'Contract')], default='buy', max_length=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='industry.industryprojectitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('fmt', models.CharField(default='multibuy', max_length=12)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='industry.industryproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('quantity', models.BigIntegerField(default=1)),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='industry.shoppinglist')),
            ],
        ),
    ]
