# Generated by Django 5.2.15 on 2026-06-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryprojectitem',
            name='max_depth',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='strategy',
            field=models.CharField(choices=[('build_vs_buy', 'Build when cheaper'), ('build_to_minerals', 'Build all the way down')], default='build_vs_buy', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('activity', models.CharField(default='manufacturing', max_length=32)),
                ('runs', models.IntegerField(default=1)),
                ('output_quantity', models.BigIntegerField(default=1)),
                ('produced_quantity', models.BigIntegerField(default=0)),
                ('required_quantity', models.BigIntegerField(default=0)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='industry.industryprojectitem')),
            ],
            options={
                'ordering': ['-depth', 'type_id'],
            },
        ),
    ]
