# Generated by Django 5.2.15 on 2026-07-03 12:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_industryprojectitem_max_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryEconomyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('erp_redirects', models.BooleanField(default=True)),
                ('default_market_hub_system_id', models.BigIntegerField(default=30000142)),
                ('default_system_cost_index', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=6)),
                ('default_facility_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0025'), max_digits=6)),
                ('default_sales_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0450'), max_digits=6)),
                ('default_broker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0150'), max_digits=6)),
                ('corp_buyback_modifier', models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=5)),
                ('hauling_cost_per_m3', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('default_visibility', models.CharField(choices=[('private', 'Private (owner + leadership)'), ('leadership', 'Leadership only'), ('corp', 'Whole corporation')], default='corp', max_length=12)),
                ('allow_pilot_plans', models.BooleanField(default=True)),
                ('stale_price_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='industryproject',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='broker_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='facility_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='sales_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('doctrine_supply', 'Doctrine supply gap'), ('store_order', 'Corp Store order'), ('store_gap', 'Corp Store stock gap'), ('esi_job', 'Imported ESI job')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='store_order_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='system_cost_index',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (owner + leadership)'), ('leadership', 'Leadership only'), ('corp', 'Whole corporation')], default='corp', max_length=12),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='blueprint_source',
            field=models.CharField(choices=[('own_bpo', 'I own a BPO'), ('own_bpc', 'I own a BPC'), ('buy', 'Buy the blueprint'), ('invent', 'Invent a T2 BPC'), ('corp', 'Corporation blueprint'), ('unknown', 'Not sure — guide me')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='invent_decryptor_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='invent_encryption',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='invent_science_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='invent_science_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industryprojectitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
