# Generated by Django 5.2.16 on 2026-07-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_consume_materials_on_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blueprint',
        ),
    ]
