# Generated by Django 5.2.16 on 2026-07-16 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_buildjob_esi_job_id'),
        ('industry', '0006_delete_blueprint'),
        ('market', '0004_marketwatch'),
        ('stockpile', '0005_release_stranded_reservations'),
        ('tasks', '0003_task_tasks_task_related_456f28_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MrpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('consolidation_window_days', models.PositiveIntegerField(db_default=28, default=28, help_text='Dated demand beyond this many days ahead is excluded from the plan and listed separately.')),
                ('buy_lead_days', models.PositiveIntegerField(db_default=3, default=3, help_text='Assumed days to buy an item at the price-reference hub.')),
                ('import_lead_days', models.PositiveIntegerField(db_default=5, default=5, help_text='Assumed days to buy at Jita and freight to the destination.')),
                ('include_ready_jobs', models.BooleanField(db_default=True, default=True, help_text='Count finished-but-undelivered ESI jobs (status "ready") as incoming supply.')),
                ('auto_run_enabled', models.BooleanField(db_default=False, default=False, help_text='Run the planning job automatically on its nightly schedule. Off: officers run it manually from the Material Plan page.')),
                ('default_me', models.PositiveSmallIntegerField(db_default=0, default=0, help_text='Material-efficiency assumed for every build level of the explosion.')),
                ('max_depth', models.PositiveSmallIntegerField(db_default=8, default=8, help_text='Deepest BOM level the explosion will recurse to.')),
            ],
            options={
                'verbose_name': 'MRP config',
                'verbose_name_plural': 'MRP configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='industryproject',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('doctrine_supply', 'Doctrine supply gap'), ('store_order', 'Corp Store order'), ('store_gap', 'Corp Store stock gap'), ('esi_job', 'Imported ESI job'), ('mrp', 'MRP planning run')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='MrpRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_default='running', db_index=True, default='running', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict)),
                ('inputs_digest', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_default='open', db_index=True, default='open', max_length=12)),
                ('net_quantity', models.BigIntegerField(db_default=0, default=0)),
                ('gross_quantity', models.BigIntegerField(db_default=0, default=0)),
                ('available_quantity', models.BigIntegerField(db_default=0, default=0)),
                ('incoming_quantity', models.BigIntegerField(db_default=0, default=0)),
                ('required_by', models.DateTimeField(blank=True, null=True)),
                ('suggestion', models.CharField(blank=True, db_default='', default='', max_length=8)),
                ('feasible_at', models.DateTimeField(blank=True, null=True)),
                ('feasible_source', models.CharField(blank=True, db_default='', default='', max_length=12)),
                ('depth', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('sources', models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list)),
                ('incoming_refs', models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list)),
                ('diverged', models.BooleanField(db_default=False, default=False)),
                ('build_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erp.buildjob')),
                ('hauling_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stockpile.haulingtask')),
                ('industry_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='industry.industryproject')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='industry.mrprun')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.marketlocation')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task')),
            ],
            options={
                'ordering': ['depth', 'type_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mrprun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='uniq_running_mrp_run'),
        ),
        migrations.AddIndex(
            model_name='netrequirement',
            index=models.Index(fields=['status', 'suggestion'], name='industry_ne_status_4dac96_idx'),
        ),
        migrations.AddIndex(
            model_name='netrequirement',
            index=models.Index(fields=['status', 'depth'], name='industry_ne_status_7c8117_idx'),
        ),
        migrations.AddConstraint(
            model_name='netrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'in_progress'))), fields=('type_id', 'location'), name='uniq_live_netrequirement_per_type_location', nulls_distinct=False),
        ),
    ]
