# Generated by Django 5.2.16 on 2026-07-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_mrpconfig_alter_industryproject_source_mrprun_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netrequirement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorder'),
        ),
    ]
