# Generated by Django 5.2.16 on 2026-07-17 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_netrequirement_purchase_order'),
        ('sso', '0006_backfill_director_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrpconfig',
            name='capacity_enabled',
            field=models.BooleanField(db_default=False, default=False, help_text='Hold build dates to committed manufacturing capacity (slots, skills, blueprints, facilities) and name the bottleneck. Off: dates assume unlimited industry slots (the P3 behaviour).'),
        ),
        migrations.AddField(
            model_name='mrpconfig',
            name='capacity_skill_stale_days',
            field=models.PositiveSmallIntegerField(db_default=14, default=14, help_text='A pilot\'s slots become "unknown" (excluded from measured capacity) when their skills snapshot is older than this. Unknown is never treated as zero.'),
        ),
        migrations.AddField(
            model_name='netrequirement',
            name='bottleneck_code',
            field=models.CharField(blank=True, db_default='', default='', max_length=12),
        ),
        migrations.CreateModel(
            name='ProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('activity_class', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('reaction', 'Reaction'), ('science', 'Science')], max_length=13)),
                ('slots_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manual_slots_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weekly_output', models.PositiveIntegerField(blank=True, help_text='Cap on finished units/week the scheduler will book onto this pilot — a crude cadence governor counted across all types, not a per-job ceiling. Blank means uncapped.', null=True)),
                ('unavailable_from', models.DateTimeField(blank=True, null=True)),
                ('unavailable_until', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(db_default=False, default=False, help_text="Don't schedule new work onto this pilot.")),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_resources', to='sso.evecharacter')),
            ],
            options={
                'ordering': ['character_id', 'activity_class'],
                'indexes': [models.Index(fields=['activity_class'], name='industry_pr_activit_c313eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('character', 'activity_class'), name='uniq_resource_per_char_activity')],
            },
        ),
    ]
