# Generated by Django 5.2.16 on 2026-07-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_mrpconfig_capacity_enabled_and_more'),
        ('logistics', '0009_freightconfig_freightbatch_freightbatchline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netrequirement',
            name='freight_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.freightbatchline'),
        ),
    ]
