# Generated by Django 5.2.15 on 2026-06-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctrines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance'), ('ship', 'Ship'), ('system', 'System')], max_length=12)),
                ('entity_id', models.BigIntegerField()),
                ('window', models.CharField(default='all', max_length=8)),
                ('kills', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('isk_destroyed', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('isk_lost', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('points', models.IntegerField(default=0)),
                ('solo_kills', models.IntegerField(default=0)),
                ('danger_ratio', models.FloatField(default=0.0)),
                ('gang_ratio', models.FloatField(default=0.0)),
                ('avg_gang_size', models.FloatField(default=0.0)),
                ('top_ships', models.JSONField(blank=True, default=list)),
                ('top_systems', models.JSONField(blank=True, default=list)),
            ],
            options={
                'unique_together': {('entity_type', 'entity_id', 'window')},
            },
        ),
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('source', models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('killmail_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('killmail_hash', models.CharField(max_length=64)),
                ('killmail_time', models.DateTimeField(db_index=True)),
                ('solar_system_id', models.IntegerField(db_index=True)),
                ('region_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('moon_id', models.IntegerField(blank=True, null=True)),
                ('war_id', models.IntegerField(blank=True, null=True)),
                ('victim_character_id', models.BigIntegerField(blank=True, null=True)),
                ('victim_corporation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('victim_alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('victim_faction_id', models.IntegerField(blank=True, null=True)),
                ('victim_ship_type_id', models.IntegerField()),
                ('damage_taken', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('destroyed_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dropped_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fitted_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('points', models.IntegerField(default=1)),
                ('is_solo', models.BooleanField(default=False)),
                ('is_npc', models.BooleanField(default=False)),
                ('is_awox', models.BooleanField(default=False)),
                ('sec_band', models.CharField(choices=[('highsec', 'Highsec'), ('lowsec', 'Lowsec'), ('nullsec', 'Nullsec'), ('wh', 'Wormhole'), ('abyssal', 'Abyssal'), ('pochven', 'Pochven'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('involves_home_corp', models.BooleanField(db_index=True, default=False)),
                ('home_corp_role', models.CharField(choices=[('victim', 'Victim'), ('attacker', 'Attacker'), ('none', 'None')], default='none', max_length=10)),
                ('valuation_version', models.IntegerField(default=1)),
                ('points_version', models.IntegerField(default=1)),
                ('doctrine_fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_kills', to='doctrines.doctrinefit')),
            ],
            options={
                'ordering': ['-killmail_time'],
            },
        ),
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('system_ids', models.JSONField(default=list)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sides', models.JSONField(default=dict)),
                ('isk_destroyed_by_side', models.JSONField(default=dict)),
                ('ship_breakdown', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('killmails', models.ManyToManyField(blank=True, related_name='battle_reports', to='killboard.killmail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KillmailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('parent_idx', models.IntegerField(blank=True, null=True)),
                ('item_type_id', models.IntegerField()),
                ('flag', models.IntegerField(default=0)),
                ('singleton', models.IntegerField(default=0)),
                ('quantity_dropped', models.BigIntegerField(blank=True, null=True)),
                ('quantity_destroyed', models.BigIntegerField(blank=True, null=True)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='killboard.killmail')),
            ],
            options={
                'unique_together': {('killmail', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='KillmailParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('victim', 'Victim'), ('attacker', 'Attacker')], max_length=8)),
                ('seq', models.IntegerField(default=0)),
                ('character_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('corporation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('faction_id', models.IntegerField(blank=True, null=True)),
                ('ship_type_id', models.IntegerField(blank=True, null=True)),
                ('weapon_type_id', models.IntegerField(blank=True, null=True)),
                ('damage_done', models.IntegerField(default=0)),
                ('final_blow', models.BooleanField(default=False)),
                ('security_status', models.FloatField(blank=True, null=True)),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='killboard.killmail')),
            ],
            options={
                'unique_together': {('killmail', 'role', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance')], max_length=12)),
                ('entity_id', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='killboard.watchlist')),
            ],
            options={
                'unique_together': {('watchlist', 'entity_type', 'entity_id')},
            },
        ),
    ]
