# Generated by Django 5.2.16 on 2026-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0013_watchlist_activity_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestSourceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_count', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KillstreamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='Optional real-time fallback feed (zKillboard R2Z2). The primary sources (ESI Director feed, the zKill query poll and EVE Ref archives) always run; turn this on only for lower-latency ingest or as a supplementary source.')),
                ('last_sequence', models.BigIntegerField(blank=True, help_text='The last R2Z2 sequence number consumed — the resumable cursor.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_scanned', models.IntegerField(default=0)),
                ('last_run_ingested', models.IntegerField(default=0)),
                ('ingested_total', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='combatmetric',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='killmail',
            name='source',
            field=models.CharField(choices=[('esi_char', 'ESI (character token)'), ('esi_corp', 'ESI (corporation/Director token)'), ('manual', 'Manual entry'), ('zkill', 'zKillboard'), ('killstream', 'zKillboard R2Z2 (realtime fallback)'), ('everef', 'EVE Ref'), ('sde', 'Static Data Export'), ('estimated', 'Estimated'), ('system', 'System')], default='manual', max_length=16),
        ),
    ]
