# Generated by Django 5.2.16 on 2026-07-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0014_ingestsourcehealth_killstreamstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KillmailComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('author_character_id', models.BigIntegerField(blank=True, null=True)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='killboard.killmail')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
