# Generated by Django 5.2.16 on 2026-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0015_killmailcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='killfeedconfig',
            name='exclude_awox',
            field=models.BooleanField(default=False, help_text="Skip awox kills (a corp member on the victim's own corp)."),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='exclude_npc',
            field=models.BooleanField(default=False, help_text='Skip kills with no player attackers (NPC/ratting deaths).'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='losses_deviated_only',
            field=models.BooleanField(default=False, help_text='For losses, post only those that deviated from doctrine.'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='max_attackers',
            field=models.PositiveIntegerField(default=0, help_text='Require at most this many attackers (0 = off).'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='max_jumps_from_staging',
            field=models.PositiveIntegerField(default=0, help_text='Only within this many jumps of the staging system (0 = off).'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='min_attackers',
            field=models.PositiveIntegerField(default=0, help_text='Require at least this many attackers (0 = off).'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='require_solo',
            field=models.BooleanField(default=False, help_text='Post solo kills only.'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='sec_bands',
            field=models.JSONField(blank=True, default=list, help_text='Only these security bands (empty = all).'),
        ),
        migrations.AddField(
            model_name='killfeedconfig',
            name='ship_classes',
            field=models.JSONField(blank=True, default=list, help_text='Only these victim ship classes (empty = all).'),
        ),
    ]
