# Generated by Django 5.2.16 on 2026-07-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0017_killboardapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillboardStreamEvent',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('killmail_hash', models.CharField(max_length=64)),
                ('kill_time', models.DateTimeField()),
                ('home_role', models.CharField(choices=[('victim', 'Victim'), ('attacker', 'Attacker'), ('none', 'None')], max_length=10)),
                ('sec_band', models.CharField(choices=[('highsec', 'Highsec'), ('lowsec', 'Lowsec'), ('nullsec', 'Nullsec'), ('wh', 'Wormhole'), ('abyssal', 'Abyssal'), ('pochven', 'Pochven'), ('unknown', 'Unknown')], max_length=10)),
                ('system_id', models.IntegerField()),
                ('ship_class', models.CharField(blank=True, max_length=32)),
                ('victim_ship_type_id', models.IntegerField()),
                ('victim_character_id', models.BigIntegerField(blank=True, null=True)),
                ('victim_corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_solo', models.BooleanField(default=False)),
                ('is_npc', models.BooleanField(default=False)),
                ('is_awox', models.BooleanField(default=False)),
                ('needs_srp', models.BooleanField(default=False)),
                ('deviated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('killmail', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='killboard.killmail')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
