# Generated by Django 5.2.16 on 2026-07-22 16:00

import apps.killboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0025_killboardhistoryimport'),
        ('sso', '0007_alter_evecharacter_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SignatureScanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seq', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatSignatureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. Off = the feature is dark for everyone.')),
                ('max_active_per_pilot', models.PositiveSmallIntegerField(default=5)),
                ('refresh_interval_hours', models.PositiveSmallIntegerField(default=6)),
                ('snapshots_enabled', models.BooleanField(default=True)),
                ('revoke_on_leave', models.BooleanField(default=False, help_text='When a pilot leaves the corp, also delete their signature images.')),
                ('max_featured_trophies', models.PositiveSmallIntegerField(default=4)),
                ('default_layout', models.CharField(choices=[('identity', 'Identity'), ('tactical', 'Tactical'), ('minimal', 'Minimal')], default='identity', max_length=16)),
                ('default_period', models.CharField(default='30d', max_length=16)),
                ('allowed_size_presets', models.JSONField(default=apps.killboard.models._default_size_presets)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='killboard.signaturebackground')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('public_token', models.CharField(blank=True, max_length=24, unique=True)),
                ('mode', models.CharField(choices=[('live', 'Live (auto-refreshing)'), ('snapshot', 'Snapshot (frozen)')], default='live', max_length=8)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('layout', models.CharField(choices=[('identity', 'Identity'), ('tactical', 'Tactical'), ('minimal', 'Minimal')], default='identity', max_length=16)),
                ('size_preset', models.CharField(choices=[('compact', 'Compact (468×120)'), ('standard', 'Standard (600×150)'), ('wide', 'Wide (728×120)'), ('card', 'Card (600×200)')], default='standard', max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('frozen', 'Frozen')], default='active', max_length=8)),
                ('render_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Rendered'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('dirty', models.BooleanField(default=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('render_error', models.CharField(blank=True, max_length=300)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('config_version', models.IntegerField(default=1)),
                ('snapshot_taken_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_signatures', to='sso.evecharacter')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='killboard.signaturebackground')),
            ],
            options={
                'indexes': [models.Index(fields=['character', 'status'], name='sig_char_status_idx'), models.Index(fields=['status', 'dirty', 'rendered_at'], name='sig_status_dirty_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mode', 'live'), ('snapshot_taken_at__isnull', False), _connector='OR'), name='ck_sig_snapshot_ts')],
            },
        ),
    ]
