"""The notification-event registry + governance policy.

Every place in the app that *pushes* a message out (a Discord/Slack/Telegram/WhatsApp
broadcast, an EVE-mail digest, an in-app alert generated by a background job) is
catalogued here as a **notification event**. The registry is the single source of
truth for:

* **documentation** — one authoritative list of what generates notifications
  (mirrored in ``handbooks/reference/background-jobs.md``);
* **governance** — each event carries an *audience* (who it is for) and a
  *sensitive* flag (is it leadership-oriented?). Leadership-oriented events must
  never reach a mass chat channel; they resolve to a leadership *classification*
  that the Pingboard sink (:func:`apps.pingboard.services.broadcast_text` and the
  :class:`~apps.pingboard.dispatch.AlertDispatcher`) refuses to post to a channel
  whose ``max_classification`` ceiling is below it;
* **configuration** — leadership tunes each event (enable/disable, change the
  audience, adjust the severity floor) and sets *who* counts as corp leadership,
  from the ``/ops/admin/notifications/`` console page, with no deploy.

Policy overrides live in the ``pingboard.notifications`` config document (the exact
``apps.pingboard.config`` versioned-JSON pattern); this module only reads them.
The registry defaults encode today's shipped behaviour, so an install with no
overrides behaves exactly as the catalogue describes.
"""
from __future__ import annotations

from dataclasses import dataclass

from . import config

# --- audience → classification -------------------------------------------------
# The audience an event is *for* determines the lowest channel classification that
# may carry it. ``corp``/``public``/``member`` are corp-internal (any channel);
# ``officer`` is high-command; ``director``/``admin`` are director-eyes-only; a
# targeted ``user``/``users`` DM must never fan out to a shared channel, so it is
# treated as director-eyes-only for broadcast purposes (per-recipient legs — in-app,
# EVE-mail, verified DM handles — still deliver to exactly the addressed pilots).
_AUDIENCE_CLASSIFICATION: dict[str, str | None] = {
    "corp": None,
    "public": None,
    "member": None,
    "officer": "high_command",
    "director": "director_eyes_only",
    "admin": "director_eyes_only",
    "user": "director_eyes_only",
    "users": "director_eyes_only",
}

# Audience values a director may pick for an event on the console.
AUDIENCE_CHOICES = ("corp", "officer", "director")
_LEADERSHIP_ROLE_CHOICES = ("member", "officer", "director", "admin")


def classification_for_audience(audience: str | None) -> str | None:
    """The classification tier an audience string implies (``None`` = corp-internal)."""
    return _AUDIENCE_CLASSIFICATION.get(audience or "corp", None)


# --- the catalogue -----------------------------------------------------------
@dataclass(frozen=True)
class Event:
    """One catalogued notification event.

    ``sensitive`` marks leadership-oriented traffic; its default audience is a
    restricted role, so out of the box it never reaches a mass chat channel. Leadership
    can widen the audience to ``corp`` (opting into a broadcast) or designate a
    leadership channel (raise a provider's ``max_classification`` ceiling) — both via
    the console. ``broadcast`` records whether the event fans out to chat channels at
    all (vs. purely in-app / EVE-mail). ``min_severity`` applies only to the
    recommendation digest.
    """

    key: str
    label: str
    description: str
    group: str
    source_service: str
    audience: str = "corp"
    sensitive: bool = False
    broadcast: bool = True
    min_severity: int | None = None
    triggers: str = ""  # human note: what/when fires it (for the docs + UI)

    def defaults(self) -> dict:
        d = {"enabled": True, "audience": self.audience}
        if self.min_severity is not None:
            d["min_severity"] = self.min_severity
        return d


# Groups (display order + labels for the console).
GROUP_LEADERSHIP = "leadership"
GROUP_OPERATIONS = "operations"
GROUP_MEMBER = "member"
GROUP_LABELS = {
    GROUP_LEADERSHIP: "Leadership & command",
    GROUP_OPERATIONS: "Operations & defence",
    GROUP_MEMBER: "Members & community",
}

REGISTRY: tuple[Event, ...] = (
    # --- leadership / command (sensitive: keep OFF mass channels) -------------
    Event(
        key="recommendations.officer_digest",
        label="Officer recommendations digest",
        description=(
            "High-severity officer recommendations — stock shortages, doctrine readiness "
            "gaps, build-vs-buy calls, market seeding, hauling backlog and repeated combat "
            "losses (e.g. “Lost 6 × Capsule in the last 7d”)."
        ),
        group=GROUP_LEADERSHIP, source_service="recommendations",
        audience="officer", sensitive=True, min_severity=50,
        triggers="Beat recommendations.run (every 30 min) → dispatch_alerts.",
    ),
    Event(
        key="readiness.alert",
        label="Readiness alerts",
        description="Fleet-readiness findings that cross a configured alert rule (owner-routed).",
        group=GROUP_LEADERSHIP, source_service="readiness",
        audience="officer", sensitive=True,
        triggers="Beat readiness.evaluate_alerts, over open findings.",
    ),
    Event(
        key="readiness.weekly_report",
        label="Weekly readiness report",
        description="The weekly executive readiness digest — index, biggest movers, top risks.",
        group=GROUP_LEADERSHIP, source_service="readiness",
        audience="officer", sensitive=True,
        triggers="Beat readiness.weekly_report (weekly).",
    ),
    Event(
        key="pilots.leadership_briefing",
        label="Daily leadership briefing",
        description=(
            "The daily command briefing — readiness index, 24h losses, open tasks/hauls, "
            "stock shortfalls, SRP exposure and the top contributor."
        ),
        group=GROUP_LEADERSHIP, source_service="pilots",
        audience="officer", sensitive=True,
        triggers="Beat pilots.deliver_leadership_briefing (daily).",
    ),
    Event(
        key="mentorship.review",
        label="Mentorship review notices",
        description=(
            "Mentor/cadet applications pending review, pairings awaiting approval and "
            "stalled-pair nudges — officer/mentor review traffic."
        ),
        group=GROUP_LEADERSHIP, source_service="mentorship",
        audience="officer", sensitive=True,
        triggers="Mentorship application/pairing events (when the programme arms Discord).",
    ),
    Event(
        key="command_intel.report",
        label="Command-intelligence reports",
        description=(
            "Scheduled Command-Intelligence reports. Self-classifies per report and is "
            "already gated at the sink; listed here for visibility and the on/off switch."
        ),
        group=GROUP_LEADERSHIP, source_service="command_intel",
        audience="director", sensitive=True,
        triggers="command_intel.deliver_report for a ready scheduled report.",
    ),
    Event(
        key="admin_audit.integration_health",
        label="Integration health & dependency alerts",
        description=(
            "One deduped director alert when a background sync stops running, the SDE "
            "static data goes stale, or a dependency vulnerability (CVE) is found — the "
            "corp would otherwise bleed stale data until a director opens the health page. "
            "Fires once per distinct problem set and resets once healthy."
        ),
        group=GROUP_LEADERSHIP, source_service="admin_audit",
        audience="director", sensitive=True,
        triggers="Beat admin_audit.scan_integration_health (every 30 min), on state change.",
    ),
    Event(
        key="srp.sla_alert",
        label="SRP SLA & solvency alerts",
        description=(
            "One deduped SRP-officer digest when the ship-replacement queue breaches its "
            "configured service level — backlog too large, oldest claim too old, average "
            "approval wait too long, or the period budget underwater. Reuses the readiness "
            "SRP thresholds; fires once per distinct breach set and resets within SLA."
        ),
        group=GROUP_LEADERSHIP, source_service="srp",
        audience="officer", sensitive=True,
        triggers="Beat srp.scan_sla (every 2h), on breach-set change.",
    ),
    Event(
        key="sso.ingestion_token_dead",
        label="Ingestion-token liveness alerts",
        description=(
            "One nudge to the owning director when a corp-ingestion token (assets / "
            "wallet / roster / structures) dies — revoked or refresh-failing past the "
            "retry limit — so corp data doesn't silently go stale. Names the character "
            "and the data at risk; fires once per token death and re-arms on recovery."
        ),
        group=GROUP_LEADERSHIP, source_service="sso",
        audience="director", sensitive=True,
        triggers="Beat sso.scan_ingestion_tokens (every 30 min), one per token death.",
    ),
    Event(
        key="corporation.infrastructure_alert",
        label="Structure fuel & sov-ADM alerts",
        description=(
            "One deduped officer digest when a corp structure crosses the leadership-set "
            "low-fuel threshold (or runs dry) or a sovereignty system drops below the ADM "
            "floor. Thresholds are tunable on the Structure-alert settings page; fires once "
            "per distinct breach set and resets when everything is back above threshold."
        ),
        group=GROUP_OPERATIONS, source_service="corporation",
        audience="officer", sensitive=True,
        triggers="Beat corporation.scan_infrastructure_alerts (every 2h), on breach-set change.",
    ),
    # --- operations / defence (corp-wide by design) ---------------------------
    Event(
        key="esi.corp_alert",
        label="Structure / war ESI alerts",
        description=(
            "Interesting in-game ESI notifications relayed as corp alerts — structure "
            "under attack, war declared, sov reinforced, low fuel. Home-defence items are "
            "corp-wide; structure-timer/fuel items follow the officer routing default."
        ),
        group=GROUP_OPERATIONS, source_service="recommendations",
        audience="corp", sensitive=False,
        triggers="Beat recommendations.sync_notifications (Director notifications token).",
    ),
    Event(
        key="operations.fleet",
        label="Fleet & timer announcements",
        description="Fleet-op rally calls and structure-timer announcements posted by officers.",
        group=GROUP_OPERATIONS, source_service="operations",
        audience="corp", sensitive=False,
        triggers="Operations board announce / structure-timer announce.",
    ),
    Event(
        key="killboard.killfeed",
        label="Kill feed",
        description="Sizeable corp kills and losses above the configured ISK thresholds.",
        group=GROUP_OPERATIONS, source_service="killboard",
        audience="corp", sensitive=False,
        triggers="Beat killboard.run_kill_feed (kill-feed config must be enabled).",
    ),
    Event(
        key="mail_relay.corp_mail",
        label="Corp mail relay",
        description="New corporation / alliance / mailing-list mail headers relayed to chat.",
        group=GROUP_OPERATIONS, source_service="recommendations",
        audience="corp", sensitive=False,
        triggers="Beat recommendations.relay_mail (mail-scoped token required).",
    ),
    # --- members / community --------------------------------------------------
    Event(
        key="raffle.announce",
        label="Raffle announcements",
        description="Raffle open/draw/winner announcements and per-pilot ticket/winner DMs.",
        group=GROUP_MEMBER, source_service="raffle",
        audience="corp", sensitive=False,
        triggers="Raffle lifecycle events (inert until channels are armed).",
    ),
    Event(
        key="operations.formup_reminder",
        label="Form-up reminders",
        description=(
            "A T-minus reminder to a pilot who claimed a seat, before their fleet op forms "
            "up. Targeted per-pilot (only those who signed up) — never a corp-wide ping."
        ),
        group=GROUP_OPERATIONS, source_service="operations",
        audience="corp", sensitive=False,
        triggers="Beat operations.formup_reminders (every 5 min, inside the lead window).",
    ),
    Event(
        key="logistics.haul_overdue",
        label="Haul deadline & overdue nudges",
        description=(
            "A pre-deadline reminder DM to the hauler running a courier contract, and — when a "
            "haul passes its deadline and is auto-released back to the pool — a notice to the "
            "poster and the former hauler. Targeted per-pilot, never a corp-wide ping. The "
            "auto-release itself is unconditional; only these notifications are gated."
        ),
        group=GROUP_MEMBER, source_service="logistics",
        audience="corp", sensitive=False,
        triggers="Beat logistics.sweep_hauls (every 15 min).",
    ),
    Event(
        key="store.order_status",
        label="Corp Store order updates",
        description=(
            "A DM to the buyer when their Corp Store order changes status (claimed, in "
            "production, ready, delivered, cancelled). Targeted at the buyer only — never a "
            "corp-wide ping — and at most one per status change."
        ),
        group=GROUP_MEMBER, source_service="store",
        audience="corp", sensitive=False,
        triggers="A member/officer advances, claims or cancels a store order.",
    ),
    Event(
        key="planetary.colony_issue",
        label="PI colony issue nudges",
        description=(
            "A DM to a PI pilot when one of their imported colonies develops an issue — an "
            "expired extractor or an unrouted factory — so passive income doesn't silently "
            "stop. Targeted at the owner only, at most one per detected issue-set."
        ),
        group=GROUP_MEMBER, source_service="planetary",
        audience="corp", sensitive=False,
        triggers="A colony ESI import surfaces a new issue for the enrolled owner.",
    ),
    Event(
        key="raffle.enrolment_outreach",
        label="Raffle enrolment nudges",
        description=(
            "A one-time DM to an active-but-unenrolled pilot who earned would-be raffle "
            "tickets, nudging them to enrol and claim them. Officer-triggered from the "
            "ineligible report; once per pilot per contest, honours a permanent opt-out."
        ),
        group=GROUP_MEMBER, source_service="raffle",
        audience="corp", sensitive=False,
        triggers="An officer sends enrolment outreach from a contest's ineligible report.",
    ),
    Event(
        key="mining.chunk_arrival",
        label="Moon chunk-arrival reminders",
        description=(
            "An opt-in corp reminder ahead of a moon extraction's chunk arrival (default 24h "
            "and 1h before the fracture), so the corp forms up and doesn't miss the window. "
            "At most one per extraction per offset; inert until leadership arms channels."
        ),
        group=GROUP_MEMBER, source_service="corporation",
        audience="corp", sensitive=False,
        triggers="The chunk-arrival sweep reaches a configured offset before a fracture.",
    ),
    Event(
        key="killboard.watchlist_activity",
        label="Watchlist activity tripwire",
        description=(
            "An opt-in corp alert when a watched entity (hostile pilot / corp / alliance) "
            "shows up on a fresh killmail — a gate-camp / roam early warning. Per watchlist, "
            "at most one alert per entity per cooldown, on a fresh activation. A risk "
            "indicator, not a guarantee. Inert until leadership arms a watchlist + channels."
        ),
        group=GROUP_OPERATIONS, source_service="killboard",
        audience="corp", sensitive=False,
        triggers="The watchlist-activity sweep finds a watched entity on a recent killmail.",
    ),
    Event(
        key="navigation.route_watch",
        label="Saved-route camp / incursion push",
        description=(
            "An opt-in DM to the OWNER of a saved jump route when a gate camp or incursion "
            "appears on one of its systems — so a hauler scouts before undocking. Per route, "
            "only on a change in the threat set. A risk indicator, not a guarantee."
        ),
        group=GROUP_MEMBER, source_service="navigation",
        audience="corp", sensitive=False,
        triggers="The route-watch sweep finds a new camp/incursion on a watched route.",
    ),
    Event(
        key="skills.idle_queue",
        label="Idle skill-queue nudge",
        description=(
            "An opt-in reminder DMed to a pilot when one of their characters' skill queues "
            "runs dry, so they stop bleeding SP. Off by default per pilot; one nudge per "
            "empty transition, targeted per-pilot — never a shared channel."
        ),
        group=GROUP_MEMBER, source_service="skills",
        audience="corp", sensitive=False,
        triggers="Beat skills.notify_idle_queues (hourly, opted-in pilots only).",
    ),
    Event(
        key="killboard.newbro_milestone",
        label="Newbro combat milestones",
        description=(
            "A new pilot's own 'first kill / first solo / first final blow' celebration. "
            "Delivered per-pilot, and only for a recently-achieved first (never a "
            "retroactive back-congratulation)."
        ),
        group=GROUP_MEMBER, source_service="killboard",
        audience="corp", sensitive=False,
        triggers="Beat killboard.scan_milestones (nightly).",
    ),
    Event(
        key="killboard.rank_up",
        label="Combat rank-ups",
        description=(
            "A pilot's own one-time 'you reached <rank>!' celebration when they climb the "
            "combat ladder (plus a note when a rank reward is pending). Delivered per-pilot "
            "— never posted to a shared channel."
        ),
        group=GROUP_MEMBER, source_service="killboard",
        audience="corp", sensitive=False,
        triggers="Beat killboard.notify_rank_ups (nightly, after the member rollup).",
    ),
)

_BY_KEY: dict[str, Event] = {e.key: e for e in REGISTRY}


def event(key: str) -> Event | None:
    return _BY_KEY.get(key)


# --- effective policy --------------------------------------------------------
def _policy() -> dict:
    return config.get("notifications")


def resolve(key: str) -> dict:
    """The effective policy for an event: registry defaults ⊕ stored overrides.

    Returns ``{key, label, enabled, audience, sensitive, broadcast, classification,
    min_severity}``. ``classification`` is derived from the (possibly overridden)
    audience — it is what the broadcast sink checks against each channel's ceiling, so
    changing an event's audience on the console immediately changes whether it may reach
    a mass channel. An unknown key resolves to an enabled, corp-audience passthrough so a
    new caller is never silently muted before its catalogue entry lands.
    """
    ev = _BY_KEY.get(key)
    overrides = (_policy().get("events") or {}).get(key) or {}
    if ev is None:
        audience = overrides.get("audience", "corp")
        return {
            "key": key, "label": key, "enabled": bool(overrides.get("enabled", True)),
            "audience": audience, "sensitive": False, "broadcast": True,
            "classification": classification_for_audience(audience),
            "min_severity": overrides.get("min_severity"),
        }
    audience = overrides.get("audience", ev.audience)
    if audience not in _AUDIENCE_CLASSIFICATION:
        audience = ev.audience
    return {
        "key": ev.key, "label": ev.label, "enabled": bool(overrides.get("enabled", True)),
        "audience": audience, "sensitive": ev.sensitive, "broadcast": ev.broadcast,
        "classification": classification_for_audience(audience),
        "min_severity": int(overrides.get("min_severity", ev.min_severity or 0)) or ev.min_severity,
    }


def is_enabled(key: str) -> bool:
    return resolve(key)["enabled"]


def broadcast_classification(key: str) -> str | None:
    """The classification a broadcast for this event must carry (``None`` = corp-internal).

    Passed straight to :func:`apps.pingboard.services.broadcast_text`, so a leadership
    event (default audience ``officer`` → ``high_command``) is dropped by every chat
    channel that has not been explicitly designated a leadership channel.
    """
    return resolve(key)["classification"]


# --- leadership distribution -------------------------------------------------
def leadership_role() -> str:
    role = _policy().get("leadership_role", "officer")
    return role if role in _LEADERSHIP_ROLE_CHOICES else "officer"


def leadership_user_ids() -> list[int]:
    ids = _policy().get("leadership_user_ids") or []
    return [int(i) for i in ids if isinstance(i, int) or (isinstance(i, str) and str(i).isdigit())]


def leadership_audience() -> dict:
    """The audience spec that addresses corp leadership for a restricted alert.

    Explicit named recipients win when set; otherwise everyone at or above the
    configured leadership role. Used as the in-app / EVE-mail distribution for
    leadership-restricted alerts and offered to callers that want to reach leadership
    directly rather than via a channel.
    """
    ids = leadership_user_ids()
    if ids:
        return {"kind": "users", "ids": ids}
    return {"kind": leadership_role()}
